### ISSUE TITLE
after last update EDMC highjacks my computer!!

### ISSUE THREAD

**Issue by harliquin76** [Marginal/EDMarketConnector#101]
since the last update everytime I try to launch the program I get the hourglass and it will not let me, kill the task in the task manager, or shutdown my computer. it just hangs it after a while.
I even uninstalled and reinstalled same issue

**Comment by Marginal** [comment]
Can't diagnose this without a lot more info, but the fact that you can't even shutdown your computer suggests something seriously wrong with your computer. Could be lots of things - perhaps your antivirus or firewall is going crazy.

**Comment by harliquin76** [comment]
it only does it after I try to start the program it works 100% fine as long as I don't click on it. I set up a resource mon and after launch it pegs out all 4 of my cores. tell me what debug info you need and I will happily supply it. I love the program and would like to still be able to use it

**Comment by Marginal** [comment]
That's certainly odd - it isn't doing anything that resource intensive.
- Do you see the EDMC main window appear?
- Is the there anything in the file `%TMP%\EDMarketConnector.log` ?
