### ISSUE TITLE
Installation error: Could not open key. Verify that you have sufficient access to that key.

### ISSUE THREAD

**Issue by smeggysmeg** [Marginal/EDMarketConnector#102]
Hi there. Today EDMarketConnector wouldn't launch. So, I uninstalled it with the intent to reinstall it. When I try to reinstall it, I receive the following error:

Could not open key: UNKNOWN\Components\E66BB33D46696BA40A4403405BA0900B\D36CE44061781964CBC011866B8B1242.  System error 5.  Verify that you have sufficient access to that key, or contact your support personnel.

Attached is a screenshot.
![2016-03-12 13_29_08-elite dangerous market connector](https://cloud.githubusercontent.com/assets/7536439/13724818/d885bd04-e856-11e5-88dc-7813c4e0b2c1.png)

In Event Viewer, MsiInstaller has the following error (Event ID 11402): 
Product: Elite Dangerous Market Connector -- Error 1402. Could not open key: UNKNOWN\Components\E66BB33D46696BA40A4403405BA0900B\D36CE44061781964CBC011866B8B1242.  System error 5.  Verify that you have sufficient access to that key, or contact your support personnel.

**Comment by Marginal** [comment]
System error 5 is "Access Denied".
I don't know how you got in this situation but the following should work:
- Run regedit
- Press Ctrl+F and search for the key `E66BB33D46696BA40A4403405BA0900B` - you should find it under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\UserData\S-1-5-18\Components\`. (regedit in Windows 10 build 10565 and later is a bit crashy - you may find it works better if you select the key HKEY_LOCAL_MACHINE before starting the search).
- Delete the key `E66BB33D46696BA40A4403405BA0900B`
- Reinstall EDMarketConnector.

**Comment by smeggysmeg** [comment]
I tried your steps, but to no effect. 

I went and found the registry entry listed in the error, and the permissions on it are such that I cannot even view the contents of the registry object. After taking ownership of the object, I can see that the entry does pertain to EDMarketConnector (it mentions filenames for EDMarketConnector's application files). After changing its permissions, then deleting it, I'm able to get past that error. However, a similar error then comes up identifying another registry entry, also with EDMarketConnector application files being mentioned.

All of the registry keys affected are named D36CE44061781964CBC011866B8B1242, so I will continue this process of finding them, taking ownership, and correcting permissions.

This last Windows Update (KB3140768) appears to have caused a handful of other little bugs in Windows 10. I'll put the blame there.

Once I've finished the ownership+permissions+deletion process on all of the affected registry entries, I'll write an update here.

**Comment by Marginal** [comment]
I find it hard to understand why Windows Installer would create entries under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\UserData\S-1-5-18\Components\` with permissions such that they're not accessible to the admin user. How would that ever make sense?
Could be KB3140768 - I notice that it hasn't yet ~~infected~~ installed on my Windows 10 machine and now I'm scared to reboot!

**Comment by smeggysmeg** [comment]
No luck. The Windows Installer windows just comes up then disappears. Event Viewer shows:

Event ID 1040: Beginning a Windows Installer transaction: D:\Documents\downloads\tmp\EDMarketConnector_win_210.msi. Client Process Id: 1516.
Event ID 1042: Ending a Windows Installer transaction: D:\Documents\downloads\tmp\EDMarketConnector_win_210.msi. Client Process Id: 1516.
Event ID 11707: Product: Elite Dangerous Market Connector -- Installation completed successfully.
Event ID 1033: Windows Installer installed the product. Product Name: Elite Dangerous Market Connector. Product Version: 2.1.0.0. Product Language: 1033. Manufacturer: Marginal. Installation success or error status: 0.

If I look in the folder C:\windows\installer\{044EC63D-8716-4691-BC0C-1168B6B82124} I find EDMarketConnector.exe but it isn't a valid executable.

I find nothing relating to EDMarketConnector or "Elite Dangerous Market Connector" when searching the registry.

I'm one of the lucky ones who've had trouble with Windows 10. Only on my desktop PC - my laptop is fine. I've wiped and reinstalled, but the issues always seem to return. First it was too many Start Menu entries, then Win10 Apps not working right, and now this update seems to have caused a handful of applications to need to be reinstalled. EDMC is the only application having trouble, now, though.

**Comment by smeggysmeg** [comment]
Scratch that, after the last install attempt, the program files are there! The application launches,  too. It doesn't exist in Programs and Features and doesn't appear in the Start Menu, but I've manually created a shortcut and it runs just fine.

**Comment by Marginal** [comment]
Good to hear.
You may (or may not) find that the Start Menu shortcut appears at some point - the Windows 10 Start Menu is a bit of a mystery.
