### ISSUE TITLE
"Invalid Credentials" App on PC, Game on Xbox One

### ISSUE THREAD

**Issue by BladeEdge545** [Marginal/EDMarketConnector#104]
Hello!

I just installed this application, and i am having trouble validating my credentials for the first time when running this app.

I changed my password on the Frontier store after the authentication failed, so i assume i might have to wait a few hours for the information to update

My question is this, Can this app work for Xbox One players?
My Frontier Store account i gave the app is also connected to my Microsoft Account that purchased the game.

Does the app only work for PC players? Or can it work with Xbox One

**I am installing the app on my Windows laptop, my information is on the Xbox One platform.

**Comment by Marginal** [comment]
Unfortunately I've heard that this app works for Xbox One players.
I suspect this is because your Xbox account isn't linked to a Frontier account?.

**Comment by BladeEdge545** [comment]
My xbox account is linked to my Frontier account,

Will it be possible to make it accessible to xbox one players? or would you likely have to go through Microsoft to do such a thing?

**Comment by Marginal** [comment]
Not sure whether it's Microsoft, Frontier or both who would have to change something, but right now the API that this app uses doesn't appear to work for Xbox users.

**Comment by mavericknoob** [comment]
This is not just an XBox issue. I'm having the same error and I'm running the app on Windows 7

**Comment by Mesberstov482** [comment]
Would love to have connections with Xbox and inara, but that probably won't happen anytime soon.

**Comment by Marginal** [comment]
Nope, sorry.

**Comment by cmdravulon** [comment]
Running PC Windows 8.1 Having the same issue.  Cmdr Name and group is displayed along with ship name and canon news.  Below 'Update' is text 'Error: Invalid Credentials' - re-entered password to no effect. Disabled EDSM/INARA and plugins: restarted app, error persists. Screenshot attached.
![edmc_invalid-credentials](https://user-images.githubusercontent.com/37553637/37615116-637a4c30-2ba4-11e8-8b3b-cb0c45f95009.JPG)

**Comment by cmdravulon** [comment]
Resolved my issue - as Simple as forgetting that I'd changed the email address associated with my frontier account.  Updated the game client but hadn't updated EDSM as I wasn't using it at the time.
