### ISSUE TITLE
Local times are reported as UTC times

### ISSUE THREAD

**Issue by andrewgoz** [Marginal/EDMarketConnector#107]
EDMC is transmitting local times to both EDProxy and EDSM as if they were UTC. For example, if my local time zone is UTC+8 and the local time is 20:00:00, then EDMC will send a DateUtc:"2016-04-15T20:00:00" to EDProxy instead of "2016-04-15T12:00:00". Similar incorrect times are sent to EDSM and end up in the explorer log where I have to manually delete them (one at a time - very annoying).

I have a Wireshark packet capture if you think it will help.

**Comment by andrewgoz** [comment]
I've just looked at the capture more closely. When jumping between systems EDMC is taking the DateUtc from EDProxy "12:00" and performing an unnecessary UTC time correction and sending "04:00" as the time to EDSM.

**Comment by andrewgoz** [comment]
Fix is in attached file...

[edmc_utc.patch.txt](https://github.com/Marginal/EDMarketConnector/files/233950/edmc_utc.patch.txt)

**Comment by Marginal** [comment]
Thanks.
