### ISSUE TITLE
Multiple Commanders - Doesn't ask for Re-Authentication

### ISSUE THREAD

**Issue by Red13x3** [Marginal/EDMarketConnector#108]
I found a problem (on the Mac, if that makes any diff.) with initially logging in with the details of one commander I have (which is out near Sag A*) but then realising I want ED MC working with my other commander that is in the bubble.

I went to Preferences and put in my other login details, and although I keep getting emails from Frontier with my new Authentication code, ED MC does not pop up the dialog box asking me to enter that code in.

So right now, it isn't working at all, even though I thought I could delete the App and re-install it, hoping it would lose all the Preference data. It didn't. :(  Can someone point me to how I can wipe it all clean and do a fresh install so it goes through the process of authorising my commander properly?

**Comment by Marginal** [comment]
What error does EDMC give when you press "Update"?

Please try:
- Quit EDMC.
- Delete the file `~/Library/Application Support/EDMarketConnector/cookies.txt` (to see the `~/Library` folder in Finder go to your home folder, hold down ⌥ and choose Go -> Library).
- Restart EDMC and Update.
