### ISSUE TITLE
"Error: Can't connect to EDDN" for weeks

### ISSUE THREAD

**Issue by xentac** [Marginal/EDMarketConnector#109]
Every time I try to Update EDMC thinks for a bit "Sending data to EDDN..." then tells me "Error: Can't connect to EDDN".  I've been seeing this message for weeks.

Is there anything I can test on my end to figure out what the problem is?  I couldn't find any higher level logging than the status bar.

**Comment by Marginal** [comment]
Are you still having this problem?

**Comment by compro01** [comment]
I am having this problem also.  It connects fine to EDSM, but when it tries to send to EDDB, it goes unresponsive for about 10 seconds, then gives me that error.

**Comment by xentac** [comment]
Yes, I am still having this problem.

**Comment by xentac** [comment]
Oh wait... I just noticed there was a new release.  I'll try to today.

**Comment by xentac** [comment]
With the newest release to 2.11, I still have the "Error: Can't connect to EDDN" problem.

**Comment by Marginal** [comment]
EDMC is just connecting to EDDN over http, so even if you're behind a proxy or firewall it should still work.

Can you [run from source](https://github.com/Marginal/EDMarketConnector/wiki/Running-from-source)? If so, the program will print out some diagnostic information on error.

**Comment by xentac** [comment]
C:\Users\Jason\Downloads\EDMarketConnector-master>c:\Python27\python.exe EDMarketConnector.py
Monitoring "c:\program files (x86)\steam\steamapps\common\Elite Dangerous\Products\elite-dangerous-64\Logs"
Invalid "demandBracket":"" (<type 'unicode'>) for "Skimer Components"
Invalid "demandBracket":"" (<type 'unicode'>) for "Basic Medicines"
Traceback (most recent call last):
  File "EDMarketConnector.py", line 447, in getandsend
    eddn.export_commodities(data)
  File "C:\Users\Jason\Downloads\EDMarketConnector-master\eddn.py", line 70, in export_commodities
    'commodities' : commodities,
  File "C:\Users\Jason\Downloads\EDMarketConnector-master\eddn.py", line 39, in send
    r = requests.post(upload, data=json.dumps(msg), timeout=timeout)
  File "c:\Python27\lib\site-packages\requests\api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "c:\Python27\lib\site-packages\requests\api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "c:\Python27\lib\site-packages\requests\adapters.py", line 459, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPConnectionPool(host='eddn-gateway.elite-markets.net', port=8080): Max retries exceeded with url: /upload/ (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x0000000008D2A320>, 'Connection to eddn-gateway.elite-markets.net timed out. (connect timeout=10)'))

**Comment by xentac** [comment]
When I try to access eddn-gateway.elite-markets.net:8080 in Chrome, it also times out.

I'm able to resolve the address and ping it:

C:\Users\Jason\Downloads\EDMarketConnector-master>ping eddn-gateway.elite-markets.net

Pinging eddn-gateway.elite-markets.net [199.115.222.234] with 32 bytes of data:
Reply from 199.115.222.234: bytes=32 time=21ms TTL=51

And it does respond on port 80, but only with the status window.  Interestingly, on that window I see that there are no messages received on any of the gateways (but I do see messages received on the relays).

**Comment by AnthorNet** [comment]
You seems to have a problem with port 8080 being inaccessible.
Thus the timeout, and the no stats in the status page which query the gateway on port 8080 too..

**Comment by xentac** [comment]
I would tend to agree.  I just watched the packets leave my router and they never returned.  I doubt it's my router config, but maybe comcast is blocking the port?  That seems a bit silly.

I'll check from work tomorrow.

**Comment by AnthorNet** [comment]
Here is the status now: 
![gatewaystatus](https://cloud.githubusercontent.com/assets/654353/16512934/9c4f3fc0-3f60-11e6-9f32-93b8b6c1f852.png)

And if all works well going to that page: http://eddn-gateway.elite-markets.net:8080/upload/
Should give you a Error: 405 method not allowed

**Comment by xentac** [comment]
It works fine at work.  I'm going to say that my ISP (comcast) is blocking 8080 dest ports.

Trying to access other sites on port 8080 also doesn't work.

Interestingly accessing http://eddn-gateway.elite-markets.net:9090/ works just fine (the stats port for http://eddn-gateway.elite-markets.net/).

Is it possible to expose a different eddn port in addition to 8080 to get around stupid blocks like mine?

**Comment by Marginal** [comment]
It would be odd for an ISP to block port 8080 outgoing. [This FAQ](https://customer.xfinity.com/help-and-support/internet/list-of-blocked-ports/) suggests that Comcast doesn't.
Have you checked your router's firewall / port forwarding config?

**Comment by xentac** [comment]
Awww, I was proven wrong...

Yeah, it was a router config.  I was mis-forwarding that port.

**Comment by 701yekeparG** [comment]
Hello, I have the same problem! Is someone willed and skilled enough, to help me to fix that problem?

Regards
