### ISSUE TITLE
App just bounces on startup then exits on Mac Yosemite.

### ISSUE THREAD

**Issue by dh219** [Marginal/EDMarketConnector#11]
The app was working fine until the EDDN 2 update whereupon it reported 'server is down' then would never start up again. I've updated again since and same result.

I tried running it from the command line and this is all it says:-
```
./EDMarketConnector.app/Contents/MacOS/E\:D\ Market\ Connector 
Jun 30 23:49:06 Tonic-2.local E:D Market Connector[11150] <Notice>: 2015-06-30 23:49:06.281 E:D Market Connector[11150:2795669] An uncaught exception was raised
Jun 30 23:49:06 Tonic-2.local E:D Market Connector[11150] <Notice>: 2015-06-30 23:49:06.282 E:D Market Connector[11150:2795669] Error (1000) creating window shape
Jun 30 23:49:06 Tonic-2.local E:D Market Connector[11150] <Notice>: 2015-06-30 23:49:06.282 E:D Market Connector[11150:2795669] (
Jun 30 23:49:06 Tonic-2.local E:D Market Connector[11150] <Notice>: 	0   CoreFoundation                      0x00007fff8a7a666c __exceptionPreprocess + 172
Jun 30 23:49:06 Tonic-2.local E:D Market Connector[11150] <Notice>: 	1   libobjc.A.dylib                     0x00007fff869be76e objc_exception_throw + 43
Jun 30 23:49:06 Tonic-2.local E:D Market Connector[11150] <Notice>: 	2   CoreFoundation                      0x00007fff8a7a651d +[NSException raise:format:] + 205
Jun 30 23:49:06 Tonic-2.local E:D Market Connector[11150] <Notice>: 	3   AppKit                              0x00007fff90c7f0ae _NSCreateWindowWithOpaqueShape2 + 154
Jun 30 23:49:06 Tonic-2.local E:D Market Connector[11150] <Notice>: 	4   AppKit                              0x00007fff90c7d906 -[NSWindow _commonAwake] + 1882
Jun 30 23:49:06 Tonic-2.local E:D Market Connector[11150] <Notice>: 	5   AppKit                              0x00007fff90c7d009 -[NSWindow _makeKeyRegardlessOfVisibility] + 85
Abort trap: 6
```

**Comment by Marginal** [comment]
Could be [this bug](http://core.tcl.tk/tk/tktview/c84f660833546b1b84e7) in Tk on OSX. Some questions:
- Do you have a dual monitor setup, where the secondary monitor has higher resolution than the primary (e.g. large display attached to a laptop?)
- What does it say when you type `defaults read uk.org.marginal.edmarketconnector geometry` in the Terminal?
- Does typing `defaults delete uk.org.marginal.edmarketconnector geometry` allow you to launch the app on the primary display?

**Comment by dh219** [comment]
Hi there.

I do have a secondary display, but it's lower resolution. I've tried disabling it and running in mirrored mode, but no change.

`$ defaults read uk.org.marginal.edmarketconnector geometry
+23+-337`

`defaults delete uk.org.marginal.edmarketconnector geometry` Worked, though. Thanks!

**Comment by Marginal** [comment]
Looks like it is [this bug](http://core.tcl.tk/tk/tktview/c84f660833546b1b84e7) in Tk on OSX then.
You may have to repeat the `defaults delete ...` in order to get the app to run until I release a version with this fix.

**Comment by dh219** [comment]
Thanks for the help. I'm not convinced it's that bug as I've never used it on my second monitor (it's a projector only used for media) and quitting and running again now shows it working fine.

The problem definitely manifested directly after the update I ran from within the app itself which might be co-incidence but I'll keep an eye on it at next release.

Cheers!
