### ISSUE TITLE
"Invalid Logindata" since 2.1 Release

### ISSUE THREAD

**Issue by heavykick** [Marginal/EDMarketConnector#111]
Hi,

the update just did go live, and I can't send data. I got the Message: "Fehler: Ungültige Logindaten"
My translation: "Error: Invalid Logindata"

The Password and username are correct!

**Comment by nalyu** [comment]
In english it says "Error: Invalid Credentials"

**Comment by Marginal** [comment]
Looks like the API is still down. We've seen the API stay down for some time after major updates in the past.

**Comment by butler1475** [comment]
wouldn't coun on it just being the api down. Slopey's tool sent back an immediate response, but instead of a system name (LHS 3836) it came back as xyz coordinates

**Comment by texaspete** [comment]
I get the Invalid Credentials error, but I'm also unable to login to the EliteDangerous app on my iPhone.

**Comment by IamNovus** [comment]
Invalid login :/

**Comment by Clampitts** [comment]
Also get invalid login....

**Comment by AnthorNet** [comment]
HI,
We are aware of that issue, and working on it.

**Comment by Juddz** [comment]
Again, I commend you on your speed and diligence with this amazing app. I saw the same problem this morning and you're already working on it.
Thank you guys [thumbs up emote]

**Comment by Marginal** [comment]
Looks like Frontier have fixed this.
If you're still having problems please try quitting and restarting the game and/or logging in to the Frontier store using the link in the Laucher.
