### ISSUE TITLE
400 Client Error: Bad Request

### ISSUE THREAD

**Issue by NKDavis** [Marginal/EDMarketConnector#113]
Hi,

Thanks for fixing the Invalid Credentials issue with EDH 2.1

Now, when I try to send Station data through I am getting this error message.

Is it perhaps because there are so many new materials in the Commodities Market and they are not all loaded in the back-end database?

**Comment by Barracuda4Surf** [comment]
Hi! 
I have the same issue. At first I had the "Invalid Credentials" and now I get the "400 Client Error: Bad Request" message when when  updating EDMC.

Cross-checking with the station market data on EDDB, it doesn't seem to get updated as well ("Price Update: X mins ago")

**Comment by DeadMeatGF** [comment]
I'm getting the same error - I'm thinking the same as NKDavis

**Comment by PierreReynaud** [comment]
Had the invalid credentials issue but now it's been solved thanks :D ! now i have the saem error , 400 client error, but I went to the EDDB and it does update the data from the market when i click update or maybe someone else was there at the same time as me and updated it at the same time but i doubt it or it's just my imagination. Can someone confirm this ?

**Comment by AnthorNet** [comment]
If you encounter this error, please try to send us the JSON returned by the API, I'm not in the bubble actually to test things and add the new outfit classes to EDDN

**Comment by Barracuda4Surf** [comment]
Where do I find the json and where should I upload it to?
Thx in advance!

**Comment by Marginal** [comment]
If you're able to [run from source](https://github.com/Marginal/EDMarketConnector/wiki/Running-from-source) the program will produce the .json output file.

**Comment by libbkmz** [comment]
I've got some json files. But, actually my ED Engineers are downloading, so I didn't log in with engineers update, if it makes sense
https://gist.github.com/libbkmz/bf3720f0e4d3ce5816b1e55f223b1772

**Comment by Marginal** [comment]
I can't see anything novel in that json file. Is this from a station where you get the 400 error?

**Comment by scamfield** [comment]
When using EDMarketConnector and tcpdump I can see the following FATAL error when sending to EDDN :

Server: nginx/1.0.15
Date: Sat, 28 May 2016 10:47:00 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Content-Length: 168

FAIL: [<ValidationError: "{'category': 'hardpoint', 'rating': '?', 'mount': 'Fixed', 'name': 'Pulse Laser', 'class': '4'} is not valid under any of the given schemas">]

**Comment by Marginal** [comment]
@scamfield
Can you capture the json body that EDMC sends to EDDN, and feed it and the schema https://github.com/jamesremuscat/EDDN/blob/master/schemas/outfitting-v1.0.json into http://jsonschemalint.com/ ?

**Comment by scamfield** [comment]
@Marginal 
It appears to the failing on these

```
{
  "category": "hardpoint",
  "class": "4",
  "mount": "Fixed",
  "name": "Pulse Laser",
  "rating": "?"
}
```
```
{
  "category": "hardpoint",
  "class": "4",
  "mount": "Gimballed",
  "name": "Pulse Laser",
  "rating": "?"
}
```
```
{
  "category": "hardpoint",
  "class": "4",
  "mount": "Gimballed",
  "name": "Multi-Cannon",
  "rating": "?"
}
```
Screenshot:

<img width="675" alt="screen shot 2016-05-28 at 12 35 28" src="https://cloud.githubusercontent.com/assets/5695457/15627093/0d578a92-24d1-11e6-9b9b-ae12148b7d7d.png">

**Comment by AnthorNet** [comment]
Based on that, it seems that EDMC needs to update his list to comply with the EDDN schema?

**Comment by koreldan** [comment]
to me worked by deleting ( click into the field than backspacing all the chars ) the API key and pasting again into the field on Edmc

**Comment by ThomasHeliase** [comment]
Also getting 400 Client Error: Bad Request, at Maia [Darnielle's Progress].  No .json - not running in debug.

**Comment by NKDavis** [comment]
The problem definitely appears to be with the Outfitting data. Data from Stations which do not provide Outfitting Services go through with no issues.

**Comment by brittmd99** [comment]
I was able to get around this at least at the station I was having an issue with - The data from the companion app had data for "Skimer Components" (which is wierd because that doesn't show up in game in the market, and I believe it's supposed to be named Skimmer Components to boot).  That record had "" for the Demand Bracket instead of a number.  I hacked the eddn.py python script to just replace "" with a 0.  It's not elegant and it is probably not a complete fix but it did work for at least one station.

**Comment by libbkmz** [comment]
My little research for this issue.

If I issue .exe version, on every place I get 400 error. But, When I look at eddb.io it shows that market data is updated, but outfitting and shipyard dont. 

If I try to use from python source code, everything works fine, and market shipyard and outfiting data is updated without 400 bad request issue.

**Comment by brittmd99** [comment]
It seems my little hack isn't what made it work, just the fact that I too was running it from source just like libbkmz.  I ran the original file and it worked as well.  It spits out the following messages in the console window:
Invalid "demandBracket":"" (<type 'unicode'>) for "Skimer Components"
Invalid "demandBracket":"" (<type 'unicode'>) for "Basic Medicines"
Invalid "demandBracket":"" (<type 'unicode'>) for "Liquor"
Outfitting: ('Pulse Laser', None, '4', '?')
Outfitting: ('Beam Laser', None, '4', '?')
Outfitting: ('Multi-Cannon', None, '4', '?')

**Comment by AnthorNet** [comment]
Thanks for that report will look into it

**Comment by Athanasius** [comment]
This appears to now be resolved, at least my EDMC 2.1.0.0 is now able to send data to EDDN (which then shows up in eddb.io).

**Comment by Athanasius** [comment]
Oh maybe I spoke too soon.  Perhaps I got lucky with stations that didn't have the culprit weapons available.

**Comment by derf-vader** [comment]
No still seeing this error landed at Copernicus Orbital in Ngadakhis and the market update worked
5 min later at Baillaud Ring in Kuwemargl got the error again

**Comment by IamNovus** [comment]
any work on a fix?

**Comment by nemesyssoft** [comment]
I think the fix should come from eddn.io. I think that's the part that is broken, it chokes on new weapons.

**Comment by AnthorNet** [comment]
@nemesyssoft I will gladly updates when I receive the buggy one !
