### ISSUE TITLE
Errno 13 Permission denied <name-station-time.json> on each update in the status bar

### ISSUE THREAD

**Issue by dvillechalane** [Marginal/EDMarketConnector#12]
Hi, thanx for all the good works done here !

I've currently installed the latest version and on each station update i've got the error described in the title + a screenshot : 
http://cl.ly/image/423W111Z3M0R

**Comment by IGaunt** [comment]
I have the same problem

**Comment by Marginal** [comment]
Sorry about that. Fixed in [Release 1.53](https://github.com/Marginal/EDMarketConnector/releases/latest).

**Comment by dvillechalane** [comment]
Big Thanx : no more error on my first update test !

Good Work !

**Comment by Marginal** [comment]
Great. Thanks for the confirmation.
