### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by SirXen0** [Marginal/EDMarketConnector#120]
A box saying configuring files to install appears then disappears shortly after and the process lingers in the task manager but nothing else occurs.

Latest Release, Win version.

**Comment by Marginal** [comment]
Need more info:
- Do you get the standard [User Account Control](https://en.wikipedia.org/wiki/User_Account_Control#/media/File:Windows_7_UAC.png) dialog, and did you answer "Yes"?
- Does "Elite Dangerous Market Connector" appear in the Start menu?

**Comment by SirXen0** [comment]
UAC is disabled, so that never appears.
And no.

**Comment by HeliosFCB** [comment]
Same issue as described above.
Using Windows 10

**Comment by Marginal** [comment]
Please temporarily disable your antivirus and try again.
