### ISSUE TITLE
"Play sound" seems to have randomly stopped working

### ISSUE THREAD

**Issue by Malvenue** [Marginal/EDMarketConnector#122]
"Play sound" selected on the Hotkey tab and while it appears EDMC updates, no sound plays.  This started happening quite randomly several days ago before the latest update to 2.1.2.0

**Comment by Marginal** [comment]
I can't think of any reason why that should happen.
Please try with 2.13.

**Comment by Malvenue** [comment]
It helps to not have the app muted in your sound mixer!

No idea how that happened.  Sorry for the bother!

**Comment by Marginal** [comment]
;-)
