### ISSUE TITLE
Add "Show patchnotes button"

### ISSUE THREAD

**Issue by borbra** [Marginal/EDMarketConnector#123]
Add a button to show patchnotes from the client. The patchnotes window is there when there is new update, but atm there is no way of getting that window again once closed.

**Comment by Marginal** [comment]
The [Sparkle](https://github.com/sparkle-project/Sparkle) and [winsparkle](https://github.com/vslavik/winsparkle) frameworks that handle the download and display of updates don't provide this functionality, so marking as won'tfix.

FYI the update history is available [here](https://github.com/Marginal/EDMarketConnector/releases).

**Comment by borbra** [comment]
Oh well, thanks for the very quick respons :) bummer that it can't do it, but it's only a minor thing on a otherwise very nice program.
