### ISSUE TITLE
automatically make a log entry not working

### ISSUE THREAD

**Issue by marcus-antonius** [Marginal/EDMarketConnector#124]
For the past few days I've noticed that I have to manually update the ED Market Connector when entering a new system.  It also is not sending any data to EDSM unless I manually update after each jump.  Not sure if it's to do with the update to 2.1.03 or if it's something on my machine.

**Comment by Marginal** [comment]
Does [Doesn't track Systems visited](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#doesnt-track-systems-visited) give any pointers?

**Comment by marcus-antonius** [comment]
Thanks for getting back to me, I see the problem now although maybe not the solution.  

There are two users of this PC and one uses Steam and the other (me) uses the FD Program Files version.  

Is there any way to get the app to look in the Program Files version rather than the Steam version by default?

**Comment by marcus-antonius** [comment]
Never mind.  Arranged to swap account logins with the steam user and ED Market Connector updates automatically for me again.  Thanks for pointing me in the right direction Marginal.

**Comment by Marginal** [comment]
Glad you found a workaround.
Or you could both play the same version (Steam or non-Steam), but from different Windows accounts.
