### ISSUE TITLE
Can't install on Win 10

### ISSUE THREAD

**Issue by phixson** [Marginal/EDMarketConnector#125]
Install fails with - 
![image](https://cloud.githubusercontent.com/assets/5022134/16455152/55f28de6-3de1-11e6-9f21-8240fa83f80e.png)

**Comment by Marginal** [comment]
The error message suggests that the Windows Installer Package (`.msi`) file is truncated or corrupt. Some things you can try:
- [Download](https://github.com/Marginal/EDMarketConnector/releases/latest) it and try to install again.
- If you have it on a network drive, move or copy it to a local drive before trying to install.
- Temporarily disable your antivirus.

**Comment by phixson** [comment]
That got it, Thanks.
