### ISSUE TITLE
Cannot connect to EDDN

### ISSUE THREAD

**Issue by omgsetzz** [Marginal/EDMarketConnector#127]
Sunday 17 July 2016, 4:30 pm AEST.

Version 2.1, open play, in Ross 847 (Lee Station), cannot connect to EDDN when pressing update.

Seemed to be working fine on my previous stop in Na Chem (Rorscharch Horizons)

Thanks!

**Comment by Marginal** [comment]
Might be a network problem somewhere between you and EDDN. Is it working now?

**Comment by omgsetzz** [comment]
Yes, it's working now - funny when it happened, cuz it was working on the
stations before and after, just not that particular one I mentioned.

Also just wanted to say thank you for your contribution to the E:D
community mate. Love it.
