### ISSUE TITLE
New install - Needs Authentication but doesn't pop up request

### ISSUE THREAD

**Issue by Red13x3** [Marginal/EDMarketConnector#129]
I have E:DMC running fine on a Win10 laptop but on this Win7 machine which is actually my main gaming platform I have tried to install 2.1.4.0 (fresh) and all seems fine except it needs me to Authenticate but does not pop up the dialogue box to allow me to enter the Authentication code that has arrived in my email. :(

**Comment by Red13x3** [comment]
OK... I found it. You apparently have to go to >File > Status... before it then pops up the Authentication request dialogue box. You enter it and THEN it shows you the Status. I think this Auth dialogue box should pop up as soon as you enter new commander details into the Settings... Or at the very least, put a note in the Settings > Credentials section to inform the user to go to File > Status and enter the auth code.

**Comment by Marginal** [comment]
It prompts for the authentication code the first time that you do anything that requires authentication.
