### ISSUE TITLE
Entry "VerboseLogging="1"

### ISSUE THREAD

**Issue by nepomuk16321** [Marginal/EDMarketConnector#130]
After each start the entry " VerboseLoggin="1" " is written in the file "AppConfigLocal.xml". 
This is not necessary if the entry exists. Other tools have a problem with duplicate entries, for example "GUI for TradeDangerous (TDHelper)" !

Thanks for correcting, Mathias

ps. sorry fo my bad english

**Comment by Marginal** [comment]
EDMC is supposed to detect when VerboseLogging is already enabled. Please attach your AppConfig or AppConfigLocal file here.

**Comment by nepomuk16321** [comment]
Thanks for your fast answer !
Here is my "AppConfigLocal.xml"
```
<?xml version="1.0" encoding="utf-8"?>
<AppConfig>
  <Network
		VerboseLogging="1" />
</AppConfig>
```
First EDMC makes a backup ("AppConfigLocal_backup.xml") from the file "AppConfigLocal.xml" and then writes a new line, although the entry already exists. Maybe just me?

**Comment by Marginal** [comment]
EDMC is not parsing your file correctly. Please change the file to:
```xml
<AppConfig>
	<Network
		VerboseLogging="1"
	>
	</Network>
</AppConfig>
```

**Comment by Marginal** [comment]
EDMC is not parsing your file correctly. Please change it to:
```xml
<AppConfig>
	<Network
		VerboseLogging="1"
	>
	</Network>
</AppConfig>
```

**Comment by nepomuk16321** [comment]
Ok, I'll try immediately. Thank you !!! :-))))

**Comment by nepomuk16321** [comment]
:-)
That was it ! It works. Thank you so much !
Greetings Mathias
