### ISSUE TITLE
Each EDMC run inserts superfluous "VerboseLogging" element into AppConfig_local.xml

### ISSUE THREAD

**Issue by StarLightPL** [Marginal/EDMarketConnector#133]
I am running EDProxy first then EDMC 2.1.5.0 from a .bat file. EDProxy inserts the VerboseLogging between Port and upnpenabled tags, while each run of EDMC duplicates the VerboseLogging tag in the beginning.
```
<AppConfig>
	<Network
		VerboseLogging="1"
		VerboseLogging="1"
		VerboseLogging="1"
		VerboseLogging="1"
		VerboseLogging="1" DatestampLog="1" LogFile="netLog" Port="0" VerboseLogging="1" upnpenabled="1" />
</AppConfig>
```

The app should check if VerboseLogging isn't enabled already.

**Comment by Marginal** [comment]
EDMC's parsing of the AppConfig file is a little naive. It expects to see an explicit closing `</Network>` tag, e.g.:

```xml
	<Network
		Port="0"
		VerboseLogging="1"
		upnpenabled="1"
		LogFile="netLog"
		DatestampLog="1"
		>
	</Network>
```

**Comment by StarLightPL** [comment]
Adding closing </Network> tag helped; however be aware that blindly adding elements makes the xml not valid and as a result broke EDProxy (reported there also). But, fair enough, workaround offered, issue closed.
