### ISSUE TITLE
Security password and username - E:D

### ISSUE THREAD

**Issue by A-312** [Marginal/EDMarketConnector#134]
Hi,

Today, I download your app for the first time. Why do we have not "remember creditential" checkbox ? I don't want to see my password in regedit...

It's the best way to lose this account...

![](http://i.imgur.com/bxGCJQD.png)

(I have read : https://github.com/Marginal/EDMarketConnector/issues/89 )

**Comment by Marginal** [comment]
Duplicate of #89

**Comment by A-312** [comment]
Are you kidding me?

**Comment by Marginal** [comment]
> Are you kidding me?

No; if your computer is subverted then you're screwed - all your information is at risk whether stored in the registry or typed in at the keyboard.
If your computer isn't subverted then the registry is as good a place as any to store information.
