### ISSUE TITLE
Application remains in process list on closing

### ISSUE THREAD

**Issue by KellyRayburn** [Marginal/EDMarketConnector#136]
When I close the application, it remains in the process list. I noticed this because I had written a small Visual Basic program that would execute the program, a clock I use, and the Elite Dangerous Launcher. It checks the process list and if the process isn't found, it executes the program. If it is found, it just exits that portion of the code.

I was playing and exited for a bit. I came back and when I ran my program, it didn't call up the Market Connector. I did some checking on my code and saw that it was looking for the program in the processes list. Yeah, it had been a while since I wrote it. I checked the processes and there it was even though it wasn't in the system tray or active on the desktop.

I'm using Windows 10.

**Comment by Marginal** [comment]
I can't reproduce this problem.
Does EDMC remain in the process list if you launch it from the Start Menu and then exit? If so then your program may be at fault. Are you calling CloseHandle() on the handles returned in the [PROCESS_INFORMATION](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684873) structure returned from CreateProcess?

**Comment by KellyRayburn** [comment]
I just updated and now it doesn't appear in the running processes list, but the program still finds it there. And yes, I tried calling it up from the start menu and even the desktop icon and it didn't seem to fix the problem. No worries though, I just modified my program just to execute the program without checking the processes list for EDMarketConnector and it works fine now.

**Comment by Marginal** [comment]
Glad you have a solution.

**Comment by BobSoft3000** [comment]
I'm still getting this bug in 2.2.2.0 under Windows 7 (x64), but might have narrowed it down a bit further.
If I launch EDMC through a desktop shortcut its ok - when I close it later on, it disappears from task manager process list.
Problem is that I have EDMC pinned to my taskbar, and when I close it after launching from there, it stays in the process list.

**Comment by Marginal** [comment]
There was a race condition that meant that the app sometimes hit an exception during shutdown. Will be fixed in the next release.
