### ISSUE TITLE
Is adding materials and data quantities possible?

### ISSUE THREAD

**Issue by AndrewdAzotus** [Marginal/EDMarketConnector#138]
enhancement request

with a view to auto-magically reporting on which engineering upgrades are available

**Comment by Marginal** [comment]
The intention is to send system, station and body scan results to EDDN, using the info provided in the 'FSDJump', 'Docked' and 'Scan' entries in the Journal.

This work is underway in the [2.2 branch](https://github.com/Marginal/EDMarketConnector/tree/2.2). [Here](https://gist.github.com/Marginal/a1d6fd6d88313034ff5d5ddc5a997f51) are some sample messages taken from the sample Journal that FDev distributed.

**Comment by AndrewdAzotus** [comment]
OK, Thank you.
