### ISSUE TITLE
EDDN upload from command line

### ISSUE THREAD

**Issue by flattermann** [Marginal/EDMarketConnector#139]
At the moment, the command line EDMC.exe does not upload the data to EDDN even if this setting is enabled in the GUI (which is the default IIRC).

I suggest adding the upload function to EDMC.exe as well to enable e.g. TCE users to share their data.

If the user does not want to upload the data to EDDN, he can easily disable this setting in the GUI.

**Comment by Marginal** [comment]
None of the Output options in the GUI app apply to the command-line program; it's the responsibility of the calling app to decide what output it wants.

I'll ask Eventure if he wants to add an option to TCE to upload to EDDN.

**Comment by flattermann** [comment]
For me, EDDN is not a typical output option, but I get your point.

I just think we are losing quite a lot of crowdsourced data if we do not upload from command line.

Since I started using TCE, I haven't used the EDMC GUI anymore. 
Actually, until I checked the EDMC.py yesterday, I thought that the command line version would use the GUI settings regarding EDDN/EDSM upload.
