### ISSUE TITLE
Crash on Start-up on Windows 10 64 Bit

### ISSUE THREAD

**Issue by fcarsten** [Marginal/EDMarketConnector#144]
Crashes on start-up (Windows 10, 64 Bit). Error log:

Traceback (most recent call last):
  File "EDMarketConnector.py", line 29, in <module>
  File "config.pyo", line 333, in <module>
  File "config.pyo", line 209, in __init__
ctypes.ArgumentError: argument 4: <type 'exceptions.TypeError'>: expected LP_c_wchar_p instance instead of pointer to c_wchar_Array_260

**Comment by Marginal** [comment]
From the error this is the 2.2 branch?
Are you running from source?
What build of Python? 32 or 64 bit?

**Comment by fcarsten** [comment]
That's running the 2.20 beta pre-release (https://github.com/Marginal/EDMarketConnector/releases/download/rel-220-0/EDMarketConnector_win_2200.msi)
Not sure what version of Python it uses internally.

**Comment by Marginal** [comment]
Will be fixed in the next 2.2 release.
In the meantime you can work round this by un-installing 2.2, installing 2.17, and re-installing 2.2.
