### ISSUE TITLE
'Server is lagging' on Update request

### ISSUE THREAD

**Issue by gregmcdougall** [Marginal/EDMarketConnector#145]
it's logging star systems to EDSM ok, but any manual triggering of the Update results in an 'Error: Server is lagging' message. EDSM & EDDB look to be up? Running on Mac 10.12 btw

**Comment by Marginal** [comment]
What version of E:D and of EDMC ?

**Comment by gregmcdougall** [comment]
Current non-beta E:D running on Mac 10.12. E:DMC 2.1.7.2

**Comment by Marginal** [comment]
In 2.17 the "Server is lagging" error is only generated on automatic update. Can you double-check that you're running 2.17 on the same machine as E:D 1.6.

**Comment by sittingthunder** [comment]
I updated to the latest version of the connector and this has been happening to me.

When i first open the connector the first manual update is good but any subsequent manual update gets me the "Server is Lagging" message and the system and station details don't update in the window

Elite version V 2016.07.21.114452 0.4.5499.0
Market Connector version 2.1.7.2

**Comment by Marginal** [comment]
Looks like I'm overlooking something.
@sittingthunder Can you confirm that you're running EDMC 2.17 on the same machine as E:D 2.1 ?

**Comment by sittingthunder** [comment]
yes EDMC 2.17 and E:D 2.1

**Comment by Marginal** [comment]
EDMC is supposed to update the displayed "System:" when you jump to a new system. Does it?

@sittingthunder Do you have Steam and non-Steam versions of the game installed? If the "System:" display isn't being updated when you jump please see [Doesn't track Systems visited](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#doesnt-track-systems-visited)

**Comment by sittingthunder** [comment]
it doesn't update when i jump to a new system
I've got the steam and stand alone games installed but only use the stand alone game now and i've followed the instruction to point EDMC to the new log location, still having the same issue.

**Comment by Marginal** [comment]
@sittingthunder OK it sounds like we're making some progress. But please check that the folder that you've specified for “E:D log file location” actually contains recently-dated netLog*.log files.

**Comment by Andargor** [comment]
I had the same issue, until I realized I wasn't docked. Perhaps the message should indicate so if this is the case?

**Comment by Marginal** [comment]
@Andargor How did you trigger the update? Clicked on the "Update" button, pressed Return, pressed the hotkey, or something else ?

**Comment by Andargor** [comment]
@Marginal I clicked the update button. I was out of game, so I didn't notice I wasn't docked.

**Comment by lemmy04** [comment]
Looks like this is back:
when I manually update i get "Server is lagging", and my ship is listed as "testbuggy".

**Comment by Marginal** [comment]
@lemmy04 Next time you see this please attach the output from File->Save Raw Data here.

But it looks like FDev's server is sending you out-of-date information. In which case the only thing to do is wait for it to catch up.

**Comment by lemmy04** [comment]
nah, was my own stupidity. EDMC works fine as long as E:D is actually running...
