### ISSUE TITLE
No data is transmitted on EDDN. Error: could not connect to EDDN.

### ISSUE THREAD

**Issue by linkomizin** [Marginal/EDMarketConnector#150]
I apologize for the translation. This is Google translator.

The first time I tried this program without any problems. (Last version) It was a night 11.10.2016.Pridya day saw this any typing errors in data transmission. Ping said that u can see, but not ping. Trasert is not.
Tried VPN - all start.
I called provider. They said that it is not blocked by anything.

 Website eddn-gateway.elite-markets.net opens only through the VPN. I tried with other PCs on the same subnet to access. His no. all is well with the mobile Internet.

What could be the problem?

Thank you in advance.

![1](https://cloud.githubusercontent.com/assets/1645748/19319732/e9e6058c-90b6-11e6-9903-db65d128302d.PNG)
![2](https://cloud.githubusercontent.com/assets/1645748/19319735/ed255de2-90b6-11e6-8db9-2ccfad31306e.PNG)
![1](https://cloud.githubusercontent.com/assets/1645748/19319747/f4874410-90b6-11e6-85a0-25f815a11e5c.PNG)
![2](https://cloud.githubusercontent.com/assets/1645748/19319748/f6e1f494-90b6-11e6-89d6-49b01e1fca80.PNG)
![ping 1](https://cloud.githubusercontent.com/assets/1645748/19319754/fdd65268-90b6-11e6-88e1-b18cc53d6af3.PNG)
![tracert1](https://cloud.githubusercontent.com/assets/1645748/19319758/013f86ae-90b7-11e6-8175-534808912ec2.PNG)

Use vpn 
![ping vpn](https://cloud.githubusercontent.com/assets/1645748/19319761/03118dc4-90b7-11e6-9ad2-3917f8860d33.PNG)

**Comment by Marginal** [comment]
Hi,

EDMC needs to talk to eddn-gateway.elite-markets.net on port 8080. So please check in your router and/or VPN configuration that port 8080 / tcp is allowed through,

You can check connectivity with `telnet eddn-gateway.elite-markets.net 8080`.

**Comment by linkomizin** [comment]
Thank you! I helped. Port forwarding in the router.
You can add this information to the user manual?

  But the words of another problem. Now it does not work when the auto sync dock. And an error while sending data manually: Server timed out. It helps to restart the connector market.

**Comment by Marginal** [comment]
> Thank you! I helped. Port forwarding in the router. You can add this information to the user manual?

Great. I've [added](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#error-cant-connect-to-eddn) this info to the wiki.

> Now it does not work when the auto sync dock. And an error while sending data manually: Server timed out.

Please see [Doesn't track Systems visited](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#doesnt-track-systems-visited).

**Comment by linkomizin** [comment]
> Please see Doesn't track Systems visited.

By setting all okay.
  I use the Steam version. Without horizons.

Now I notice the following, that not all habitats triggered automatic data transfer.

You can add sound setting for automatic data transfer after docking? This is to ensure that would not have to use manual control. A bit boring sometimes use alt + tab.

**Comment by Marginal** [comment]
> not all habitats triggered automatic data transfer

Are you sure? The transfer can happen very quickly.

You should hear a sound on automatic update or on error unless you have turned off the "Play sound" setting. You can see what messages you and others are sending to EDDN [here](https://ross.eddb.io/eddn/log).

**Comment by linkomizin** [comment]
> sound on automatic update
No, there is only the sound of a manual update.

**Comment by linkomizin** [comment]
With the new version 2.2.1.0 earned automatic update. And sound the same! Thanks for your work.
Ticket are closing.
:)

**Comment by Marginal** [comment]
Glad it's working now.
The new Journal in E:D 2.2 makes everything more reliable.

**Comment by linkomizin** [comment]
Thanks for your work!
