### ISSUE TITLE
EDSM commander name/api key not found

### ISSUE THREAD

**Issue by john211murphy** [Marginal/EDMarketConnector#153]
after installing release 2.2.1 i receive "EDSM commander name/api key not found" on start up.
tried with new api key from EDSM, bet no improvement.

**Comment by schemogroby** [comment]
+1 same problem here

- Win 10, EDMC V. 2.2.4.0
- double checked credentials
- reset EDSM API Key
- reinstalled EDMC

can somebody tell me, were those credentials are stored in my filesystem? after reinstall all info reapeared "magically" so they were not uninstalled at all.
After uninstall i deleted 
`C:\Users\*me*\AppData\Local\EDMarketConnector`
as well

**Comment by Marginal** [comment]
Credentials and other persistent settings are stored in the registry on Windows, under HKEY_CURRENT_USER\Software\Marginal\EDMarketConnector .

If you're sure you've copied your username and API key correctly from EDSM then I suggest contacting the EDSM developers - either by email or on Discord.

**Comment by john211murphy** [comment]
I managed to find a fix to my problem. During an update, a non-printing character was appeneded to the commander name. I cleared the field and re-entered the commander name and all is well

**Comment by schemogroby** [comment]
Thanks for your replys.
I create a new EDSM profile and it works now,
It seems like i had a trailing "space" in my user name @ EDSM and i was not able to input this character into EDMC.

**Comment by AnthorNet** [comment]
It seems something is wrong on our side, I'll update you main account, and merge the second, and fix this trailing bug.
