### ISSUE TITLE
Paintjob not updated on EDSM when back to default

### ISSUE THREAD

**Issue by Mikayex** [Marginal/EDMarketConnector#154]
The paintjob is not updated on EDSM when we get back to default paintjob from a custom one.

Here is the associated journal entry:
```js
{ "timestamp":"2016-11-01T13:00:10Z", "event":"ModuleSell", "Slot":"PaintJob", "SellItem":"$paintjob_hauler_blackfriday_01_name;", "SellItem_Localised":"Black Friday", "SellPrice":0, "Ship":"hauler", "ShipID":9 }
```

**Comment by Marginal** [comment]
This works for me. Do you still have this issue? It's possible that EDSM has fixed it on their end.

**Comment by AnthorNet** [comment]
Change the empty paintJob parameter, might have fix it.

**Comment by Mikayex** [comment]
I can't test from game since I'm on my way to Colonia, but I may try with fake log entries later today...

**Comment by Marginal** [comment]
I'll close this based on my testing and on @AnthorNet's comment. But please re-open if you find it doesn't work for you when you get to Colonia.
