### ISSUE TITLE
Need to start including engineer modifications in ship loadouts

### ISSUE THREAD

**Issue by nemesyssoft** [Marginal/EDMarketConnector#155]
Now that beta.coriolis.edcd.io is starting to support engineer modifications, I believe it's time that EDMarketConnector starts exporting those modifications with the ship loadouts that it creates. That would speed up things tremendously and reduce some errors because, right now, it is very tedious and time consuming to enter all those engineer modifications. Plus, because some values in the in-game outfitting screen are truncated, there are some rounding errors because of the values we enter and the real values in the game. For example, I overcharged one of my power plant. The game reports that it's generating 39.75MW but after entering the mods in beta.coriolis.edcd.io, it reports 39.74MW because one of the modification value was rounded up or simply dropped in the outfitting screen.

**Comment by Marginal** [comment]
EDMC exports engineers' mods if you select E:D Shipyard format, and [E:D Shipyard](http://www.edshipyard.com) imports them.

If the Coriolis guys decide on an import/export format that includes mods then EDMC will support it.
