### ISSUE TITLE
Clash with Coriolis on ship fit outs?

### ISSUE THREAD

**Issue by DRY411S** [Marginal/EDMarketConnector#156]
I've noticed that EDMC and Coriolis are using different JSON schema references.

The EDMC output using schema v2 (Attached) includes a passenger cabin. Coriolis does not recognise the cabin. Coriolis JSON out also attached.

EDMC Output:
[Asp Explorer.2016-11-02T16.05.txt](https://github.com/Marginal/EDMarketConnector/files/569098/Asp.Explorer.2016-11-02T16.05.txt)

Coriolis export, after importing the above
[Asp Explorer.2016-11-02T16.05 out.txt](https://github.com/Marginal/EDMarketConnector/files/569105/Asp.Explorer.2016-11-02T16.05.out.txt)

I*think* this is a Coriolis issue as the website does not allow me to build a fitout that includes passenger cabins. But nevertheless their schema and EDMC schema are mis-aligned.

I've also reported this to Coriolis as potentially their issue. https://github.com/cmmcleod/coriolis/issues/206

**Comment by Marginal** [comment]
Coriolis hasn't been updated for 2.2.

There's a fork at [coriolis.edcd.io](https://coriolis.edcd.io) (with [source](https://github.com/EDCD/coriolis/)) which has support for 2.2, and which can handle this output from EDMC.
