### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by Sle3perX** [Marginal/EDMarketConnector#157]
Hey, i have a problem with EDMC.
I get the above message everytime i try to get station/market data.
I already deinstalled all files. (including appdata/local files)
Set my account and typed the auth code i got per mail from Frontier.
I'm sure my credentials are correct. Cause the same work on the elitedangerous.com website.

After that i still got the message "Invalid Credentials".

Is something broken?
It definitely can see my commander name, my actual system+station.

I hope you can help me :)

**Comment by Marginal** [comment]
This error can happen when your Cmdr name as reported in the game's journal doesn't match your Cmdr name as reported by the API.

If you have more than one account, please check that the username in EDMC's settings matches the account that you're playing with.

Otherwise, please send me the latest Journal.*.log file from the "Saved Games\Frontier Developments\Elite Dangerous" folder plus the output from EDMC when you choose File ->Save Raw Data. Perhaps the easiest way to get these to me is to mail me at jonathan@marginal.org.uk .

**Comment by Red13x3** [comment]
Speaking of two accounts...

Is EDMC ever going to be able to handle multiple commanders with any sort of easy interface or switch?

Thanks,
CMDR Red_xiii

--
Mark
iPhone: 0402 322 901

**Comment by Sle3perX** [comment]
Thanks for the answer Marginal.
What i saw, that in the information screen (where your credits and the various faction rangs are) are wrong values.
Before that i deleted my old save in Elite Dangerous itself, because i wanted to start over again.
How can i reset EDMC so i see my actual credits and the ohter values?

**Comment by Marginal** [comment]
Sounds like the Frontier servers are still returning data from your previous Cmdr.

There's nothing I can do about this - hopefully the servers will catch up at some point. The only thing I can think for you to try is to quit the app and delete its data under %USERPROFILE%\AppData\Local\EDMarketConnector to go through validation again.

**Comment by Sle3perX** [comment]
Yeah i have done this yesterday. Got the old data again.
Ok i will wait a few days and see if i get correct data for my commander.

Thanks for you help :)
I will write here again and close the issue if it works again.

**Comment by ceilingpaint** [comment]
Hi, just installed for first time tonight and I'm having this issue, though my CMDR name is showing up correctly and the market connector is able to pick up my station/system with ease. Save raw data doesn't seem to do anything though...

**Comment by tankrd** [comment]
I just started running the market connector and I get the same error.  Tried wiping everything out and restarting, but no luck.  Name showing correctly, but when I hit update, it says invalid credentials

**Comment by teronpotter** [comment]
I have the same issue here. Created new save with same Commander Name, tried to wipe settings and re-link to Frontier's API. Invalid Credentials. Does this resolve itself with time? Does the original poster have an update on if his is working or not?

**Comment by hatetank** [comment]
Same issue here.  Same name, new save as of three days ago.  

Status window shows incorrect balance, faction, and ranks.  Also shows old ships from the previous save.

Not sure how long that'll take to propagate.  Hopefully not too long, it'd be nice to contribute.

**Comment by Marginal** [comment]
I've written up a more succinct summary of this issue at #165 so closing this as a duplicate.
