### ISSUE TITLE
Can't install EDMarketConnector_win_223.msi on win 10

### ISSUE THREAD

**Issue by ToXinE** [Marginal/EDMarketConnector#159]
hi, 

i can't install the provided EDMarketConnector_win_223.msi in win 10.
The installation is blocked by windows.
![2016-11-17 14_22_57_windwos10](https://cloud.githubusercontent.com/assets/6205053/20391549/2dba5e50-acd4-11e6-9fda-e3c2381d3a02.png)

**Comment by cappa83** [comment]
Click on Information complementaires and then on "Run anyway"

**Comment by Marginal** [comment]
Closing. Please re-open if @cappa83's solution doesn't work for you.
