### ISSUE TITLE
Imperial Cutter export to E:D Shipyard - slot offset by 1

### ISSUE THREAD

**Issue by doubleshadow** [Marginal/EDMarketConnector#161]
When clicking the "ship link" to display current ship loadout in E:D Shipyard, optional internal modules are shifted by 1. This currently means that I am unable to display my loadout as EDMC will generate one more slot and EDS will complain about that.
To make it work, I simply removed my shields, and that revealed the problem.

The json data is correct - slot 8 is empty.

Raw json data:
[Laksak.Stjepan Seljan Hub.2016-11-20T15.47.14.zip](https://github.com/Marginal/EDMarketConnector/files/602096/Laksak.Stjepan.Seljan.Hub.2016-11-20T15.47.14.zip)

Malformed URL generated by EDMC:
http://www.edshipyard.com/#/L=80_C,7u507u507u507u505DeG50goB4mEkCjIqMwAuYotC5DeG3CmhOMxJTYsD77wR00mI10_g20_g20_g20_g20mI10_g00_g0,231Cg1D80B6G50wpT6tT28tigGyI1OjguBa1B6G7AmVCInL7KtbVQnLhSs3bYnLhatbOBa09s1,0DI10AA10AA10AA108c108c107212UI1

Correct URL:
http://www.edshipyard.com/#/L=80_C,7u507u507u507u505DeG50goB4mEkCjIqMwAuYotC5DeG3CmhOMxJTYsD77wR00mI10_g20_g20_g20_g20mI10_g00_g0,231Cg1D80B6G50wpT6tT28tigGyI1OjguBa1B6G7AmVCInL7KtbVQnLhSs3bYnLhatbOBa09s1,mpT0DI10AA10AA10AA108c108c107202UI0

**Comment by Marginal** [comment]
EDMC generates the correct output ([Type6.txt](https://github.com/Marginal/EDMarketConnector/files/602122/Type6.txt)) and URL. Looks like an E:D Shipyard issue.

**Comment by doubleshadow** [comment]
> I assume you mean the first slot is empty?

Yeah, I meant the Slot01_Size8.
I've sent mail to taleden to check this out.

**Comment by Marginal** [comment]
According to the author this is a known issue with E:D Shipyard - empty slots are skipped. Closing.
