### ISSUE TITLE
Crashes on startup on Mac OS Sierra 10.12.1

### ISSUE THREAD

**Issue by codebykevin** [Marginal/EDMarketConnector#162]
Process:               E:D Market Connector [38926]
Path:                  /Volumes/VOLUME/*/EDMarketConnector.app/Contents/MacOS/E:D Market Connector
Identifier:            uk.org.marginal.edmarketconnector
Version:               2.2.3.0 (2.2.3.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           E:D Market Connector [38926]
User ID:               501

Date/Time:             2016-11-22 10:13:11.359 -0500
OS Version:            Mac OS X 10.12.1 (16B2555)
Report Version:        12
Anonymous UUID:        098B7675-35E3-9AFB-1042-5E82B52C9588

Sleep/Wake UUID:       3E0AC05B-DA93-4622-B0E2-AF2AA4915420

Time Awake Since Boot: 230000 seconds
Time Since Wake:       12000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fffbbac7dda __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fffbbbb3787 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fffbba2d420 abort + 129
3   org.python.python             	0x00000001004a18ee Py_FatalError + 49
4   org.python.python             	0x0000000100482127 PyEval_RestoreThread + 27
5   _tkinter.so                   	0x0000000101e2dc13 0x101e28000 + 23571
6   Tcl                           	0x0000000101e450b1 TclInvokeStringCommand + 124
7   Tcl                           	0x0000000101e465b7 0x101e38000 + 58807
8   Tcl                           	0x0000000101e894ce 0x101e38000 + 333006
9   Tcl                           	0x0000000101e8353a Tcl_ExprObj + 824
10  Tcl                           	0x0000000101e48686 Tcl_ExprBooleanObj + 25
11  Tcl                           	0x0000000101e50c73 0x101e38000 + 101491
12  Tcl                           	0x0000000101e465b7 0x101e38000 + 58807
13  Tcl                           	0x0000000101e47717 0x101e38000 + 63255
14  Tcl                           	0x0000000101e46fe0 Tcl_EvalEx + 26
15  Tk                            	0x00000001040bed27 Tk_BindEvent + 4503
16  Tk                            	0x00000001040c3651 TkBindEventProc + 344
17  Tk                            	0x00000001040ca529 Tk_HandleEvent + 895
18  Tk                            	0x00000001040cab3c 0x1040b6000 + 84796
19  Tcl                           	0x0000000101eb434b Tcl_ServiceEvent + 147
20  Tcl                           	0x0000000101eb4700 Tcl_ServiceAll + 177
21  Tcl                           	0x0000000101ee4162 0x101e38000 + 704866
22  com.apple.CoreFoundation      	0x00007fffa68edec7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
23  com.apple.CoreFoundation      	0x00007fffa68ede37 __CFRunLoopDoObservers + 391
24  com.apple.CoreFoundation      	0x00007fffa68cec2e __CFRunLoopRun + 1214
25  com.apple.CoreFoundation      	0x00007fffa68ce514 CFRunLoopRunSpecific + 420
26  com.apple.HIToolbox           	0x00007fffa5e6bfbc RunCurrentEventLoopInMode + 240
27  com.apple.HIToolbox           	0x00007fffa5e6bdf1 ReceiveNextEventCommon + 432
28  com.apple.HIToolbox           	0x00007fffa5e6bc26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
29  com.apple.AppKit              	0x00007fffa4555b79 _DPSNextEvent + 1093
30  com.apple.AppKit              	0x00007fffa4c6b1c3 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1637
31  Tk                            	0x0000000104170285 0x1040b6000 + 762501
32  com.apple.AppKit              	0x00007fffa47ab9c8 -[NSApplication _doModalLoop:peek:] + 497
33  com.apple.AppKit              	0x00007fffa497e746 __35-[NSApplication runModalForWindow:]_block_invoke + 64
34  com.apple.AppKit              	0x00007fffa47a94b2 -[NSApplication runModalForWindow:] + 137
35  com.apple.AppKit              	0x00007fffa4919db5 _NXDoLocalRunAlertPanel + 368
36  com.apple.AppKit              	0x00007fffa4919b36 NSRunAlertPanel + 295
37  uk.org.marginal.edmarketconnector	0x00000001000069e7 0x100000000 + 27111
38  uk.org.marginal.edmarketconnector	0x000000010000278f 0x100000000 + 10127
39  uk.org.marginal.edmarketconnector	0x000000010000117a main + 650
40  uk.org.marginal.edmarketconnector	0x0000000100000be4 start + 52

**Comment by Marginal** [comment]
I can't reproduce this. Is this a fresh install of EDMC, or has it worked previously?
Do you see the app icon in the dock and the app window, or does it crash before these appear?
Do you have more than one monitor? Is the app window on your primary monitor (the one with the Dock)?

**Comment by codebykevin** [comment]
Fresh install. Crashes immediately. Single monitor.

**Comment by Marginal** [comment]
Please try 2.24 and post a crash report again if it crashes.

**Comment by codebykevin** [comment]
That did the trick. Thanks.

**Comment by Marginal** [comment]
Great. It was a guess but glad it worked.
