### ISSUE TITLE
Shop export not working properly 

### ISSUE THREAD

**Issue by lordpoppington** [Marginal/EDMarketConnector#163]
I have found a couple of bugs in the new ship export with coriolis, With my anaconda I am missing a passenger cabin and it has put a 7D fighter hanger in a 5 slot 
https://coriolis.edcd.io/outfit/anaconda?code=0pxtsFklndCsxf5--------0002------4h3c-mlmgmgfhv4032f24.AwRj4yuqg%3D%3D%3D.CwRgDBldOS%2FjPMQ%3D.H4sIAAAAAAAAA2MU82RhYOBX%2Bvv%2FPwcLMwPDfybRa4xAgTkMDAzKakBRkYn%2F%2F%2F%2BXKASKCa0Biv1nFnolAJTv%2BwYUdeFkYBDZIARUKQFUJBwMkpcQncPEwMDdDWQLCgJ1qfgBCaZPP4EK%2FgMAEfKa5G0AAAA%3D

Also the export is failing for my[ Diamond back explorer](https://coriolis.edcd.io/import?data=H4sIALtJNlgC_61YW2_rNgz-L37OCt1t9a1tTi9DNxRNsR3goDDUWGmE41iGbHfNivz3UXZuStIeJ9hTQlkkP5IfKdkf0Vi5Vxudf8CfUo1NPY_OsVgMoonTOjqfqLzSIDQ693tmyhThXkpgr9OVdm86fILOOFnAQ5NF50QMopnNmlxXftOFm9nGtQbbRf8v8Od1MElEjBNKBlGhZvAsGho1s0V2qcY_v9-nnZH0xqlM42gQWUBWuwa0S2es6yIZRE2RW1VoMIgG0ZvKG7CEPK5L-_KSa4Sj8x_Pa4kEEg0kFkg8kEQgxYGUBJLcljDqpKEeqxz3SIiIYy42CfFq6bf3MrdOu_RB1dOJKTLtTkhHa4v0qQkhbBfCg3p_cAYWTvRLe_qlu6HffD_B5bfi1RT6yuYtCX3-rx1YHU3NpB460xH5azRIMExIS2ozMdq1tNatXe3uhtAXCGGEuv1S0mDnj49VFLCYzlRVQRD1vNQt7BXSMxqTWGKeJBS80cUg0JpqldfTA3q_oTMsacwRZhRxjPmOYgnuIMS0tP-0PNn3iyVjSHCZQJQ02VGfVFlqy9rMTKW_wM5wTChoxzGRgvWCQLZDQBgLLqgUSCKZbBuofb-3jndzQLb8I8pkIkmcxIJyShfPq_nzpF59BbB49mNrbErtq9XyiwrJBlGV2_oOeujdT63Fmm93RZ3eghuXeYKkI_Ov5ulVDjD4JwxEKwf3-s1PT76S_-wsXo-G6b0tXh9V8eobp3v41zKCw_RllCZUYE_iaxjJT6r42YurlKMgkpXydhy0TycBF-UGTit5MPdwiOhb5bLSmqJejtR7M9Gjpiytq_s1FJMByC39FiftcJLP830oZYnAzEP8A46urvGrXmhQLHu2Nzj4or07rY6w4wZOyXTW5LUpc_NZ-yEkMCZAeyH32u_Ltoe5HEuZECEI2dFbogD1-rAyAV9cQtw8lggf1t7EcNgGYlIizoWnKEnI8YMHIk8E4glDBInjex7mBUYkoZglJJE9MhBoc1CM4ZRhAD7G-xMjPjQxRBxODB5OjI5wLXvZL9kbTAu6My2Wlp4aT-9-w4JDNmVLfZ2ZZrbbnjury5vPA7RJ_bt96XUgxwlbh7tSTMNb2mUOv9fOZGqeolOuaQ85LNfKzS_K0lk1no4aU-te8KCeQTU6U6GdHoAY4ZsBDBX2oDyHh6aqnXlpauv6zTfJQjg7RnrS5FCmCMM4WQPzcfYbuYjG-5BKr96CIV-fcJ-UDUP7y_aMelSZ6pcbQsLZP9JFZV31P8z9EXQnwl1u-1ywoaXl3lk5GltbbteHH1sfSuHAWOMhffH4s5vhAM-Vf2F7hK7axnNkZxGJY7lGQ7s09yuU2CnU1Og8u9GFdmrF4dMKhrnsWNNiYn0xwTsi4TTANHTWX--L2tm8u-o4VVQT3aHDJ1UQbqKb8vGuO_rQiXIRlm9U6zxX7tJmc-j9sX3Tbj4aqwISmF5kb6oYtwP-qH7DlPAW3ZMp5ttz_pcFZZLjTfJuS6DXVE0m96opxlNA5A0e2Xcc7UNZHi7BGj2wtnzF_lur0habF7TF4U8A0drpRzRt8tynIgESxVsfGxLGpfDfELbvsBzeihb_AfBwP4b7EAAA)

**Comment by Marginal** [comment]
Please report the Anaconda issue over on the Coriolis project [issue tracker](https://github.com/EDCD/coriolis/issues).

Given the nature of the problem I would suggest choosing "Ship loadout" in EDMC's settings, Update, and attach the Anaconda*.txt file to the bug report.
