### ISSUE TITLE
Error: Invalid Credentials

### ISSUE THREAD

**Issue by Marginal** [Marginal/EDMarketConnector#165]
This error is raised when the Companion API server is supplying data for a different Cmdr than the one that you're currently playing. Either:

1. You have multiple accounts and the username/password setting is not for the account that you're currently playing; or
2. You have reset your Cmdr but Frontier's server is still supplying data for the old Cmdr.

If 1 check your username/password settings.
If 2 this problem may or may not resolve itself in time.

**Comment by AcornBBCnut** [comment]
With regard to invalid credentials, I have fount that while the program accepts my credentials on startup, if I click the update button or change any of the settings, my credentials become invalid. The only way I've found to fix this is to restart the program.

**Comment by Pogster71** [comment]
Downloaded latest version (2.31) today.  Gets my details right on first run, but 'update' fails with Invalid Credentials error.  Going back into settings shows details blanked out.  They are still in the registry.
Only way to get to work is to uninstall, manually delete the registry (uninstall does not remove) and reinstall - for one system.  
Windows 10 64 bit system if that helps.
btw, installer could do with an option to install to an alternative location please.

**Comment by adrensnyder** [comment]
Please help... Suddendly i cannon use it anymore. Credentials Frontier and EDSM are in registry but in gray and blank on program. I try to uninstall/reinstall and delete registry and folder in %localappdata% but nothing.. using 2.3.2

**Comment by Marginal** [comment]
@adrensnyder https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#credentials-settings-are-greyed-out

**Comment by adrensnyder** [comment]
@Marginal Thanks for answer. I checked this things you kinked before ask here... I reboot PC and restart game and program and now work. Don't know why

**Comment by Risnack** [comment]
At 23-06-2017 ED Market Connector suddenly started giving the error: Invalid Credentials.
It was installed at the end of May, ran properly for about 4 weeks, updating and sending info to EDDN and EDSM as it should. Then it just stopped working.

There were no updates for the app nor for ED itself during that time i'm aware off.
I run Win7 64bit, also no updates were done during that time.

Criteria:
-Identity -> Credentials are greyed out eventhough nothing else is running
-EDSM -> EDSM credentials is also greyed out
-Configuration - > ED journal file location is checked, and is set to the correct path aka where the game's journals reside, "default" button is greyed out though.
- I don't have multiple accaunts
- There were no additional purchases during the time, already had Horizons in April, and didn't purchase any cosmetics, from Frontier, at the time ED Market Connector got the error.

Steps taken to fix it:
- browse forums for solutions (obvious)
- pc restarts
- uninstal -> restarted pc -> then tried to reinstal but installer  kept being unresponsive -> Registry cleaned -> restarted pc -> Instal functioned -> ED Market Connector in exact same state as before and NO new prompt to (re-)set my CMDR credentials.

**Comment by Marginal** [comment]
Point 2 above appears fixed in E:D 2.4 - cAPI server reacts to changes in E:D password more quickly now.
