### ISSUE TITLE
SUGGESTION - Installing and Updates

### ISSUE THREAD

**Issue by Pastiekiller** [Marginal/EDMarketConnector#169]
I recently decided to play elite again and updated EDMarketConnector. 
The latest update notes appeared and I thought to myself, I'll read those while the program is updating - I clicked on install and they dissappeared. Ok fine, There must be a read me or info option in the apps menu - there wasn't.

Not an issue as you can come here and see (which I did) but for an app it would be nice if you could do the above.
So my suggestions are:
Firstly Leave the update notes visible while installing/updating along with any previous revisions (as you first get when you see there is an update) and leave them there until the user clicks on close. (even after the program has updated) Maybe a timed close option?
Secondly add a menu with some info on the app, like previous revisions, locations of downloads/website, maybe even a "share with a friend" option so that it can create a post on facebook, linking to the application with info on what it is and does.

I work with programming excel for the company I work in and I know from first hand that you have to make apps "Idiot Proof", Basic instructions, simple help files, links to things that you know are there but they haven't a clue on finding themselves.

These options may well be there somewhere, but treat us all like idiots and your life will be much simpler :) (Just don't tell the users how you are treating them)

Hope this helps

**Comment by Marginal** [comment]
Added Help menu in 2.25.

**Comment by Pastiekiller** [comment]
Nice work - many thanks
