### ISSUE TITLE
[Errno 13] Permission denied: 'outfitting.cvs' after upgrade

### ISSUE THREAD

**Issue by msteele9999** [Marginal/EDMarketConnector#17]
Just upgraded and getting the above error message when attempting to update.

subsequent updates generate: 128662535: mount "None"!="None"

**Comment by Marginal** [comment]
I completely messed up the release process for 1.61. Fixed in 1.61.1.
Please choose "Check for Update" from the menu.

**Comment by msteele9999** [comment]
Will test shortly

---
This email was sent from my mobile device. Please forgive any misspellings
or punctuation errors.

**Comment by msteele9999** [comment]
success!
