### ISSUE TITLE
Contributing minor-faction, states/stations/influence?

### ISSUE THREAD

**Issue by thesuperzapper** [Marginal/EDMarketConnector#170]
I am not sure if this is already possible, but can we automatically submit updates to the minor-faction, states/stations/influence data? 

E.g. [this section](https://eddb.io/system/factions/17072) on EDDB.io
![minor-factions](https://cloud.githubusercontent.com/assets/5735406/21764231/e0f904c8-d6c6-11e6-82ee-5d80ce6a1e67.PNG)

**Comment by Marginal** [comment]
EDMC sends the controlling system faction on arrival in a system, and controlling station faction and state (e.g. "Expansion") on docking.
Unfortunately, the additional data that you would like is not available from the API or Journal.
