### ISSUE TITLE
Using EDMC Reduced Rares profits?

### ISSUE THREAD

**Issue by Red13x3** [Marginal/EDMarketConnector#171]
Is anyone aware of this one?

Apparently if you have EDMC running when you pull into a station to sell a Rare, the value you will get for it is way less than if you are NOT running EDMC.

Have not confirmed this myself - Just seen it posted on a FB group.

**Comment by Marginal** [comment]
See https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#rares-profits-wiped-out

Duplicate of #92.

**Comment by Red13x3** [comment]
Has this been investigated before closing it?

--
Mark
iPhone: 0402 322 901

**Comment by Marginal** [comment]
Yes.

**Comment by Red13x3** [comment]
And what was the findings? Does it affect Rares profits or not? Because if it doesn't, then I want to slap the person that's spreading false rumors. 

--
Mark
iPhone: 0402 322 901

**Comment by 7h3ju57** [comment]
This has already been answered above. And it's in the wiki.
