### ISSUE TITLE
Coriolis link missing optional internals

### ISSUE THREAD

**Issue by jtmcdole** [Marginal/EDMarketConnector#173]
Selecting Coriolis as default shipyard doesn't load the entire ship:

[coriolis link](
https://coriolis.edcd.io/import?data=H4sIAHn1e1gC_82XS2_bMAyA_4vPwaCnH7m1SR8bOqBoAuwwDIbiKI1RxTJkuVtX9L9PkhPXyrrWNnbIKaFskp9IiqKfg4ypexlMn82fkmW5fgqmKCQvk2CjOA-mGyYqboSaC_vSjuWF_zJG5l3FK64euf8EfKLoxTzM18GUTIKdXNeCV_adM7WTtXL23KL957mzKhDFgCQoiSdBwXbmWbB8KnmUNsrplWJrDoNJIA2QVrXRKlUulXMNJ0FdCMkKbgyBSfDIRG0sAItzLlcrwQEMpt9_tBLyJOxJxJOoJ4WeFHlS7ElJV4KgkeY8YwJ-HIgwjCIStoFwaunSRiCdcya4GhEHZwT1843jI98zuVsxbX9Krnmhx_rH_fxTfOT_4lcppOIqXWSyHuP9orjPCz6TwhWizcWlMg4W23yj5ypvavmD6gwJRKgF-1zo9NpUqFpb9XSR_-Y0nQlWVfQffOBtPgoBTii2lJfm2C1Z8dALBlPgwRyUuyi4T6gSE3DS4jjJwtzkG76oy1Iq3S841kiHp6PvkEiDhIZFB8U4crH5alpRk8WqFw6IIw-n0f0_ebo1LPqLXPWo5giSTtEcFNOmty1ZpnNb39-2ueYjyvpWmGXN1NNZWSrJsu2itoZ6YCEM_fg0pnw7PYAo6EQINFDyJ1fzvNIqX9Vaqn7Vk_hH69iISxwelThIY4xhS2Y32q-iAYn-Ziqtereg6bC8wRACELtA3bE16xcdhBKPZMGLSqqqG5SB5woCiF0tL4TUADpLYb--Q7DHMrMTxR3LmsYTNjQDb2ocIprAFgedFg5uusap4JBBOOgdHDoAB0JIw_C1fpzYMtHmRJwUUziACUVHB2ybc7G-4gVX7NB96LiDFicA0xYqcqZQr2GYEh9qLrOHvLi3U1it7TCkWWE6yHoYENm3aYcT98axeQPv5A2PKm0IaNi0oR0T4tpsppTmitxP6_4iemsRv7W4H-GXefHUNfnx6BlT_Dp2X5eHOjiXsnIBN_sEo-4gFJuu78LuQaFThMKnCEX6nRiIPajZlm02N6wusq2BsgaHwcT7s_KNs1IWr58PL_5HatAqPAfbWgh7y0ex2UbS-Q6GhEQJjT1PGEEcm471B_BU_V-YDwAA)

[ED shipyard link](http://www.edshipyard.com/#/L=90XC,,DBw0DBw0DBw0CEg0,9p31A721AOE0Ads0AsO0B3_0BK40Bcg1,0AA10AA10AA108c108c17TC00nE005U1)

Expected: Same ship specs loaded.
Seen: Only two of the optional internals are loaded.

**Comment by jtmcdole** [comment]
Hacking a little bit:
coriolis data= is base64 encoded, gzip compressed, json data.
json data has the modules wrong. Changing "Slot03_Size5" to "Slot03_Size6" and gzip-base64 encoding lets more of the ship load.

So mismatch in ship template?

**Comment by jtmcdole** [comment]
Annnd looking at the coriolis data project, they updated it recently. Maybe the fix is just pulling the latest version? :)

**Comment by Marginal** [comment]
EDMC is sending the correct info.
Please raise this issue against Coriolis.

**Comment by jtmcdole** [comment]
The data= is wrong, so I assume that means EDCD/coriolis-data is wrong?

**Comment by Marginal** [comment]
I was too hasty - EDMC *is* forwarding inconsistent info from the Frontier API e.g:
```json
    "Slot03_Size5": {
      "module": {
        "free": false,
        "id": 128064343,
        "name": "Int_CargoRack_Size6_Class1",
        "on": true,
        "priority": 1,
        "unloaned": 0,
        "value": 362591
      }
    },
```
The Slot names returned from the API haven't been updated to reflect the buff to Type 7 in 2.2.

Nevertheless, this is still [Coriolis](https://github.com/EDCD/coriolis)' problem to deal with. (Not coriolis-data, which looks correct to me).
