### ISSUE TITLE
Generates wrong entry for commodity "Micro-weave cooling hoses"

### ISSUE THREAD

**Issue by DeepstarOne** [Marginal/EDMarketConnector#174]
Hi,
The latest version seem to generated a wrong entry for the commodity "Micro-weave cooling hoses" in the *.csv and *prices files: "Cooling Hoses" instead of "Micro-Weave Cooling Hoses"

Example:
- - - - - - - - - 
...
Ngadakhis;Detmer Hub;Ceramic Composites;933;;2242606;High;;;2017-01-18T21:18:58Z;
Ngadakhis;Detmer Hub;**Cooling Hoses**;1584;;212781;High;;;2017-01-18T21:18:58Z;
Ngadakhis;Detmer Hub;Insulating Membrane;11569;;39998;High;;;2017-01-18T21:18:58Z;
...
- - - - - - - - -

**Comment by Marginal** [comment]
Thanks. Looks like FDev changed the name of this item in their API return.
