### ISSUE TITLE
Error: 14-day Cooldown 

### ISSUE THREAD

**Issue by Big-Gaz** [Marginal/EDMarketConnector#175]
Cooldown is currently showing approx. 1,233,700s - counting down to approx. 8 Feb 2017 18:30! Closing and restarting hasn't reset it - neither has uninstalling and reinstalling.

![edmc](https://cloud.githubusercontent.com/assets/24977745/22289705/f29cbe4c-e2f4-11e6-9234-eac2d4162ba4.png)

**Comment by Marginal** [comment]
Have you been messing with your system clock?

You will need to run RegEdit and delete the registry key HKEY_CURRENT_USER\Software\Marginal\EDMarketConnector\querytime

**Comment by Big-Gaz** [comment]
I haven't knowingly done anything that would change the System Clock, which is why I thought it might be a bug.

Anyway, that's worked nicely - thank you very much!
