### ISSUE TITLE
Can't find "Transparent" translation key in OneSkyApp

### ISSUE THREAD

**Issue by CatfoodCZ** [Marginal/EDMarketConnector#178]
I want to fix the Czech translation of the new "Transparent" theme option, but I can't find it in the OneSkyApp. So I created this pull request #177

**Comment by Marginal** [comment]
Added in [OneSkyApp(http://marginal.oneskyapp.com/collaboration/translate/project/project/52710/language-from/1/language/13/#/?keyword=Transparent).

Will be fixed in the next release.
