### ISSUE TITLE
Can't login after 2.26

### ISSUE THREAD

**Issue by XtaZiiy** [Marginal/EDMarketConnector#179]
Hi Marginal, I've got a problem with the 2.26. 

After update EDMC to 2.26 my CMDR account not working anymore. I can't wrote it again because in settings options ID windows was disable. I already try to uninstall EDMC and install it again 3 times, and still not working. I try to launch it before ED, after ED etc.. Still not working. 

I have only one ED account and never reset it, so i dont understand why i have this issue. In game when docking at station, system analysing, etc... ID option still disable. That's why i submit here my issue because i can't use EDMC anymore riht now. 

Sorry for my bad english, hope you can understand me ;)

Here a screen of my problem, still like that all the time :
![edmc](https://cloud.githubusercontent.com/assets/25582737/22643729/0bc8be1a-ec60-11e6-9f72-85913a965406.png)

**Comment by Marginal** [comment]
Check that the "E:D journal file location" setting on the "Configuration" tab is pointing at your game's journal files (or press the "Default" button to reset this setting).

**Comment by XtaZiiy** [comment]
I already check it, still at the same location before updating EDMC. In steam/common/ED/logs as you can see here : 
![edmc2](https://cloud.githubusercontent.com/assets/25582737/22651241/a5f3d2a0-ec82-11e6-83db-d5048c665dff.png)

**Comment by Marginal** [comment]
It should be C:\Users\\_you_\\Saved Games\Frontier Developments\EliteDangerous (assuming you're running EDMC on the same machine as E:D).

**Comment by XtaZiiy** [comment]
I don't have anything like Saved Games (only on default users but is empty) or parties enregistrées. All of my ED files are in steam, i have ED on steam, and on my AppData. The only one .logs on my PC actually for ED is on Steam/Steamapps/common/ED/Logs called Client.log.
All saves trought steam are in Steam/UserDate/(760 for ED)/remote , but no ".log" here, only steamcache and screenshots. 

But my logs location worked very well before the 2.26 update, so i don't think this is my problem actually. I found it here on Frontier Support (at steam installation): https://support.frontier.co.uk/kb/faq.php?id=108

**Comment by Marginal** [comment]
Since E:D 2.2 / EDMC 2.20, EDMC doesn't use the netLog files described at https://support.frontier.co.uk/kb/faq.php?id=108 . Instead, it requires the game's "[Journal](https://forums.frontier.co.uk/showthread.php/275151-Commanders-log-manual-and-data-sample)" files which normally live in your "Saved Games" folder and are named like "Journal.170206155841.01.log".

Since you don't have a "Saved Games" folder then you should search your C drive for files named Journal.*.log to find out where E:D is putting them.

**Comment by XtaZiiy** [comment]
In regedit its C:\Users\XtaZiiy\Saved Games 
But hes not crated at the moment in this folder, i think ED with steam don't use this location to be honest.
I don't have any jounal.xxx.log in my C: drive and i doesn't found any journal.xxx.log in my hdd (E) aswell where ED is installed.. 

I don't understand why in EDMC 2.25 my current location worked very well and now, just after dl and install the 2.26 it doesn't work anymore ? Maybe because EDMC is on my SSD and ED on my HDD ? But all worked fine before update 2.26 so...

**Comment by Marginal** [comment]
Glad it works now.
