### ISSUE TITLE
Error: Server overloaded

### ISSUE THREAD

**Issue by Infinito1977** [Marginal/EDMarketConnector#180]
Since 5 days or so I always get a message that the server is overloaded when I try to update EDMC. It started in the system Ngere but I also get that message in other systems.

2.2.0 to 2.2.2 are still working, 2.2.3 to 2.2.5 do not work. 2.2.4 works when ed is not installed on the same machine.

**Comment by Marginal** [comment]
sounds like you don't have the EDMC's [journal location](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#doesnt-auto-update-or-track-systems-visited) setting set correctly.
