### ISSUE TITLE
Suggestion: Add ETN in options

### ISSUE THREAD

**Issue by Grawul** [Marginal/EDMarketConnector#181]
Hi,
I would like to have an option, that you get to etn.io if you click your station or system.
Maybe like the option for the shipyard, where you can choose in the settings where to go.

This isn't critical, but maybe you can add this

**Comment by Marginal** [comment]
Unfortunately ETN doesn't offer an API for selecting your current station or system (or for automatically setting your ship details) so this isn't currently possible.
