### ISSUE TITLE
Differences between In-game and ED Market Connector draw

### ISSUE THREAD

**Issue by Deathwatch101** [Marginal/EDMarketConnector#182]
I appear to gain significant hull and resistance value differences on my ship after pulling the data to Coriolis, The data itself cannot be drawn to EDShipyard as it generates a number of errors, regarding the hull reinforcements and hull itself.

https://eddp.co/u/i25sChHj  - hand values as per game
https://eddp.co/u/LPGC8LWb - values as ed market connector

While i can see the game rounding up, I am surprised that one resistance pulled from the connector showed at the minimum over 2% above the result. It seemed most of the time the mass was correct but other values seemed off.

**Comment by Marginal** [comment]
EDMC is just forwarding the data returned from Frontier's API.
Suggest that you report this against [Coriolis](https://github.com/EDCD/coriolis) which is interpreting and displaying the data.

**Comment by kaivalagi** [comment]
Doing some digging myself and yes, I can see the engineer modifier values from the API json and what ends up in Coriolis are the same, which rules out EDMC or Coriolis. Also if Coriolis has data entered manually to match with in-game engineers mods from outfitting everything looks good This leaves only one thing wrong, the API data coming from FD is not in-line with the game....the variations are far from simple rounding issues too.....good luck getting a fix from FD on this.
