### ISSUE TITLE
How to include plugin dependencies?

### ISSUE THREAD

**Issue by kmpm** [Marginal/EDMarketConnector#183]
Hi,
I made a plugin for EDMarketConnector that cannot work without the paho mqtt client.
How would I distribute that? 
Running from source where the paho-mqtt is installed using pip works great.

**Comment by kmpm** [comment]
Not only distribute perhaps as well as running it with the installed application on at least Windows.
For the moment i have included the "paho" folder containing the mqtt client into the plugin folder and added the following section of code in the top of my load.py
```python
import sys
import os
try:
    import paho.mqtt.client as mqtt
except:
    print 'failed to load'
    #add current folder to path
    #dependencies should be included within
    sys.path.append(os.path.join(os.path.dirname(__file__)))
    #import again
    import paho.mqtt.client as mqtt
```

Is this the prefered method or what should I do?

**Comment by Marginal** [comment]
Yes. Any external dependencies need to be bundled with the plugin in the plugin's folder.
