### ISSUE TITLE
Taskbar not able to auto hide

### ISSUE THREAD

**Issue by Thoneon** [Marginal/EDMarketConnector#185]
hi there the task bar keeps thinking i'm focused on you program when i'm in borderless mode in ed

**Comment by inorton** [comment]
Hi, is this windows 10? I occasionally get this with other apps like vnc and nx.  If you find Explorer in task manager and choose "Restart" from the context menu does the problem go away?

**Comment by Thoneon** [comment]
Yes it is win 10, no restarting does not fix the issue

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by BarryCarlyon** [comment]
I get this now and again, usually fixed by just left clicking each open app till the taskbar hides.

Taskbar collapse is blocked by one of your open programs, it's just not flashing for some reason.

**Comment by Thoneon** [comment]
O wow I completely forgot about this

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
