### ISSUE TITLE
Error: Is another copy of this app already running ?

### ISSUE THREAD

**Issue by espresso0** [Marginal/EDMarketConnector#186]
Hello,
Sorry with my english... 

I pick the same code 2 time when i start this app for first time (my bad i know). 
But now they kip tell me this "Error: Is another copy of this app already running" or "wrong ID" 

I don't know what to do , i try evry thing (rebot, delet and installe back the app ...)

**Comment by Marginal** [comment]
This "Is another copy of this app already running?" error occurs when the app cannot open the file %LOCALAPPDATA%\EDMarketConnector\replay.jsonl (usually C:\Users\\_you_\AppData\Local\EDMarketConnector\replay.jsonl).

Does the folder %LOCALAPPDATA%\EDMarketConnector exist and can you write to it?
