### ISSUE TITLE
Ship loadouts missing engineering info.

### ISSUE THREAD

**Issue by Atros81** [Marginal/EDMarketConnector#191]
When exporting engineering info to either file or directly to either shipyard site, the engineering info for each ship is no longer exported.  Attached are exports of the same ship, before and after 2.3 update that shows stock modules throughout afterward.

[Imperial Courier.2017-04-12T15.45.25.txt](https://github.com/Marginal/EDMarketConnector/files/917994/Imperial.Courier.2017-04-12T15.45.25.txt)

[Imperial Courier.2017-03-26T16.54.57.txt](https://github.com/Marginal/EDMarketConnector/files/917992/Imperial.Courier.2017-03-26T16.54.57.txt)

**Comment by Marginal** [comment]
Yep. FDev no longer make the engineers' modifications info available. Bug report [here](https://forums.frontier.co.uk/showthread.php/342408-Companion-API-stopped-having-Engineering-Data).

**Comment by rdslw** [comment]
@Marginal Starting two weeks ago, Companion API contains all/most engineering info. Can we have fixed links from edmc to coriolis/edshipyard with engineering info?

**Comment by Marginal** [comment]
> Starting two weeks ago, Companion API contains all/most engineering info

In 2.4 beta, yes. In 2.3 live, no.
EDMC will send mod info to EDShipyard and Coriolis when 2.4 Companion API is live - ref 6ffcfc7. At time of writing EDShipyard will handle it, but Coriolis not.

**Comment by rdslw** [comment]
> In 2.4 beta, yes. In 2.3 live, no.
I thought that companion API was a separate api from main game. You mean, that the same api point returnes different data depending on the fact I'm logged to live or beta (at the time of companion api request being made by edmc) ?
And also does it mean, that now, as beta is disabled, companion api returns only old information?

**Comment by Marginal** [comment]
Different cAPI servers for live and Beta. EDMC contacts the appropriate one depending on whether your playing live or Beta.

**Comment by Marginal** [comment]
Fixed in E:D 2.4
