### ISSUE TITLE
Name display Feature request

### ISSUE THREAD

**Issue by avaxorg** [Marginal/EDMarketConnector#195]
https://images.discordapp.net/.eJwFwcENwyAMAMBdGABjDAGyQKW-ugIiiERK6gi7r6q79-5rPvM0q9lVb1kBtkMaz82K8qyj28E8zl7vQ2zjC6pqbfvV3yrgCy7k0BHGFClnTEAukF8KhUQxZ4fFQ6DgKdrn62F-f9NXIJg.ndF4pzRTisP_iJfdfHTntb2J3_w

**Comment by avaxorg** [comment]
is this from group name?
Why not add "Group" word?

**Comment by Marginal** [comment]
> Why not add "Group" word?

Don't want to take up any more screen space.
