### ISSUE TITLE
error: the server slows down

### ISSUE THREAD

**Issue by FJlashe** [Marginal/EDMarketConnector#196]
version 2.2.4 is working but have to manually press send data
firewall and antivirus is off

screenshots
https://yadi.sk/d/XX_2_9ZH3H9jZ3

**Comment by Marginal** [comment]
Please try with the latest version - 2.31

**Comment by FJlashe** [comment]
the same problem

**Comment by Marginal** [comment]
See [here](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#doesnt-auto-update-or-track-systems-visited)

**Comment by FJlashe** [comment]
watched all the way right, and still writes an error the server slows down if you could help what is written there, I wrote here

**Comment by Marginal** [comment]
This error normally occurs when there's a mismatch between the data returned from the Companion API that this app uses, and the Journal file. The app assumes that this mismatch is caused by the Companion API server lagging behind the game (because that does sometimes happen).

But if you've checked your “E:D journal file location” setting and still regularly receive this error then there may be another cause. In the app please choose File -> Save Raw Data, save the file with a .txt extension, and attach it in reply here.

**Comment by FJlashe** [comment]
[Achelous.Copernicus Dock.2017-04-21T05.26.12.txt](https://github.com/Marginal/EDMarketConnector/files/945894/Achelous.Copernicus.Dock.2017-04-21T05.26.12.txt)

**Comment by Marginal** [comment]
Looks OK. Please also post the Journal file at the time that you saved this (or the last Journal file if you didn't have E:D running at the time).

**Comment by FJlashe** [comment]
[Achelous.Copernicus Dock.2017-04-21T10.12.59.txt](https://github.com/Marginal/EDMarketConnector/files/946235/Achelous.Copernicus.Dock.2017-04-21T10.12.59.txt)

**Comment by FJlashe** [comment]
![2017-04-21_10-14-57](https://cloud.githubusercontent.com/assets/27788149/25266852/63121964-267b-11e7-880d-cc0102aab1f9.png)

**Comment by FJlashe** [comment]
![2017-04-21_10-15-34](https://cloud.githubusercontent.com/assets/27788149/25266878/78ecbea6-267b-11e7-983d-2c86cd5245bb.png)

**Comment by FJlashe** [comment]
Can clean all the program data? I cleaned it in appdata / local and reinstalled it, but it still shows the login, password, ways of playing and saving files where I pointed. Where can it still store data, to clean the system from it completely and install a clean one?

**Comment by Marginal** [comment]
Please also post the [Journal](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#doesnt-auto-update-or-track-systems-visited) file at the time that you saved this (or the last Journal file if you didn't have E:D running at the time).

Settings are stored in the registry under `HKEY_CURRENT_USER\Software\Marginal\EDMarketConnector\` .
