### ISSUE TITLE
ship cargo items missing in latest data

### ISSUE THREAD

**Issue by RaphaelFaria123** [Marginal/EDMarketConnector#197]
Hi there, 

Do you know if the ship cargo item data will no longer be available in the data returned by the EDServers? I exported the entire server data response as json to a file and the cargo items aren't there anymore?

**Comment by Marginal** [comment]
Yep. Feel free to pile in on the bug report [here](https://forums.frontier.co.uk/showthread.php/342408-Companion-API-stopped-having-Engineering-Data).

**Comment by RaphaelFaria123** [comment]
Cool thanks. Hopefully they add the data back again.

**Comment by RaphaelFaria123** [comment]
Hi, 

Do you have any plans of raising journal events to EDMarketConnector plugins in the future?

Since cargo data is no longer in the API, I have started implementing a journal file watcher. For some or other reason though, the file watcher doesn't raise events while Elite Dangerous is active.

I was about to implement a time based file polling mechanism but noticed that you are already watching journal files.  

Please let me know if you think adding a broadcasting journal file events from EDMarketConnector makes sense to you. 

Regards
Raphael

**Comment by Marginal** [comment]
Journal events are made available to EDMC plugins through the [plugin API](https://github.com/Marginal/EDMarketConnector/blob/master/PLUGINS.md). EDMC tracks the player's cargo and passes it in as `state['Cargo']` to [journal_entry()](https://github.com/Marginal/EDMarketConnector/blob/master/PLUGINS.md#journal-entry).

**Comment by RaphaelFaria123** [comment]
That is great news! Thank you very much for the quick response.

**Comment by Marginal** [comment]
Fixed in E:D 2.4
