### ISSUE TITLE
Coriolis ship format export

### ISSUE THREAD

**Issue by aoighost** [Marginal/EDMarketConnector#20]
It would be useful to be able to export coriolis format for ship loadouts.

**Comment by Marginal** [comment]
Should be do-able.

**Comment by Marginal** [comment]
Please let me know how you get on with [this version](https://github.com/Marginal/EDMarketConnector/releases/tag/rel-171).

Note that Coriolis will silently ignore any modules that it doesn't recognise, so look out for missing modules after import.

**Comment by Marginal** [comment]
Fixed in Release 1.72
