### ISSUE TITLE
Journaling broken by training session

### ISSUE THREAD

**Issue by Snodlander** [Marginal/EDMarketConnector#208]
I went on a mammoth exploring session over the 28-29 April, when all the sites were down in protest, so didn't bother to sync to EDSM - though the journal log is in the expected folder.
A day or so later I logged in and started up a training session briefly to show someone the game - a further journal log was created.
A day later I fired up the ED Market Connector to sync my exploring mission to EDSM only to find that the Market Connector didn't recognise me.
Eventually launched the game again and saw the connector populate all of my credentials again - another journal log created.
Went to sync the connector to EDSM, expecting to see all that I had explored but got only a 141 lyr jump from an old system to my current system.

I've since tried, unsuccessfully, to get that data uploaded via a few different methods but have reached the limit of my troubleshooting skills.
I'd welcome any ideas as to how I can now get that data visible in EDSM?

**Comment by Snodlander** [comment]
OK, that was quick. I've found the page on EDSM where I was able to upload the log file manually.
Problem kinda solved, well, symptom at least.

**Comment by Marginal** [comment]
EDMC doesn't "sync" with EDSM as such. It sends your details to EDSM while you have that option selected, and doesn't if have that option not selected.

Glad you found the place to upload your Journal. For anyone else reading that place is https://www.edsm.net/en/settings/logs/import .

**Comment by Snodlander** [comment]
Just to confirm, I've always had that option to send selected. If you start a training session however EDMC picks up the corresponding log file and... Well, there be dragons.

**Comment by Marginal** [comment]
I misunderstood. Will investigate.

**Comment by Marginal** [comment]
Your exploring session over the 28-29 April wasn't sent to EDSM because you didn't have the "Send to EDSM" option selected (FYI the EDSM API deliberately remained up while the website was down).

EDMC doesn't recognise you when you are in a training session (or you're not in the game and your last game was a training session).

**Comment by Snodlander** [comment]
I did not run EDMC during my exploring session on 28-29 April.
Having performed a training session afterwards, the only way to send that exploring session to EDSM is to manually upload it.
Is this expected functionality of EDMC?

**Comment by Marginal** [comment]
> Is this expected functionality of EDMC?

Yes - it sends your flight log to EDSM if you have that option selected. It doesn't if you don't.

**Comment by Snodlander** [comment]
" it sends your flight log to EDSM if you have that option selected. It doesn't if you don't."

Can we move away from this as it is not relevant to this situation.

These are the steps to reproduce the issue:
*Open ED and EDMC, ensure EDMC is configured to send your commander's data to EDSM by default.
* Fly from point A to point But
* Log out of ED
* Send data to EDSM by pressing the 'Update' button on EDMC interface
* Check EDSM and confirm location at B, having travelled from A
* Shut down EDMC
* Log into ED
* Fly from point B to point C to point D to point E
* Log out of ED
* Log into ED and perform a training session
* Log out of ED
* Log into ED and load EDMC
* Press 'update' button on EDMC to update EDSM
Result:
EDSM shows travel history as A:B:E and does not know about C or D

Please confirm expected behaviour.

**Comment by Marginal** [comment]
You weren't running EDMC while you were in points C and D, therefore it was not able to send any info to EDSM about these systems.

**Comment by Snodlander** [comment]
Oh OK,
I was under the impression that EDMC would pick up all of the log files created since last update. 
If it only picks up the log file created whilst EDMC is running, that's cool, I know what to expect now. 
Thanks for clarifying.
