### ISSUE TITLE
OpenSSL issue on Mac

### ISSUE THREAD

**Issue by gregmcdougall** [Marginal/EDMarketConnector#209]
Please disable the secure sockets interactions in EDSM.py until the SSL issues being encountered between EDMC and EDSM are resolved.

**Comment by gregmcdougall** [comment]
Perhaps a toggle to enable/disable SSL (if that's possible)?

**Comment by inorton** [comment]
I think EDSM no longer offers plain HTTP.

**Comment by inorton** [comment]
@gregmcdougall can you give as an example log/screenshot of the error you get?

**Comment by Marginal** [comment]
> I think EDSM no longer offers plain HTTP.

It doesn't, and it can't while it uses Cloudflare CDN.

**Comment by gregmcdougall** [comment]
so, it's working (which is good, if frustrating). may have been a Cloudflare issue.
