### ISSUE TITLE
Unterminated string starting at: line 1 column 135 (char 134)

### ISSUE THREAD

**Issue by aarronc** [Marginal/EDMarketConnector#211]
Hi, 
I have had this issue since upgrading to 2.3.2.1 whenever i jump into a system i get 'Unterminated string starting at: line 1 column 135 (char 134)' appear at the bottom of the window

Please See image here : http://i.imgur.com/iHHtGlk.png

is there any way to fix it?, the client does not seem to be updating to EDDN. 

Many thanks, 
![edmcerror](https://cloud.githubusercontent.com/assets/1708701/25976762/e99655b6-36ae-11e7-8ea7-87e4afaafef9.png)

**Comment by Marginal** [comment]
This suggests a problem in the Journal file that the game produces, and which EDMC uses.
Please zip up and attach here the latest Journal file from  Saved Games\\Frontier Developments\\EliteDangerous .

**Comment by aarronc** [comment]
i normally have this show up when i load the game and i am docked. It goes saway when i launch and then comes back again when i FSD Jump to any system.

For some reason it wont let me attach a zip even though it is listed as a valid file type to attach.

here is a link to it : https://www.dropbox.com/s/9zokr51db57gd90/Journal.170512105128.01.zip?dl=0

Thanks for the reply,

**Comment by Marginal** [comment]
Thanks.
I can't see anything wrong with the Journal file you attached, and EDMC consumes it without error.
The Journal file contains a record of one FSD Jump. Did you see this error appear after that jump?

**Comment by aarronc** [comment]
the error appears after every jump. also if i load the game while i'm docked at a station. there is a message that flashed up a split second before it 'Sending data to EDDN [208]'

i can provide more logs or a video if needed.

**Comment by Marginal** [comment]
I'm pretty sure the error must be in the Journal file handling, so please post more of your recent Journal files.

**Comment by aarronc** [comment]
here is my latest log:
https://www.dropbox.com/s/mufcfgvtjnq36j2/Journal.170512112137.01.zip?dl=0

thanks for the help so far i appreciate it.

here's a video of what happens when i jump and land ect : https://youtu.be/NpGAr6oKNnQ

**Comment by Marginal** [comment]
Thanks for making and posting that video - it tells me I was on the wrong track.

You've previously either had the "Delay sending until docked" option set or have had problems sending data to EDDN. EDMC is trying and failing to send your old data to EDDN.

Please attach the file %LOCALAPPDATA%\\EDMarketConnector\\replay.jsonl.

If you don't care about your old system and body scan data you should be able to make the problem go away by quitting the app, deleting this file, and restarting (but please post the file first!).

**Comment by aarronc** [comment]
thanks for that, the scan data isnt that important to me as i think EDDiscovery was posting that data. Would it be a conflict of using both of the programs at the same time?

Here is the replay.jsonl file as requested https://www.dropbox.com/s/73meno7gkogjv5g/replay.zip?dl=0

**Comment by Marginal** [comment]
I'm not sure how that corruption happened, but next version will be more robust if it does.

Deleting this file should fix the problem (and I just resent your old data while testing).

There's no problem running EDMC and EDDiscovery in parallel - EDDN should filter out the duplicate reports. But you can disable sending system and scan data to EDDN in one of the programs if you like.
