### ISSUE TITLE
Missing: Open/Solo tag next to CMDR Uncle Bob

### ISSUE THREAD

**Issue by BeckyYork** [Marginal/EDMarketConnector#212]
Currently there's a tag saying which private group you're in eg.
CMDR Uncle Bob / T-800

Please add "Solo" and "Open" tags as well so we have no doubt as to what mode we're playing in.

Thanks.

**Comment by Marginal** [comment]
Next release will say "Cmdr: Uncle Bob / Solo" if in Solo mode.
It won't say "Open" because that is the default mode !
