### ISSUE TITLE
No unnamed columns in market-data-csv

### ISSUE THREAD

**Issue by felixlinker** [Marginal/EDMarketConnector#214]
Hi,
first: great tool. But I'd appreciate it to have no unnamend columns in the csv. Right now one has no column name for the textual description of demand and supply values. I'd be great to have them named `Demand (textual)` and `Supply (textual)`. Shouldn't be too much work either :)

Best regards
Felix

**Comment by Marginal** [comment]
The commodity CSV format is shared with some other tools, so I don't really want to change it unilaterally. I appreciate that the unnamed fields make it less convenient to import, but you can work round this in most environments.

**Comment by felixlinker** [comment]
Sure thing. If it's already in "heavy" user I understand your choice!
