### ISSUE TITLE
Feature Request: Debug window

### ISSUE THREAD

**Issue by JoelleEmmily** [Marginal/EDMarketConnector#216]
An option to enable a debug window to see what data is being sent/received.

**Comment by Marginal** [comment]
For what purpose?

**Comment by JoelleEmmily** [comment]
To better determine what information might be needed or might be unnecessary, and to assist the community in aiding the programmer in creating a more robust utility.

**Comment by Marginal** [comment]
Sounds a bit obscure for a general feature.

You can achieve this by [running from source](https://github.com/Marginal/EDMarketConnector/wiki/Running-from-source#running-from-source) and print the `msg` in [EDDN.send()](https://github.com/Marginal/EDMarketConnector/blob/master/eddn.py#L95) and print the `url` in [EDSM.call()](https://github.com/Marginal/EDMarketConnector/blob/master/edsm.py#L91).

**Comment by inorton** [comment]
You could write a plugin to hijack stdout/stderr and put them in a text box in a prefs tab?
