### ISSUE TITLE
Fails to install Error 1935

### ISSUE THREAD

**Issue by Squidocide** [Marginal/EDMarketConnector#217]
Just installed windows fresh, updates were all successful, but I can't install EDMarket connector or the 2005 vc++ redist.

**Comment by Marginal** [comment]
Error 1935 indicates that the Windows Installer is misconfgured or broken.
Follow the instructions at https://support.microsoft.com/en-us/help/947821/fix-windows-update-errors-by-using-the-dism-or-system-update-readiness-tool (this link talks about Windows Update, but the fix should address your problem too).
