### ISSUE TITLE
'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by AiryKai** [Marginal/EDMarketConnector#219]
So...

Just tried to use plugins... And here is what I got:

E:D Market Connector 2.3.3.0 2017-06-11T17:09:50
loading plugin EDMC-Inara-master-74d2480a060e0e85d4f798d9bf1572cba3e3317f
EDMC-Inara-master-74d2480a060e0e85d4f798d9bf1572cba3e3317f: 'ascii' codec can't encode characters in position 9-13: ordinal not in range(128)
loading plugin edstats-edmc-plugin-master
edstats-edmc-plugin-master: 'ascii' codec can't encode characters in position 9-13: ordinal not in range(128)

**Comment by Marginal** [comment]
Sorry about that. Will be fixed in the next release.
