### ISSUE TITLE
Automatic update?

### ISSUE THREAD

**Issue by Amarok73** [Marginal/EDMarketConnector#22]
Would it be possible, to make appliaction do automatic commodity data update in eddb when - for example - station name changes from the one where user was to new one where he just docked?

**Comment by Marginal** [comment]
There's no way to tell that you've docked other than to ask Frontier's servers.

So it is possible to do automatic updating but it would require polling the Frontier servers every minute or so, which I don't think they'd be happy about.

**Comment by Amarok73** [comment]
Hello, thank You for answer. 
Do You know perhaps, how often this request goes to servers from regular client software?

**Comment by Marginal** [comment]
The game client is in regular contact with the game servers - sometimes multiple times a second. The game servers are set up for this. The servers are hosted on Amazon Web Services for scalability and load balancing.

The servers that supply the "Companion" API that this and similar apps use are also hosted on Amazon Web Services, but Frontier have stated that they're not set up for anything like the same volume of traffic.

**Comment by Amarok73** [comment]
Ok, thank You for that information.
