### ISSUE TITLE
cmdrHistory file support

### ISSUE THREAD

**Issue by ArghArgh200** [Marginal/EDMarketConnector#220]
In essence, there's a file that immediately and accurately corresponds to the comms panel's history tab (the one with the clock)

transcript from discord:

best I can tell the format for the history file is as such: 
```js
{
  "Interactions": [
    {
      "UserID": 0, // User ID, there's only one per account
      "CommanderID": 0, // CMDR ID, differentiates between saves for a user
      "Name": "ExampleCMDR", // properly capitalized/formatted name of the CMDR
      "Epoch": 13141540721, // timestamp of when they were last sighted (not adjusted to game time or game year)
      "Interactions": [ // there's a bunch of possible strings that can be here, msot notably "Met", "KilledBy", "WingMember", and a few others
        "Met"
      ],
      "MultiCrewSessionID": "", // usually blank unless you were in a MC session with them, then it'll probably have a number here
      "Avatar": "snip" // suuuuuper long base64- or hex-encoded string that stores their avatar (just decode it and you'll have basically a blueprint. it's not an image! just a list of parts and their places.)
    }
    // then there's just more entries. It only saves the last 50 CMDRs interacted with. at CGs this'll fill up quickly.
  ]
}
```

History file location: `%LOCALAPPDATA%\Frontier Developments\Elite Dangerous\CommanderHistory\<player's CMDR ID>.cmdrHistory`

I think the file is updated every time something changes in the instance (player joins/leaves instance, you form up with a wing or multicrew)

also it should be noted that in the history panel if you kill an NPC-controlled fighter from another CMDR's ship, it'll say you killed the CMDR, and if your NPC fighter dies to a hostile player it'll say you were killed by them

examples
[history panel screenshot](https://arghargh200.net/u/esoYJVBrcgt7.png)
[history file that corresponds with screenshot above](https://arghargh200.net/u/TEfFXIMmW1xZ.txt)

**Comment by Marginal** [comment]
What kind of "support" would you like?

**Comment by ArghArgh200** [comment]
just a plugin hook fired each time a new cmdr shows up (sending just that
CMDR's entry) and a function to check for a cmdr in the file already and
get those details

**Comment by inorton** [comment]
I'm actually going to have a go at this right now. I'll try it as a plugin first

**Comment by Marginal** [comment]
Added [`interaction`](https://github.com/Marginal/EDMarketConnector/blob/master/PLUGINS.md#player-interaction) callback. Please give it a go.
