### ISSUE TITLE
cmdr_data for plugin not sent on start

### ISSUE THREAD

**Issue by zabulus** [Marginal/EDMarketConnector#221]
I need commander name/location on start of my plugin, but cmdr_data is sent only if something changed/docking occurred. But as I can see at least commander name is available on start.

**Comment by Marginal** [comment]
The Cmdr name is not known at startup. It *is* known soon after - create a [`journal_entry`](https://github.com/Marginal/EDMarketConnector/blob/master/PLUGINS.md#journal-entry) callback in your plugin.

**Comment by zabulus** [comment]
My plugin already uses journal_entry, and nothing with cmdr name arrives, after game login only StartUp event arrives, but in edmc own ui there is cmdr name.

**Comment by Marginal** [comment]
The Cmdr name is supplied as the first argument to `journal_entry`.

**Comment by zabulus** [comment]
Oh, mah eyes. Thanks about that.
