### ISSUE TITLE
Ship Locations / Details not updated in EDSM when using CMDR name and APP_ID.

### ISSUE THREAD

**Issue by Xantraus** [Marginal/EDMarketConnector#222]
Hi

The ship locations display of four ships currently owned correctly on Status tab of EDMC, however, my active ship and the locations of my other ships never change. (I am flying a Cobra MK III, but on EDSM, it shows me in another ship I own, a Federal Assault Ship.)

This does not change, if using EDMC directly to update EDSM, or using The Trade Computer MKII to call EDMC.

**Comment by Xantraus** [comment]
![edsm_fleet_screenshot](https://user-images.githubusercontent.com/29513613/27257535-aff9faa2-539f-11e7-8dfc-22dee5506238.jpg)
All ships should be in Shinrarta Dezhra, and I should be piloting the Cobra MK III. Yet EDSM show me piloting the Federal Assault Ship.

**Comment by Marginal** [comment]
TCE Mk II doesn't (as far as I'm aware) update EDSM, and neither does EDMC when it's acting as a helper to TCE Mk II.
The EDMC app will update EDSM if you have it running when you do something with your ship - e.g. change ship or jump to another system.

**Comment by Xantraus** [comment]
Should I leave EDMC app running in background when playing ED? I assumed that TCE MK II would do the heavy lifting with EDMC, and there was no need to also manually run EDMC.

**Comment by Marginal** [comment]
> Should I leave EDMC app running in background when playing ED?

If you want it to update EDSM then yes.

**Comment by Xantraus** [comment]
After leaving EDMC running in the background, while using TCE MKII when playing ED, Three of my four ships are now in the correct locations. I had to leave the system with each and return. But that did now work for the Cobra MK III. TCE MKII shows the Cobra MKIII with the name of one of my other ships, and the locations and paintjob displayed in EDSM are still incorrect. I'll reach out to the developer of the tCE MKII.
