### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by Sniffy75** [Marginal/EDMarketConnector#223]
Had to do a fresh install after I had to do a fresh windows 10 install.. EDMC did not ask for my log in credentials when i ran it the first time, nor can I add them in the settings since all the relevant fields under identity are greyed out.
If tried downloading and installing earlier versions with no success.
I'm sure Ive missed some critical thing but I've run out of ideas.

**Comment by Marginal** [comment]
For anyone else who stumbles across this: https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#credentials-settings-are-greyed-out
