### ISSUE TITLE
Lost credentials and cannot enter them

### ISSUE THREAD

**Issue by nemesyssoft** [Marginal/EDMarketConnector#224]
Not sure what happened. I used the latest version yesterday and everything was OK. I just open the app and now, it doesn't show my commander name, my ship, which system I'm in and which station. Worst, if I go in settings and try to enter my ED credentials, I can't. Both the username and the password fields are disabled!

**Comment by Marginal** [comment]
See https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#credentials-settings-are-greyed-out .

**Comment by nemesyssoft** [comment]
I think that EDMarketConnector should still display the text in the textfields to avoid creating confusion.

**Comment by Marginal** [comment]
Problem is that EDMC doesn't know your Cmdr name while E:D is at the main menu - the information is not present in the Journal until you start the game.

**Comment by nemesyssoft** [comment]
No, I'm talking about your ED credentials. Even if the main window is empty, when I checked my ED credentials (and EDSM as well), I thought my data had been corrupted somehow since my email and password were not showing.

**Comment by Marginal** [comment]
Your E:D credentials are linked to your Cmdr name since, for users with multiple accounts, credentials will be different depending on which Cmdr is active. (Most users don't have multiple accounts, but the program has to assume that you might).

I will add a note on this screen in the next version.
