### ISSUE TITLE
Credentials missing - cannot re-enter data

### ISSUE THREAD

**Issue by mikelimtw** [Marginal/EDMarketConnector#226]
I get an Error: Invalid Credentials message on the main EDMC panel, but when I go into settings, I am unable to enter my information for both the FDev companion API and also for EDSM. The boxes are greyed out and I am unable to re-enter my information. EDMC was working until yesterday, so I'm not sure what happened in the last 12 hours or so. I have uninstalled, and re-installed EDMC to see if I could get EDMC to allow me to access those information fields, but no joy.

**Comment by martinjh99** [comment]
Same here - Just installed having installed before and deciding not to use it.  The credentials settings are also greyed out and not allowing me to re-enter them.

**Comment by Marginal** [comment]
Duplicate of #224
