### ISSUE TITLE
A newer version of Elite Dangerous Market Connector is already installed

### ISSUE THREAD

**Issue by VAV1ST** [Marginal/EDMarketConnector#228]
Windows 8.1 x64
Release 2.34 Does not work.
Downloaded Release 2.33 
The game is installed in the Steam on an external hard drive

![1](https://user-images.githubusercontent.com/30325556/28433124-3f2f1b82-6d93-11e7-8273-0aacc1824b46.JPG)

**Comment by Marginal** [comment]
> Release 2.34 Does not work.

What bad thing happens with 2.34 ?

**Comment by VAV1ST** [comment]
Программа установки запускается на 1 секунду. И сразу выключается.

**Comment by VAV1ST** [comment]
Sorry, Sorry. Problem solved)
