### ISSUE TITLE
Special characters in passwords not supported ?

### ISSUE THREAD

**Issue by TheRealBix** [Marginal/EDMarketConnector#231]
I can't connect to my account, nothing happens when pressing OK in settings.

It seems related to special characters in mail or password : 

With "testC" as password, pressing OK works and the password is detected as wrong.
With "testÇ" as password, pressing OK doesn't work.

characters not working : é è ç à ö ô € ....

edit : A weird thing is that even if typing the char doesn't work, copy paste do works

**Comment by Marginal** [comment]
This is due to a bug in the UI framework that EDMC uses - https://sourceforge.net/p/tktoolkit/bugs/2722/ . It's fixed in newer versions but macOS still ships with an older version.

As you've found, the workaround is to use copy & paste.
