### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by AiryKai** [Marginal/EDMarketConnector#234]
Hello.

I think this problem already existed in previous versions.

Now it's back to 2.40 and does not allow the plugins to work.

Traceback (most recent call last):
  File "plug.pyo", line 135, in load_plugins
  File "plug.pyo", line 42, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 9: ordinal not in range(128)

**Comment by Marginal** [comment]
What's the full directory path of your plugin?

**Comment by Marginal** [comment]
Thanks. And your plugin name?

**Comment by AiryKai** [comment]
Any plugin. HabZone for example.

**Comment by Marginal** [comment]
Sorry about that. Please try [2.41](https://github.com/Marginal/EDMarketConnector/releases/tag/rel-241)
