### ISSUE TITLE
Not Transferring Drones to EDSM

### ISSUE THREAD

**Issue by gregmcdougall** [Marginal/EDMarketConnector#236]
Not transferring drone/limpet information to EDSM.

{ "timestamp":"2017-08-25T09:30:20Z", "event":"Cargo", "Inventory":[ { "Name":"gold", "Count":327 }, { "Name":"drones", "Count":5 } ] }

**Comment by AnthorNet** [comment]
They should be, or I made a mistake, they are hidden from stations commodities, so they don't have a proper category over EDSM.
I will check right now.

**Comment by AnthorNet** [comment]
Fixed
