### ISSUE TITLE
Error: Invalid Credentials

### ISSUE THREAD

**Issue by shuki25** [Marginal/EDMarketConnector#237]
Just prior to updating to 2.4.0, I launched EDMC and it asked me to enter verification code from Frontier, I entered it and it said invalid.  It was working before.  Then I updated EDMC to 2.4.0 and restarted the app, it cleared out my log in credentials so I re-entered them and still get the "Error: Invalid Credentials" and did not get the verification code from Frontier.  Still having the problem for half hour.  I even changed the password with Frontier, still having the same error.  Still no verification code email.

**Comment by shuki25** [comment]
I also cleared the cookie.txt file from %USER%\AppData\Local\EDMarketConnector, still can't log in.

**Comment by Marginal** [comment]
If you've recently changed your Frontier password and/or reset your Cmdr profile it can take a while for the Frontier server that this app talks to synchronise.

Quit the app, delete the cookie file, restart the app and try again. If it still doesn't work you'll just have to wait I'm afraid.

**Comment by AndreS8Shok** [comment]
can't login too, updated and can't login.

I deleted cookie files and i have not update my username or password since i bought the game :/

**Comment by shuki25** [comment]
Just tried it again and it is working now.
