### ISSUE TITLE
New Plugin EDMC-Screenshot

### ISSUE THREAD

**Issue by NoFoolLikeOne** [Marginal/EDMarketConnector#238]
I have written a plugin to take the in game screenshots, convert them to png and rename them after System(Body)_nnn.png and optionally delete the original file. 

Perhaps you can add it to the list of plugins?

https://github.com/NoFoolLikeOne/EDMC-Screenshot/blob/master/README.md

**Comment by inorton** [comment]
Very nice!

**Comment by Marginal** [comment]
Done - https://github.com/Marginal/EDMarketConnector/wiki/Plugins
Sorry for the delay.
