### ISSUE TITLE
 Error: Invalid Credentials

### ISSUE THREAD

**Issue by Berbe** [Marginal/EDMarketConnector#242]
My problem does not seem to be related to #165. I am using EDMC for Windows (`7 x64`).

Everything worked fine in `v2.4.1.0` on `v2.3` Elite: Dangerous.

After having patched the game to `v2.4`, I updated EDMC to `v2.4.3.0` and all I can get is the `
Error: Invalid Credentials` message.

Here is what I tried:
- Reinstalling `v2.4.3.0`
- Rebooting PC
- Uninstalling + cleaning up (deleting) EDMC data :
    * `<User>\AppData\Local\EDMarketConnector`
    * `HKCU\Software\Marginal\EDMarketConnector`

Of course, deleting the cookie (and even more deleting all data) had me reauthorized the app, which I did seamlessly.

I see on [ROSS logs](https://ross.eddb.io/eddn/log?parsing_result=&parsing_result_detail=&header_software_name=E%3AD+Market+Connector+%5BWindows%5D&schema=&schema_main_group=&schema_sub_group=&system_id=&station_id=&body_id=) that other EDMC Windows clients are working fine. Is there something I haven't checked which could be wrong on my side? Or could there be something wrong with the `v2.4` cAPI? Or maybe have you changed something on your part regarding login (I aven't found anything in the commits)?

Note: I did not try `v2.4.2.0`, I jumped from `v2.4.1.0` to `v2.4.3.0`, might that mean somehow the problem lies in the cAPI?

**Comment by faybs** [comment]
+1 here.  I should remark that when I ran ED 2.4 this evening, the launcher asked me to type in my credentials before it would let me launch the game and I had to paste in a code from a Frontier email.  I'd run the game yesterday so I don't think my credentials had expired.

**Comment by Marginal** [comment]
The Frontier cAPI is still not properly up yet.

**Comment by inorton** [comment]
@Berbe wrt ROSS, EDMC submits some data from the companion API and some data from journals. It will still be able to submit journal data to EDDN

**Comment by shaunpond** [comment]
EDDI is similarly affected (I raised a ticket for that)

**Comment by Kireth** [comment]
2.40.0 ....since updated to ED 2.4 the Invalid Credentials started...have been deleting the cookies, upgraded to 2.4.3.msi....but no...s

**Comment by fmacbeth** [comment]
same issue v2.4.3 msi used to re-install after uninstall, deleted reg keys and files in app data before re-install. I got a verification notice, which worked but still getting the same message. The program detects where I am in ED but does not seem to send data.

**Comment by gregmcdougall** [comment]
Me too. Can we help, or are we certain it's at the Frontier end?

**Comment by Sniffy75** [comment]
Have same issue, but just tried a clean install of the older 2.4.1 and still getting the same problem so i don't think its an issue with 2.4.3.. probably some change in the background with ED 2.4 has broken things.

**Comment by sleoj** [comment]
This just happened to me too.  I started the ED:H 2.4 update (still syncing).  I then updated EDMarketConnector.  After a few botched key-entry attempts, I finally got through but then hit "Invalid credentials".  Uninstalling EDMarketConnector, deleting the "Marginal" HKCU registry key for it and its %localappdata%\EDMarketConnector folder, then reinstalling it did not correct the problem.

**Comment by inorton** [comment]
Howdy peeps, we know about this one and it's out of our power to fix, FDev are working on the server end. Stat tuned

**Comment by Berbe** [comment]
Frontier has reacted on the [cAPI issue](https://forums.frontier.co.uk/showthread.php/378874-cAPI-asking-user-to-purchase-ED) submitted to them and has acknowledged it yesterday.

Wait and see...

**Comment by Kireth** [comment]
it should be no surprise, as it's on FD's end but just FYI, but Mac version 2.4.2 has same issue

**Comment by draeath** [comment]
Frontier are considering this issue of the ["highest priority"](https://forums.frontier.co.uk/showthread.php?p=5966220&viewfull=1#post5966220) so we'll have a fix sooner rather than later, one hopes.

**Comment by livewater1977** [comment]
Can't wait when it will be finally fixed!

**Comment by NoWan2500** [comment]
Thanks Draeth.  I just started using EDMC a week before the update and I was already hooked. :)  Not to mention how all of the data to all of the websites helps the whole ED community.

**Comment by insuusvenerati** [comment]
Did the update this morning fix the issue? I'm still getting the error.

**Comment by shaunpond** [comment]
You may have to just re-enter your credentials. For Eddi I had to re-authenticate with a code, but for the market connector I just re-entered my password. All 
OK now

Shaun

**Comment by argent-smith** [comment]
Still have it, 2.4.2.0

**Comment by Loutreck** [comment]
Its still there. With 2.4.2 and 2.4.3. Changing the PW in ED and entering the new does not help either.

**Comment by Alendrathril** [comment]
It started working for me the other day.  I didn't have to do anything.

**Comment by Kireth** [comment]
removed cookie, re-authenticated with validation-code....but ala...still there

**Comment by scrodev** [comment]
Still "Error: Invalid Credentials" with 2.4.3. I tried some relogin every 30 minutes after ED Update but it want connect. Also reinstallation (deinstallation, registry clean, AppData clean) dont work

**Comment by ZXZver** [comment]
No commodity update to EDDN logs in the past 7 days. The project is collapsed?

**Comment by draeath** [comment]
Folks, Frontier broke the API with the 2.4 patch. They are aware and have committed to fixing it. There's nothing we can do but wait.

**Comment by bk1984** [comment]
Dreath, the API was listed as fixed in the patch that was released today.

**Comment by Loutreck** [comment]
Well, then the statement "Fixed Companion API authentication problems" in the latest patch note is "doubtful".

**Comment by insuusvenerati** [comment]
They are working on it. Let's give it some time. 
https://i.imgur.com/Gcyg1yS.png

**Comment by Soulflare3** [comment]
I was momentarily hopeful when I saw this
![Error: Frontier server is down](https://i.imgur.com/hQgU5DC.png)
But on update it returned to this 🙁 
![Error: Invalid Credentials](https://i.imgur.com/tUO5Ifc.png)

**Comment by shaunpond** [comment]
Mine was working, just as I said earlier, but I just unloaded it and tried again... And it fails 

Shaun

**Comment by draeath** [comment]
That's the kind of thing meant when it's said the API is currently unstable.

Just hang in there, everyone.

**Comment by Marginal** [comment]
The cAPI is still flakey, so expect to see "Invalid Credentials" errors on occasion. When this happens no intervention is required on your part, other than to press "Update" to try again.

If you see "Station doesn't have anything" errors then please update to EDMC version 2.43.

**Comment by L1Pritchard** [comment]
>The cAPI is still flakey, so expect to see "Invalid Credentials" errors on occasion.

I'm seeing it every time I try to update.
I've reinstalled the app and cleared the files.
Am I missing something?

**Comment by scrodev** [comment]
> I'm seeing it every time I try to update.

Also here. Tried it every hour since 2.4.02 release.
I've reinstalled and/or cleared the files and registry several times.

All i got every time: "Error: Invalid Credentials"

**Comment by NoFoolLikeOne** [comment]
same here

**Comment by Alendrathril** [comment]
Same.  Back in the old boat now.

**Comment by Berbe** [comment]
You can see from the [ROSS EDDN logs](https://ross.eddb.io/eddn/log?parsing_result=&parsing_result_detail=&header_software_name=&schema=https%3A%2F%2Feddn.edcd.io%2Fschemas%2Fcommodity%2F3&schema_main_group=&schema_sub_group=&system_id=&station_id=&body_id=) that some people are updating the commodities price with EDMC.

Still using the v2.4.3.0 version, I tried deleting the local data once again (having to reauthorize the 3rd-party application), but still no success at all and the same error message. That's getting old now...

@Marginal Do you have any slightest idea on why some people's client work and some don't?

**Comment by njcrawford** [comment]
> Do you have any slightest idea on why some people's client work and some don't?

I have v2.4.3.0 and it seems to work occasionally, but there doesn't seem to be a pattern to it. I'd venture to guess that it's affected by the load on Frontier's cAPI server(s) at any given moment.

**Comment by Marginal** [comment]
> Do you have any slightest idea on why some people's client work and some don't?

No. Last I heard Frontier are adding some logging to their cAPI server to help diagnose.

**Comment by NoFoolLikeOne** [comment]
I installed completly from fresh on a new PC and can't get EDMC to work at all because of it. 

Its very frustrating. I feel for you guys having to answer queries for a problem not of your making

**Comment by chrismartinau** [comment]
I have two Elite accounts, and I run them on different machines.

On one account all I had to do was clear the EDMC cookie file and re-validate and I was up and running.

On my other account there is nothing I can do to get it to work. I can press 'Update' a thousand times and it never works. What is interesting is that it appears to be the validation that's not working. I get the e-mail after removing the cookie file and type the code in (taking great care not to make any errors) and it asks for the code a second time. I type it in again (still taking a lot of care not to screw it up) and the validation window goes away, and immediately it says "Invalid Credentials" and will not work, no matter how many times I press Update.

I do think there is something wrong with the cAPI, and it's effecting a subset of accounts. If there is further detail I can provide to help the process, please let me know.

**Comment by Berbe** [comment]
> I do think there is something wrong with the cAPI, and it's effecting a subset of accounts. If there is further detail I can provide to help the process, please let me know.

@chrismartinau You think well: the problem is on the game developer server side, not clients, as Marginal stated and confirmed (as do all 3rd-party developers). You can follow the core issue & resuolution on the [cAPI thread on Frontier forum](https://forums.frontier.co.uk/showthread.php/378874-cAPI-asking-user-to-purchase-ED).

For some people it works, and it seems that when it does it might only temporarily. The rest of use remain stranded outside.

It seems it is not the first time it happens, but as long as people continue to buy their useless products (ie skin packs) and money is pouring in on their side, their management probably won't take such trouble more seriously than that and allocate time so developers can trace this kind of issue better.

Be patient for now and in the future refrain on buying supplemental content until Frontier show deep signs of changes in its priorities of what to process is all you can do.

**Comment by NoWan2500** [comment]
Where is this "Cookie file" referenced a few times?

**Comment by Marginal** [comment]
cAPI *should* now be working for everybody.
If it's not working for you:
- Quit EDMC.
- Windows: Delete the files `%LOCALAPPDATA%\EDMarketConnector\cookie*.txt` (usually `C:\Users\you\AppData\Local\EDMarketConnector\cookie*.txt`).
- Mac: Delete the files `~/Library/Application Support/EDMarketConnector/cookie*.txt` (in Finder hold ⌥ and choose Go → Library to open your ~/Library folder).
- Restart EDMC and press "Update".

If you're prompted for a verification code then your credentials are OK.
If you're not prompted then check your email and password in settings.
If you see "Invalid Credentials" after getting and entering the validation code then the cAPI is not working for you.

**Comment by chrismou** [comment]
No joy @Marginal .  I've just installed the app for the first time about 10 mins ago, and I can't get past the "invalid credentials" error after entering my login details.

Have double checked, and I'm able to log into the Elite with the same creds

**Comment by Kireth** [comment]
JAY!!!>>>MACversion works!...will try PC now

**Comment by stenyak** [comment]
Works for me, Windows version. Last time I removed the cookie files was a day ago, I didn't need to renew them today, it just worked.

**Comment by NoWan2500** [comment]
Unfortunately I did thsi before seeing Marginals notes a few messages ago.
So try Marginal's fix first.

Here are the steps I took to fix my EDMC.

Note:
-Follow these steps at your own risk.
-Some of the steps may not actually have contributed to the "fix".

1. Close all programs
2. Cleaned files and registry with ccleaner
3. Restart computer
4. Uninstall ED Market Connector using Revo Uninstaller (free portable version)
*I used default options for uninstall that allowed me to delete all related registry entries and related files and folders.
Note: Revo's setting's indicate it will create a Windows Restore point before uninstalling, but I didn't test this.
7. Restart computer
8. Download and installed latest EDMC installer
9. Ran EDMC filled in my Elite Dangerous and EDSM information.
*Selected to make a new EDSM API Key
11. Launched Elite Dangerous

**Comment by Kireth** [comment]
Excellent! Next to the Mac version, Win7 version worked as well.....just needed to remove cookie

**Comment by amaraltx** [comment]
"If you see "Invalid Credentials" after getting and entering the validation code then the cAPI is still not working for you."

Any solution yet for those who are still not able to use it?

Thanks!

**Comment by Marginal** [comment]
@amaraltx Please update to [2.44](https://github.com/Marginal/EDMarketConnector/releases/latest) and see if you get "Invalid Credentials" or "Frontier server SKU problem" error.

**Comment by L1Pritchard** [comment]
Works for me now too. 👍

**Comment by amaraltx** [comment]
@Marginal - brilliant. Seems to be working fine now!

Thanks

**Comment by ziceman** [comment]
Still having trouble, updated to new version and deleted cookie. Getting invalid credentials and a greyed out update button.

**Comment by Marginal** [comment]
@ziceman Double-check your email and password settings.

**Comment by ziceman** [comment]
Tried that, even a complete re-install of edmc. Doesn't seem to be saving the login details no sign of the verification check upon re-install.

**Comment by Jagget** [comment]
@Marginal @ziceman Same for me. I'm unable to connect no matter what I did

**Comment by Soulflare3** [comment]
After updating to the most recent version and deleting the cookie files, I'm now able to log in finally. Thanks @Marginal

**Comment by neutronium** [comment]
> I have two Elite accounts, and I run them on different machines.

Same here. 1st machine was upgraded to windows 10 and works fine (have not yet updated this machine to latest EDMC 2.4.4.0 - i.e still using 2.4.3. Shall I update or is there a chance for loosing functionality on this as well???)
But the old one is on Win7 and even after upgrading to 2.4.4.0 (doing a clean upgrade i.e.
- uninstalled previous version, 
- used ccleaner to clean disk and registry, 
- deleted program files(x86)\EDMC directory and 
- cleared EDMC cookie(s)
still no joy..

**Comment by ziceman** [comment]
@Marginal All working now, came back to it fresh this morning and all working as it should be. I must have missed something, who knows what!

**Comment by Marginal** [comment]
@neutronium See advice [above](https://github.com/Marginal/EDMarketConnector/issues/242#issuecomment-334738347)

**Comment by Berbe** [comment]
@Marginal I suppose you wanna leave that ticket open until only a marginal (no play with words I promise) amount of players is still impacted?
Case solved for me.

I let you close it when you see fit.

**Comment by Marginal** [comment]
@Berbe yes. I believe that lingering issues (if any) are just due to caching at the server end. Will leave this open for a while to catch any reports.

**Comment by neutronium** [comment]
> @neutronium See advice above
Marginal I am sorry. I tried these steps. I even deleted the whole C:\Users\you\AppData\Local\EDMarketConnector\ folder. No luck. The strange thing is that Elite: Dangerous Launcher and Elite: Dangerous game itself as well as EDDiscovery app tool are all loading OK.

**Comment by inorton** [comment]
@neutronium try deliberately setting the wrong cmdr name and then restart edmc twice, try your own details on the 3rd restart

**Comment by neutronium** [comment]
@inorton I just reinstalled after reading your message and ... IT WORKED out of the box! i.e. just after installation, it asked for the verification code without me having to do anything! I am so happy! Thank you guys!
