### ISSUE TITLE
Engineers modifications not visibles.

### ISSUE THREAD

**Issue by Bimnomercy** [Marginal/EDMarketConnector#246]
Hi and thank you for your incredible work. If my memory is correct, during the bêta phase, the engineer's modifications were visibles when we clicked on the name of the spaceship and opened Coriolis.io. It is not active in de release version, is it a issue ?

Tanks.

**Comment by Marginal** [comment]
EDMC passes engineers’ mods to EDShipyard and Coriolis. Please raise this issue against https://github.com/EDCD/coriolis
