### ISSUE TITLE
Engineer data is missing

### ISSUE THREAD

**Issue by bazzawill** [Marginal/EDMarketConnector#247]
Hi guys
So now the ED API appears to resolved I had thought module engineering would be available in 2.4, so far I cannot see this

**Comment by sharkismyname** [comment]
Looks like we can see it in Shipyard but not Coriolis.

**Comment by bazzawill** [comment]
Ah I see, ok can switch to shipyard for the time being

**Comment by Marginal** [comment]
Duplicate of #246
