### ISSUE TITLE
Ship modifications - wong calculations

### ISSUE THREAD

**Issue by DeadlyMercury** [Marginal/EDMarketConnector#248]
Greetings!

I see there is engineering support in new version of EDMC and it works fine, but I found one bug with weapons. This is my ship:
https://goo.gl/TWZDRV

Everything seems correct (mass, jump range, speeds etc) exept of weapon DPS (its very low!). Must be something like that (seems that there is only wrong rate of fire):
https://goo.gl/xhTXYn

**Comment by Marginal** [comment]
EDMC just passes on the ship info to EDShipyard. Please report this problem to the EDShipyard author via Discord or one of the other contact routes listed on the site.
