### ISSUE TITLE
Does EDMC actually "log in"?  / account credentials hacked?

### ISSUE THREAD

**Issue by NoWan2500** [Marginal/EDMarketConnector#249]
If I leave EDMC running on my computer, Elite Dangerous (ED) itself is closed. Will it ever look like I logged into ED?

My brother noticed ED is saying I logged into ED, but I am not any where near my computer.
 I changed my ED password just in case. Still haven't' been back to my computer yet. No one else has access to my computer.

Thank you
 Nowan

**Comment by AnthorNet** [comment]
EDMC will never do that.
There is actually a bug in the game saying friends are online when they are not.

**Comment by NoWan2500** [comment]
@AnthorNet   Sounds good. Thank you for the info.
