### ISSUE TITLE
Engineering wont export to coriolis

### ISSUE THREAD

**Issue by Pendragon55555** [Marginal/EDMarketConnector#250]
Whenever I try to export my ships fit to coriolis.edcd.io the engineered modules and rolls are not transferred while they are transferred to www.edshipyard.com

**Comment by willyb321** [comment]
See https://github.com/EDCD/coriolis/issues/158#issuecomment-335675734

**Comment by strideynet** [comment]
Duplicate Issue.

**Comment by Marginal** [comment]
Duplicate of #246
