### ISSUE TITLE
Sending ship builds to EDSM results in HTTP 414 error

### ISSUE THREAD

**Issue by Athanasius** [Marginal/EDMarketConnector#251]
For a while since things died down after the CAPI was working again in ED 2.4 I'd been seeing "Error: Can't connect to EDSM" on any update.

I've just added a few key print() statements in plugins/edsm.py and it turns our that www.edsm.net is returning a 414 error because the URL is too long for a GET.  And indeed it is.  With my apikey elided it's trying to send:

```https://www.edsm.net/api-commander-v1/update-ship?commanderName=Athanasius&apiKey=ELIDEDOFCOURSE&fromSoftware=E%3AD%20Market%20Connector&fromSoftwareVersion=2.4.4.0&shipId=6&type=python&linkToCoriolis=https%3A//coriolis.edcd.io/import%3Fdata%3DH4sIAKt631kC_-1b227bSBL9FUPAYl4Sou-XvMV2LpO1d7yWMXkUaKktE6FILUVmRjPIv-9pyhc1RYoSnckCuxsMBFkjVd_qVJ1TXfxzdFc4N3pzF6cr92qUzEZv1KtRGlfZ9P40Xq9Gb_4cjdO8JGYyTv5wvP67uq0_8u_TPJ7lVTl6M1qVcVG6YvTq8bN_xAsYHo2fPs82H5RuVd5W8_l69O3bt1ejRT6rUlcP9LZY5FXh333Oiy8_Z1dFPi_cajXBd5K7ZBqXSZ7V3_ylKu-Sskyy-fvEpbOb9dJNzt2dy6busv6uKz66OC3vL6u0TJYp_vY_myWrZRqvf43Tys_E6kjZv2FmXzcf0MhqZQX-cWm4xOTaxnn3-zLNV8lXd-1WCVaNMVtsv-Y6kiIwzrUUHPatUYJ3GP97krkyme43TXVkwnlTbayQVmrCVNe8L-PVqs2ajigLjBFNqaVUWc5ol7Gbe1cseuZJIy23DJPIGiaksEpQY7T2h--yORa8OZzH9z_DBzkhjJLn___oSy51mTv55OIMdgs3TZbuwn11Kab9-PfDVze-NIEXfF2fVyWc7dHV_Fg7Tk-ZIcJyQZ7c9Gpd3ufZ5MHOhyKeOYpB82z0piwq_GxZJHmRwLIf-3GNflHnbhqn1A-zf0CltBbsacD6Z5OzfHEbl3DmeJaujxiPHTaeJI3xbvzCJjfraZ5nRwzHDxzONoarwVO4YvIuTUp32IDvC1gY3yd35XkB2A2ND6d5Xt4kizZPFRE3oadKRa0gRFqipOnAwPvxOdyrvI7LNps80jyEFddMa0OYYbLb4i_LMlnEaQdYmYhsCFYmLEWs4tYSbjvM_pyVbr7Z2pZgYiOugsUbogQx3BJBmLZHRhOEPa0bYU9rIgF8w5TotPb7-8qlV674VC2WrbHEqHA3qVHcWEIF7dzOq_w3V5wX8W8d65bhVlIrqaaKCcEY7YlOVO1Gp3fp16SITy6R76rqSzNAiUaAwllPLvJsfh1nc3dAdELUZM_BAkc6-Yg1FjMPiTo3y8lZikORHaAiTysVQhvNNtDCpt_E2Zd-NGN8vhU8_PiPP94enfdC2iIqCD_2RVzM3ce4mC3zJCvp4LQfL-J5a5o0EWvkH4r4Z5HaGOGsw2c25uCIYzfNs1kbBjVAuO2Mr5HokNWY4NhZRXWXZWTKIrmtyrzLJylmTEIoUm0RMoyGT6quKX_CB6385rVlEaMhwWGMSPAPJHjSBRsf0H65e58UbbvKLAlJE1aPIGmZslRy0Jsuo87Twq74KyITHpWUVEhqpOQMp9YDRsJ3wXha5PnJTVz8q0qyPih-dvESqf46XiazetmHcAVBnnPbx2U5uarwhYt45YrTqliVk5uqKFw5qb28AxTsacHgbVzSXVSw748KSiOlQycznCEeKEMpp_YFuFAh4DwuFENqIsZIY_lgXCDr8RAXGkwXOYpSrZkwR-PCiEiHuDBCEyOMtkZLNgwXyCeN1VsrhZLKE2nCBuHChDkKuKBCWyU1QlhvjvrvhQX__rCwkbBhsiCSEquMVNIKOhgVkBSR2NaBr1kkCMI5UgZDhHsBKsAwQ-IGtHGcgeLAsjoeFZDDQfrxcphaRbSBM3WibC_JMhENceYxyzhhoFjDcMaVjJQM9xMYk2C_lgKEZhDO_FJDnBlQBCEhqY1B4u0BmtkF2kXyx8n1elYXPgKU8e-CMssDlJ3Gq2R6maxWSequ4-mXyfvkdzebXLpZUi06YMa3CKFVfAOz5M6Nq-UyL8qhENsrNriJVBjJFRXEE2-FbdTsOLEhER55YE1QgXALPWS0oaavwtASHy-wOSef8H6VZ30nt7VZk4tkfl9-dv71MC4vRcClt215Oi02dJr10mmkP1sv9DJOsnf1YlZDj27z8z2a9rXWOLAA0ForooiV3BiruipmtV0oWwTKu7xYdNSLOI94KJk550xpzozSivcZ3yObEd1tQ-BDwhmKzdNGED1IN4uINMi6tAiYxpfgqNKDNCmNZBiBKZWEMqqMMYL3-TPb9Wc4wB3OPy9OruJ0N-XLhktvNhPJpzioYqaQ7UNN-mDAu7A6VI9CwlsNmlh7cR2xXq4KN2W7K5e5sqi_2ZZAm76Mk0MMwo4j7_O9Gb_FmmlSSqg2ygUCGyVUDOYPw8z2kgdgTYbkQUHgg1ZLxijplJp7EUHCGg1AZikEocELXOXIsrSNqGgg1osIgnxh5BBwCd5MFlIJZS2nHEme7C10x-kFyEN7BmqsWUBEKRAHiRxkbB9iW6pIN_ns5CeMenIK9ICp_XRyOf0n2Hovdh-IxLs7gCNxWXkYkVAkIBL1fclZnGWw9CFZ3MbpfhLxnIiEZnUBcrXEpBCJmyh9-HwyzYuivj6ZrO5dinVkVZq2QJ_9ldCnoaD05UQcB-eSay3ksdCHr5rQmqVGIMUYKV4gHYaZ7dcNOjIh2UXM48JKy9RQbNmIh-pJ1kCFSDW0uyLWgy3d5IqCCS9EPOPQVP0fWzvYSkCsslkSF-tJkVfZbPWMrivQw_JTfttf6dWcbs_88YeThwuxz9Aod_5GZkIOvA-7SmNgEZN6u1wWeTy9H1fJhl72XCBh1VQH9GJjKrTTNwek83oWtf8-o-NlJHl1Fi_jaXsiFCEYgFvBjUImtAwJcS-NXV276X1dGmkTT5FulCgUIxJqHwpAaHVcftVhVcLf-gquCAMZ07xLRI_XQM1i_9qlbqwd4lwLIpjqpCsPZvetne7c0BlFwbdB2LjtLOZvYLtvvgwKJswEjGokA2OoZ0L77e6ZsEJGCfcBAhdRy2hrRV89m7bUE3zUOv8NCXO3otC8-m56-uTqARUP0z6I2DMaEvsdo57i60MpvgG916CAjzj0OB5cYfAC9TEST9vLDCqiDSWpkOKUUr4YPeiaVLAwGyPFafgI9erXdKvTerV7_A88XDWuS7kCBfGleC5EX-HJ7jrKR1fEJzdxlvTltOeD8FfjQODsMMWnWhxjWZs5wCW2chqTRMIv_BKv41k8OCB3aX7w8IhvVwoZvID7C0CCQNd5sb2P58jQrRCFwEYIyBjBWXHVWc_M2mMECF549spSpZW29V15V7B0GeT8jY875XgaZ2-zedoaMiVp3iYK6-83FMMrJ_Y7V8ea7rWZ58N0j7zpZiKsjm2MrLbLCqy_rGAl_vOrHN8ny5_PyQHUBwpTP1dW_UqwpSU2vbYwOc-r29Rd-ArHh8Id2J6z-S39D47uLR24eiNaxq97hArCBgxLf_Cwvi-RbvxkcJ9QkX9x2bWb46WjDMpYs3oC2SjAmi3-qU4JdZanabLC2Pvb5mTEwks_sDvjCyngJSBSnQTSFfM19GQ98za7LLzkoBFlVmmv_Iwx-kXdjrJRF_ZajT-oVaU7Lz8P6XaEtmwEXYmEC6JqDIHK6r5X3XN-CpI3jOOcGS4kXoySXZkBPo23H1y2v9hsI9ZoVYKwphKaXXdWyJ9Mj8sCMbe8b71JDNtOQBVwdAjnhkAIsBc0atYNLI1yiKfsXCvwm75rFNpSdr5wycnZvauyeW-aeFw5aIunldcuye7yYnogG0H4CDNFw9zgQnQdSdhzJOnvjhI8mMkZMnRe38VtzaFfMXNqsPdPM-D_gRlILpl-moHYtHcdOAO2Zwby0BlQSqVSTzOQP34GIErkOaGozZXcIS2vCuxtp0luPM3z5fa1nuztfGBQAJrJpyno5_b7QX0P4_GGhvoaVFtuUDLiLODKSnIGagtuq4kaoJh4sw-UIJxoppRRVh7bo-7nFyQvPz-LlAj1D6YqBvUmqEg2moCUJFr7fgcw0B9Ej6viLp46T-QRso6hyd7XeEiTz10ZJ6mbNYzeJFk_fYIaI1suv_W4R2-RjpnQ5U_9wx2n8bo2wfbT9S2Pp1DST-PbzY8PgRyXioY5oHRpGhen-Wx9nqym-VdXrB_34u3sq0-Cs_4YJIniugag37_v0KcaPp6ySVR7H0_hsnkBwCWyA1FI-Vy97PGURlOSv6uT0lIIL2qFGoJ3Kpq9PkinlIJYdTdoH8L_hs20K5Aww0I6ySPDwIO1MRzRZFAgYTyiITFjnEJlS4Q60qnjDyFmfWvvqQ6R3RB1nsySk19Bi30XRnYYOdtUh456lgZRXnIV3H6Etjy6yaGlIoYo3wJF9le0KFGgLrh2YkAdUg3XVCB50WP9jZKwyANfIVQheXGkGtVXhKEtD0Fdx4uTm_i-r3vzym_RQ9A5jlVDVWw9aVA3ceKcFnFg8aGPc09u2eLVHgw7x8d_XCRltnklwyw32mrh-YMeFu0Ub0Q7pGOGbESl0C-Id6AhpHHTQaHvLDwJUUof-zgOt2Frvb-cMkIxziFJ5aCmTiaajTNMKMqpENZybf7Ho9IBMuEvQJghhteP0wZPL-J3q7p2iE_OPr7-_HH88Mnjvue3t3VT2IOZP0f3lW_JEHA5KjXZejrXUsst883dZV7G_tZJ-J4J7eVOlaV5nCG2QDcJ_zDBt2__BnBTN1dYPAAA&linkToEDShipyard=http%3A//www.edshipyard.com/%23/I%3DH4sIAKt631kC_-1b227bSBL9FUPAYl4Sou-XvMV2LpO1d7yWMXkUaKktE6FILUVmRjPIv-9pyhc1RYoSnckCuxsMBFkjVd_qVJ1TXfxzdFc4N3pzF6cr92qUzEZv1KtRGlfZ9P40Xq9Gb_4cjdO8JGYyTv5wvP67uq0_8u_TPJ7lVTl6M1qVcVG6YvTq8bN_xAsYHo2fPs82H5RuVd5W8_l69O3bt1ejRT6rUlcP9LZY5FXh333Oiy8_Z1dFPi_cajXBd5K7ZBqXSZ7V3_ylKu-Sskyy-fvEpbOb9dJNzt2dy6busv6uKz66OC3vL6u0TJYp_vY_myWrZRqvf43Tys_E6kjZv2FmXzcf0MhqZQX-cWm4xOTaxnn3-zLNV8lXd-1WCVaNMVtsv-Y6kiIwzrUUHPatUYJ3GP97krkyme43TXVkwnlTbayQVmrCVNe8L-PVqs2ajigLjBFNqaVUWc5ol7Gbe1cseuZJIy23DJPIGiaksEpQY7T2h--yORa8OZzH9z_DBzkhjJLn___oSy51mTv55OIMdgs3TZbuwn11Kab9-PfDVze-NIEXfF2fVyWc7dHV_Fg7Tk-ZIcJyQZ7c9Gpd3ufZ5MHOhyKeOYpB82z0piwq_GxZJHmRwLIf-3GNflHnbhqn1A-zf0CltBbsacD6Z5OzfHEbl3DmeJaujxiPHTaeJI3xbvzCJjfraZ5nRwzHDxzONoarwVO4YvIuTUp32IDvC1gY3yd35XkB2A2ND6d5Xt4kizZPFRE3oadKRa0gRFqipOnAwPvxOdyrvI7LNps80jyEFddMa0OYYbLb4i_LMlnEaQdYmYhsCFYmLEWs4tYSbjvM_pyVbr7Z2pZgYiOugsUbogQx3BJBmLZHRhOEPa0bYU9rIgF8w5TotPb7-8qlV674VC2WrbHEqHA3qVHcWEIF7dzOq_w3V5wX8W8d65bhVlIrqaaKCcEY7YlOVO1Gp3fp16SITy6R76rqSzNAiUaAwllPLvJsfh1nc3dAdELUZM_BAkc6-Yg1FjMPiTo3y8lZikORHaAiTysVQhvNNtDCpt_E2Zd-NGN8vhU8_PiPP94enfdC2iIqCD_2RVzM3ce4mC3zJCvp4LQfL-J5a5o0EWvkH4r4Z5HaGOGsw2c25uCIYzfNs1kbBjVAuO2Mr5HokNWY4NhZRXWXZWTKIrmtyrzLJylmTEIoUm0RMoyGT6quKX_CB6385rVlEaMhwWGMSPAPJHjSBRsf0H65e58UbbvKLAlJE1aPIGmZslRy0Jsuo87Twq74KyITHpWUVEhqpOQMp9YDRsJ3wXha5PnJTVz8q0qyPih-dvESqf46XiazetmHcAVBnnPbx2U5uarwhYt45YrTqliVk5uqKFw5qb28AxTsacHgbVzSXVSw748KSiOlQycznCEeKEMpp_YFuFAh4DwuFENqIsZIY_lgXCDr8RAXGkwXOYpSrZkwR-PCiEiHuDBCEyOMtkZLNgwXyCeN1VsrhZLKE2nCBuHChDkKuKBCWyU1QlhvjvrvhQX__rCwkbBhsiCSEquMVNIKOhgVkBSR2NaBr1kkCMI5UgZDhHsBKsAwQ-IGtHGcgeLAsjoeFZDDQfrxcphaRbSBM3WibC_JMhENceYxyzhhoFjDcMaVjJQM9xMYk2C_lgKEZhDO_FJDnBlQBCEhqY1B4u0BmtkF2kXyx8n1elYXPgKU8e-CMssDlJ3Gq2R6maxWSequ4-mXyfvkdzebXLpZUi06YMa3CKFVfAOz5M6Nq-UyL8qhENsrNriJVBjJFRXEE2-FbdTsOLEhER55YE1QgXALPWS0oaavwtASHy-wOSef8H6VZ30nt7VZk4tkfl9-dv71MC4vRcClt215Oi02dJr10mmkP1sv9DJOsnf1YlZDj27z8z2a9rXWOLAA0ForooiV3BiruipmtV0oWwTKu7xYdNSLOI94KJk550xpzozSivcZ3yObEd1tQ-BDwhmKzdNGED1IN4uINMi6tAiYxpfgqNKDNCmNZBiBKZWEMqqMMYL3-TPb9Wc4wB3OPy9OruJ0N-XLhktvNhPJpzioYqaQ7UNN-mDAu7A6VI9CwlsNmlh7cR2xXq4KN2W7K5e5sqi_2ZZAm76Mk0MMwo4j7_O9Gb_FmmlSSqg2ygUCGyVUDOYPw8z2kgdgTYbkQUHgg1ZLxijplJp7EUHCGg1AZikEocELXOXIsrSNqGgg1osIgnxh5BBwCd5MFlIJZS2nHEme7C10x-kFyEN7BmqsWUBEKRAHiRxkbB9iW6pIN_ns5CeMenIK9ICp_XRyOf0n2Hovdh-IxLs7gCNxWXkYkVAkIBL1fclZnGWw9CFZ3MbpfhLxnIiEZnUBcrXEpBCJmyh9-HwyzYuivj6ZrO5dinVkVZq2QJ_9ldCnoaD05UQcB-eSay3ksdCHr5rQmqVGIMUYKV4gHYaZ7dcNOjIh2UXM48JKy9RQbNmIh-pJ1kCFSDW0uyLWgy3d5IqCCS9EPOPQVP0fWzvYSkCsslkSF-tJkVfZbPWMrivQw_JTfttf6dWcbs_88YeThwuxz9Aod_5GZkIOvA-7SmNgEZN6u1wWeTy9H1fJhl72XCBh1VQH9GJjKrTTNwek83oWtf8-o-NlJHl1Fi_jaXsiFCEYgFvBjUImtAwJcS-NXV276X1dGmkTT5FulCgUIxJqHwpAaHVcftVhVcLf-gquCAMZ07xLRI_XQM1i_9qlbqwd4lwLIpjqpCsPZvetne7c0BlFwbdB2LjtLOZvYLtvvgwKJswEjGokA2OoZ0L77e6ZsEJGCfcBAhdRy2hrRV89m7bUE3zUOv8NCXO3otC8-m56-uTqARUP0z6I2DMaEvsdo57i60MpvgG916CAjzj0OB5cYfAC9TEST9vLDCqiDSWpkOKUUr4YPeiaVLAwGyPFafgI9erXdKvTerV7_A88XDWuS7kCBfGleC5EX-HJ7jrKR1fEJzdxlvTltOeD8FfjQODsMMWnWhxjWZs5wCW2chqTRMIv_BKv41k8OCB3aX7w8IhvVwoZvID7C0CCQNd5sb2P58jQrRCFwEYIyBjBWXHVWc_M2mMECF549spSpZW29V15V7B0GeT8jY875XgaZ2-zedoaMiVp3iYK6-83FMMrJ_Y7V8ea7rWZ58N0j7zpZiKsjm2MrLbLCqy_rGAl_vOrHN8ny5_PyQHUBwpTP1dW_UqwpSU2vbYwOc-r29Rd-ArHh8Id2J6z-S39D47uLR24eiNaxq97hArCBgxLf_Cwvi-RbvxkcJ9QkX9x2bWb46WjDMpYs3oC2SjAmi3-qU4JdZanabLC2Pvb5mTEwks_sDvjCyngJSBSnQTSFfM19GQ98za7LLzkoBFlVmmv_Iwx-kXdjrJRF_ZajT-oVaU7Lz8P6XaEtmwEXYmEC6JqDIHK6r5X3XN-CpI3jOOcGS4kXoySXZkBPo23H1y2v9hsI9ZoVYKwphKaXXdWyJ9Mj8sCMbe8b71JDNtOQBVwdAjnhkAIsBc0atYNLI1yiKfsXCvwm75rFNpSdr5wycnZvauyeW-aeFw5aIunldcuye7yYnogG0H4CDNFw9zgQnQdSdhzJOnvjhI8mMkZMnRe38VtzaFfMXNqsPdPM-D_gRlILpl-moHYtHcdOAO2Zwby0BlQSqVSTzOQP34GIErkOaGozZXcIS2vCuxtp0luPM3z5fa1nuztfGBQAJrJpyno5_b7QX0P4_GGhvoaVFtuUDLiLODKSnIGagtuq4kaoJh4sw-UIJxoppRRVh7bo-7nFyQvPz-LlAj1D6YqBvUmqEg2moCUJFr7fgcw0B9Ej6viLp46T-QRso6hyd7XeEiTz10ZJ6mbNYzeJFk_fYIaI1suv_W4R2-RjpnQ5U_9wx2n8bo2wfbT9S2Pp1DST-PbzY8PgRyXioY5oHRpGhen-Wx9nqym-VdXrB_34u3sq0-Cs_4YJIniugag37_v0KcaPp6ySVR7H0_hsnkBwCWyA1FI-Vy97PGURlOSv6uT0lIIL2qFGoJ3Kpq9PkinlIJYdTdoH8L_hs20K5Aww0I6ySPDwIO1MRzRZFAgYTyiITFjnEJlS4Q60qnjDyFmfWvvqQ6R3RB1nsySk19Bi30XRnYYOdtUh456lgZRXnIV3H6Etjy6yaGlIoYo3wJF9le0KFGgLrh2YkAdUg3XVCB50WP9jZKwyANfIVQheXGkGtVXhKEtD0Fdx4uTm_i-r3vzym_RQ9A5jlVDVWw9aVA3ceKcFnFg8aGPc09u2eLVHgw7x8d_XCRltnklwyw32mrh-YMeFu0Ub0Q7pGOGbESl0C-Id6AhpHHTQaHvLDwJUUof-zgOt2Frvb-cMkIxziFJ5aCmTiaajTNMKMqpENZybf7Ho9IBMuEvQJghhteP0wZPL-J3q7p2iE_OPr7-_HH88Mnjvue3t3VT2IOZP0f3lW_JEHA5KjXZejrXUsst883dZV7G_tZJ-J4J7eVOlaV5nCG2QDcJ_zDBt2__BnBTN1dYPAAA```

**Comment by Athanasius** [comment]
Anthor says you should be able to change this to a POST instead of GET to work around the problem.  Talk with him about any specifics I guess.

**Comment by Marginal** [comment]
Thanks. I don't have a loadout that triggers this issue, but a738343 switches to using POST so should hopefully fix it for you.

**Comment by Athanasius** [comment]
Confirmed working (EDMC reported no errors, and EDSM showed an updated coriolis link for the affected ship).
