### ISSUE TITLE
Can not change settings?

### ISSUE THREAD

**Issue by neotropic2023** [Marginal/EDMarketConnector#252]
I installed it and it is telling me my credentials are invalid. So I click File > Settings.

But then it tells me "Not Available while E:D is at main menu."
What?

I see no way to change the settings other than uninstalling and reinstalling. 
I see nothing else I can run that will only open the settings.

Am running Windows 10

**Comment by NoFoolLikeOne** [comment]
Start ED. Get into your spaceship. Eg Join Open or Solo 

Then try changing your settings.

**Comment by Marginal** [comment]
https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#credentials-settings-are-greyed-out
