### ISSUE TITLE
engineers' mods not working

### ISSUE THREAD

**Issue by MrAndyBurns** [Marginal/EDMarketConnector#253]
Hi, cant get engineer mods to transmit to to E:D Shipyard and Coriolis. I've tried running as admin, file locations look okay and have latest build (clean install). DO you have any known issues?

(Windows 10 on iMac, 2.4 Horizons)

**Comment by Marginal** [comment]
Coriolis doesn't yet understand the post-2.4 way of describing engineers' mods.
EDShipyard should work fine.
BTW don't run software as admin - doing so can screw up permissions on files.

What does "not working" look like?

**Comment by MrAndyBurns** [comment]
Hi, your absolutely correct, like to E:D Shipyard opens as expected with all mods being recognized.  Thank you. Coriolis opens with all items and equipment (only checked one ship) but simply no mod data. Also sends correct data to EDSM (i.e. E:D Shipyard has mods Coriolis does not)

Thanks for your help and GREAT tool to work with Elite. 

Would you like me to close?

(PS just used admin rights for testing)
