### ISSUE TITLE
Plugins with a "dot" in the name arent loaded

### ISSUE THREAD

**Issue by NoFoolLikeOne** [Marginal/EDMarketConnector#254]
When installing a plugin. if it has a "dot" in th name EDMC wont load it.

Eg. EDMC-USS-Survey-2.0
produces
RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import

It seems to be losing the 2.0

There is a simple workaround :) Either rename the directory or dont have a dot. 

E:D Market Connector 2.4.4.0 2017-10-15T20:11:12
loading plugin eddb from "C:\Program Files (x86)\EDMarketConnector\plugins\eddb.py"
loading plugin edsm from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
plugin EDMC-Alien-Tour-1.1 disabled
loading plugin EDMC-Screenshot-1.6 from "C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-Screenshot-1.6\load.py"
[..]
Screenshot loaded!
loading plugin EDMC-USS-Survey-2.0 from "C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py"
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:2: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:3: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:4: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:5: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:6: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:7: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:8: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:9: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:10: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:11: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:13: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:14: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:15: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py:16: RuntimeWarning: Parent module 'plugin_EDMC-USS-Survey-2' not found while handling absolute import
Traceback (most recent call last):
File "plug.pyo", line 135, in load_plugins
File "plug.pyo", line 46, in init
File "C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py", line 71, in plugin_start
File "C:\Users\M\AppData\Local\EDMarketConnector\plugins\EDMC-USS-Survey-2.0\load.py", line 32, in get_patrol
File "requests\api.pyo", line 71, in get
File "requests\api.pyo", line 57, in request
File "requests\sessions.pyo", line 475, in request
File "requests\sessions.pyo", line 585, in send
File "requests\adapters.pyo", line 477, in send
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

**Comment by Marginal** [comment]
Python treats the '.' as a hierarchy delimiter - https://docs.python.org/2/library/imp.html?highlight=dots#imp.find_module
The next version of EDMC will replace the '.' with a '_' (which should be transparent to the plugin author unless you're explicitly looking at `__name__`.

**Comment by NoFoolLikeOne** [comment]
Thanks. :)

**Comment by Marginal** [comment]
BTW `SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)` concerns me. Does this warning go away if you work round this loading issue?

**Comment by NoFoolLikeOne** [comment]
No. This appears to be an unrelated issue. My plugin fetches google spreadsheets and writes to google spreadheets. There is an issue for some clients with the SSL authentication. I couldn't understand why it worked for everyone else but not the one guy. 

Googling suggested it might be an issue with SSL and chained certificates. I worked around it but maybe I should tell him to make sure he has his security patches up to date.
