### ISSUE TITLE
Plugin Suggestion: Performing in game actions

### ISSUE THREAD

**Issue by NoFoolLikeOne** [Marginal/EDMarketConnector#255]
I think EDMC would be complete if we had plugins that could react to events and send key presses to the game. Eg Click on a system name and it opens the system map and pastes the system 

I'm fairly sure it can be done with various python libraries but I'm wondering if it would be worth having tighter integration so we can make it a standard thing that can be easilly added to plugin code.

**Comment by Marginal** [comment]
Keypresses are do-able - there's `game_running()` in monitor.py to find the game window and code in hotkey.py to generate key presses.

What's missing is code to expose this functionality to plugins, code to parse the bindings files to find the appropriate key sequence and/or button for each action, code to map from key sequences to virtual keycodes, and code to poke virtual key and button presses at a specific window.

But the main problem for any kind of automation is that there's no way of knowing or changing the game's UI state - e.g. is the game actually at the system menu, on the appropriate tab, and with focus in the search field? So I'm not sure how useful/usable doing this would be.

(Incidentally you can right-click on the system name and choose "Copy", and use Ctrl-V to paste into the System map's search field).

**Comment by NoFoolLikeOne** [comment]
I agree about knowing the UI state. Voice Attack has that same problem but it's still useful

Perhaps I should have a go at coding a plugin and then think about integration later. .

One of my motives is to see if we can lure people away from things like EDDI but then maybe I should really be thinking about how we I get EDDI to supply variables to VoiceAttack and maybe how to generate events from in game key presses.

**Comment by Marginal** [comment]
Available as `dashboard_entry()` since version 3.00.
