### ISSUE TITLE
EDMCOverlay window isn't closed with EDMC

### ISSUE THREAD

**Issue by Rohaq** [Marginal/EDMarketConnector#257]
I'm not sure if this is something the EDMC can handle, but if you have the EDMCOverlay plugin installed, it launches a transparent overlay window with the game - but it isn't closed when you exit the game or EDMC, requiring it to be closed manually.

Could killing the process launched by EDMC be rolled into EDMC itself?

**Comment by Marginal** [comment]
@inorton Could you use the `plugin_stop()` callback (added in EDMC 2.40) to tidy up the EDMCOverlay window?

**Comment by inorton** [comment]
@Marginal yes, that sounds like a good idea, @Rohaq could you report this on the EDMCOverlay issues tracker? - https://github.com/inorton/EDMCOverlay/issues

**Comment by Rohaq** [comment]
Done, thanks!
