### ISSUE TITLE
plugin confusion

### ISSUE THREAD

**Issue by NoFoolLikeOne** [Marginal/EDMarketConnector#258]
Would it be possible to rename the internal plugins directory to something else?

I have a user who I think is getting confused between the internal and external plugin directories.

**Comment by Marginal** [comment]
Could do.
But I would recommend updating your plugins' installation instructions along [these lines](https://github.com/Marginal/EDMarketConnector/wiki/Plugins), which avoids the issue and should be easier for your users all-round.

**Comment by NoFoolLikeOne** [comment]
Perfect. Why did I not notice that before.
