### ISSUE TITLE
it does not update anymore after the CQC update

### ISSUE THREAD

**Issue by gregkotsaftis** [Marginal/EDMarketConnector#26]
Hi, after yesterdays last ED's update the EDMarketConnector cannot update the market data anymore.
It reports "Server is down" although the game runs fine.

**Comment by AnthorNet** [comment]
I'm having the same issue here! But it seems it works for some users based on EDDN stats.

**Comment by gregkotsaftis** [comment]
i do not think it works for them. They might be using the EliteOCR

**Comment by AnthorNet** [comment]
I can assure you thzt it works for some user :)

**Comment by gregkotsaftis** [comment]
How is this possible? The error message says the "Server is down". This does not suggest it is a login issue rather a Frontier library change...

**Comment by AnthorNet** [comment]
Well the exact message returned from the API is that one:
>A server error occured when fetching your profile, please try again.

As you can see here: http://ross.eddb.io/eddn/log
Some messages from EDMC are working well.

**Comment by gregkotsaftis** [comment]
I guess this makes it even harder to debug and fix!
I just hate to go back to EliteOCR.
EDMarketConnector is soooo much better and faster!

**Comment by koreldan** [comment]
i have the same problem... login credentials are correct but server response header was 403

I also tried to change account password... and it correctly gave me bad credential response.

**Comment by Marginal** [comment]
For me it works maybe one time in ten.

The rest of the time EDMC is seeing timeouts or response status 200 including text "A server error occured when fetching your profile, please try again".

I've seen similar issues in the past when the servers are struggling, but not so regularly and not for so long. Hopefully FDev will fix their servers.

**Comment by koreldan** [comment]
Yesterday the updates by EDMarketConnector has been the half of previous days.

3 oct  = 444
4 oct = 506
5 oct = 572
6 oct = 298

probably Frontiers has reduced Companion's server efficency in favour of Download and game servers.

Maybe when the downloading rush will finish also the queries to Companion's server will work as usual

**Comment by Marginal** [comment]
I've [posted a bug report](https://forums.frontier.co.uk/showthread.php?t=188886) about the iOS app not working (more in hope than in expectation).

**Comment by egpd1701** [comment]
The iOS app hasn't been working since before the iOS 9 upgrade.  Not holding out much hope of it being fixed either.  I know this wont help but (and I'm sorry for even writing this as I hate these type of messages), but the app for me says server down.  It was saying the correct error messages yesterday when the update broke all the servers though.

**Comment by Marginal** [comment]
[Release 1.78](https://github.com/Marginal/EDMarketConnector/releases/latest) retries if the Companion server is unresponsive.
In my experience it's the login to the Companion server that tends to fail. If you successfully manage to login, subsequent queries seem to work.

**Comment by egpd1701** [comment]
Just tried 1.77 before hitting the Check for Updates and 1.77 logged in properly.  1.78 logging in OK as well now.  Thanks for the update.

**Comment by AnthorNet** [comment]
It works better now, seems the servers are done with all their migrations ;)

**Comment by Marginal** [comment]
Yep, servers seem to be fixed.

**Comment by gregkotsaftis** [comment]
yes! works for me as well!

**Comment by koreldan** [comment]
it also seems far quicker than before ;)
