### ISSUE TITLE
Installed Latest Large Windows 10  Home  64 bit update

### ISSUE THREAD

**Issue by XCaliber0Elite** [Marginal/EDMarketConnector#260]
Now that I am using the latest large update from microsoft for windows 10. I get an error that says:  "This app requires accurate timestamps. Check your system's Date and Time Settings". When I attempt to run EDMarketConnector.  I can only click a button "ok" to continue and when i do, the program closes.  EDMarketConnector has always worked great for me until this Microsoft update was installed yesterday. 

Thought you might need this info to fix the program asap.  

Thanks.

**Comment by Marginal** [comment]
The app requires that your clock is accurate to within a minute or two. The easiest way to do this is to check "Set time automatically" and maybe "Set time zone automatically" in your system's Date & Time settings.

**Comment by XCaliber0Elite** [comment]
Just tried that and then ran EdMarketConnector and got the same result.
