### ISSUE TITLE
Inara: Cannot login !

### ISSUE THREAD

**Issue by Meridiian** [Marginal/EDMarketConnector#262]
Hi,

Up until the newest update I was having no issues. Now though alongside the Inara section I have a "can't login" message. Even though this was working fine until the update. I don't know if this is an Inara issue, but I thought I would check here first.

I have checked all my login details again to make sure they were correct. Uninstalled and deleted all EDMC files and folders and reinstalled. So far no good. Everything else seems to be OK, Although after the update all my login details had been cleared and the entry boxes were grayed out. The reinstall seems to have fixed that.

**Comment by Wizlon** [comment]
I've had exactly the same happen, figured that I'd check here to see if anyone else was in the same boat.

I checked and the api code for INARA was no longer entered in it's field, I re-entered the api code, exited and restarted, still not able to log in.

So I got a new api and tried again, with the same result, nada.  Uninstalled, reinstalled, entered new api, shut down and restarted, still nada.

**Comment by Marginal** [comment]
If you see “Cannot login !” you should delete or disable MrSheepSheep’s Inara plugin and re-start.

**Comment by Wizlon** [comment]
Ok thanks this fixed it.
