### ISSUE TITLE
Early events in the player journal (e.g. FileHeader and Friends status) are not seen by plugins

### ISSUE THREAD

**Issue by lekeno** [Marginal/EDMarketConnector#264]
Hi,

Would it be possible to have EDMC fire callbacks for early events in the player journal?
In particular:
 - FileHeader before a game is loaded would allow to understand if the plugin was run from the beginning of time.
 - Friends status events before a game is loaded would allow the plugin to build an accurate picture of a player's list of online friends.

Thanks.

**Comment by Marginal** [comment]
Plugins receive these events if the app is running at the time that they're generated. Otherwise, if E:D is already running when the app is started, plugins receive a "[StartUp](https://github.com/Marginal/EDMarketConnector/blob/master/PLUGINS.md#journal-entry)" event instead.

If it's important for your plugin to receive the initial "Friends" event then instruct your users to start the app before starting a game session.

**Comment by lekeno** [comment]
Thanks for the quick reply.

It could be something I did in my plugin but here is what I'm observing in the journal_entry:
 - StartUp event: seen as expected when EDMC is started after ED has started (confirmed with player already in game and on the main menu).
 - However, when EDMC is started before ED, the first event seen by my plugin is "LoadGame". It didn't see the FileHeader and friends events that happened before the loadgame event.

Should I try a really simple plugin and report back?

**Comment by Marginal** [comment]
You're correct - the first event sent to plugins is "LoadGame". I think my rationale for this was that you don't know the Cmdr's name before LoadGame, and prior to 2.4 all the useful information in the Journal before LoadGame was reflected in the `state` dictionary.

I'm unsure what to do about this. I'm not keen to start sending events with `cmdr` and `system` set to None to plugins that might not be expecting it. An alternative solution would be to track Friends in `state` so it will be up-to-date whether the first event your plugin sees is "StartUp" or "LoadGame".

**Comment by lekeno** [comment]
Tracking friends in State would work for my use case. It seems natural to have this information in ```state```

**Comment by Marginal** [comment]
Does the initial `Friends` message ever contain any thing other than "Online" ? i.e. have you seen  "Requested", "Declined", "Added", "Lost" in your Journal files?

**Comment by lekeno** [comment]
Apologies for the late reply, I did a quick check of a few journal players.

The initial batch of friends events (before the load game event), appear to be Status: Online ones. I imagine that it's not impossible to receive other events (definitely offline) during the time it takes for someone to start a new game. The main menu shows a list of online friends which is updated every so and then. I can ask a few friends to remove me while I'm logged out, on the main menu, add me back while I'm logged out, on the main menu.

Re if "Added" implies "Online", I think the answer is yes. There isn't an Online event after an Added event.

Hope this helps.
