### ISSUE TITLE
Avoid spam in Inara financial overview

### ISSUE THREAD

**Issue by MBGTBenjamin** [Marginal/EDMarketConnector#265]
Hi, since the Inara support was added, I don't use the Inara-EDMC-Plugin anymore. However, my Inara Credits tab is full of spamming. Could you please install a mechanism similar to that of the plugin?
https://gitlab.com/mrsheepsheep/EDMC-Inara/issues/5

**Comment by Marginal** [comment]
What do you count as spam?
FYI the plugin currently updates credits on app startup, on ship purchase/sale, and if your credits change by > 5% over the course of a game session.

**Comment by MBGTBenjamin** [comment]
I played around on hour and have 4 Credit updates. If this would keep up You have around 16-20 entries for a four to fice hour session an that is a lot (for me at least). Maybe this was an exception or a bug. I will test it and when it keep up for me (or not) I will either update or close this thread. If I was not right, I want to apologize for this thread.

**Comment by MBGTBenjamin** [comment]
It seems to have been a unique "problem", which is why I have to apologize for the false "alarm". Therefore I close this thread now.

**Comment by Marginal** [comment]
No problem. Let me know if, on further experience, you find it needs changing after all.
