### ISSUE TITLE
Mission Logs not updating

### ISSUE THREAD

**Issue by Jetkar** [Marginal/EDMarketConnector#266]
I have just notice that although flight logs on inara update. It does not update mission or combat logs

**Comment by Marginal** [comment]
Missions don't update immediately, but at the next travel event (Docked, FSDJump, etc).

**Comment by Jetkar** [comment]
I tried what you suggested doesn't seem to work

**Comment by Marginal** [comment]
Did you have the app running when you accepted / completed the mission? The app only knows about mission events that happen while the app is running.

**Comment by Jetkar** [comment]
Ok its working  but delayed as you explained

**Comment by Jetkar** [comment]
EDMC is not collating all the mission data when I board hop between solo/open/private group and complete them. For example I undertook and completed 10 mission last night in this way. EDMC did not update inara when I checked both last night and before I started playing ED. Still no update as I undertook more mission by board hoping today and is failing to update all the missions. I have had to manually update the record. I have posted this comment on Inara discussion

**Comment by Jetkar** [comment]
Ok I carried out further test this morning I took a total of 13 missions 7 in solo, 3 in open play and remainder in solo EDMC/plugin on recorded last 4 mission I collected and completed. According to Api log their were 16 events no warning or errors. I cannot tell if the plugin and or EDMC is at fault. If a player uses EDMC/plugin in one sort of mode of play its great!!

**Comment by Marginal** [comment]
This is fixed in Release [2.47](https://github.com/Marginal/EDMarketConnector/releases/latest).
