### ISSUE TITLE
When setting Always on top its not on top of the game

### ISSUE THREAD

**Issue by martinjh99** [Marginal/EDMarketConnector#267]
Nvidia GTX 750 - Driver Version 338.13

Elite Dangerous latest patch - Steam Version

When playing the game with Always on Top selected the EDMC window does not show in the game.

**Comment by Jetkar** [comment]
Have you tried windowed borderless

**Comment by martinjh99** [comment]
Where are the settings for that?

**Comment by Jetkar** [comment]
At main menu in game under options

**Comment by martinjh99** [comment]
Thanks - Windowed did it.
