### ISSUE TITLE
EDMC not updating modules in EDDN

### ISSUE THREAD

**Issue by omgsetzz** [Marginal/EDMarketConnector#273]
Using EDMC 2.4.7.0

Noted in Ciguri and Na Chem, EDMC window is updating, but does not show in EDDN, e.g. old data is shown in EDDN.

EDMC updates modules in Inara.

Thanks!

**Comment by Marginal** [comment]
I assume you mean eddb, not EDDN, since Inara gets the info from EDMC via EDDN.
eddb was running slowly yesterday.

**Comment by omgsetzz** [comment]
Yes, it is indeed EDDB. Apologies, I blame typing on a fever using fat
fingers.

Thanks for checking - glad it wasn't on your end, love your work!

Regards
Marko
