### ISSUE TITLE
Trouble with e-mail verification.

### ISSUE THREAD

**Issue by JMLCarter** [Marginal/EDMarketConnector#274]
Windows 10 PC.
On execution the Authentication dialogue box displays, indicating a verification code has been sent.
I don't receive the verification e-mail. (of course not in spam folder either)

Been trying for a week or so. ED not at main menu screen.

First day I received one verification e-mail, but the code did not work, the status bar continues to report "Error: Verification failed". 

Is there a way to reset the process, I tried uninstallation/re-installation. Is it significant if the code is executed on different computers?

Scant instructions on this online, so I assume it works for everyone else.

**Comment by Marginal** [comment]
> Is it significant if the code is executed on different computers?

Maybe - the app might be picking up incorrect CMDR details. Check that “E:D journal file location” on the “Configuration” settings tab is pointing at a shared drive from the machine on which E:D is running.

**Comment by JMLCarter** [comment]
It is pointing to "Saved Games\Frontier Developments\Elite Dangerous", which is on the C drive. This folder contains a number of files like "Journal.161029113005.01.log", so it looks like its correct.
Note my steam installation of the game is on D drive.

**Comment by RivaSilvercrown** [comment]
Hi!
I just updated to the latest version of ED market connector and I'm having the same issue... It was working perfectly before the update, but after there's no way of getting the connector to log in correctly.

**Comment by Chilly2001** [comment]
I have just recently downloaded the program and i have the same issue. I have been waiting for an e-mail and i have checked the spam folder as well. I have been waiting for a few hours now. I doubled checked to make sure i put the right e-mail address. please let me know if i missed a step or something. Thank you.

**Comment by Marginal** [comment]
Are you running from Steam. Could it be [this](https://support.frontier.co.uk/kb/faq.php?id=185) issue?
