### ISSUE TITLE
'list' object has no attribute 'itervalues'

### ISSUE THREAD

**Issue by nickfromkew** [Marginal/EDMarketConnector#276]
Landed at Rogers Dock, Tabaldak in my Cutter. EDMC picks up the market prices OK, as I can see they have updated EDDB and it outputs a .csv file to my PC. I have Inara and Ship Loadout options ticked - the ship loadout is output OK too. 
However, there is an error sound when I docked, and the status bar of EDMC shows 'list' object has no attribute 'itervalues'. 
This was playing in Open. Logged out / back in to Solo, same error sound generated. 
Previous few stations had no issue at all. Subsequent stations no issue.

**Comment by Marginal** [comment]
Thanks. Should be fixed in the next release.
