### ISSUE TITLE
Data lost after update

### ISSUE THREAD

**Issue by thestyx** [Marginal/EDMarketConnector#278]
I just updated to a new version: 2.4.8

The email and API key is gone. Please make sure that in future updates those data don't get lost. 

Thanks,

Fly/land safe.

CMDR Steyla

**Comment by thestyx** [comment]
Never mind. I got confused because after the update there was nothing. No Email, no API. After I started ED and went into the game and re-started EDMarketConnector everything was there. Perhaps a short dialog would clear that up.

Thanks,

Fly/land safe.

CMDR Steyla

**Comment by Marginal** [comment]
https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#credentials-settings-are-greyed-out
