### ISSUE TITLE
Automated Update Process Returns 'name'

### ISSUE THREAD

**Issue by JHill29th** [Marginal/EDMarketConnector#279]
After docking at a station and the automatic update initiates sometimes the return in the UI will be `'name'`.

**Comment by Marginal** [comment]
Is there any pattern that you can see? e.g. always happens at certain stations, or with certain cargo?

**Comment by JHill29th** [comment]
No pattern that I can discern. 
[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/1609251/EDMarketConnector.log)

**Comment by Marginal** [comment]
Thanks. Unfortunately there’s nothing relevant in that log.
Please attach `%TMP%\EDMarketConnector.log` after the next time you see this error.

**Comment by JHill29th** [comment]
Sure, will do.  I looked at the log prior to sending it and thought it looked a little sparse ;)
