### ISSUE TITLE
Getting Outfitting without Market

### ISSUE THREAD

**Issue by OchseGit** [Marginal/EDMarketConnector#28]
It seems that outfitting data is not synced if a station has no market.

No Problems at "LHS 3447 - Dalton Gateway" because it has both, "LHS 3447 - Trevithick Dock" only has a outfitting bay and no market.
Tested this with mEDI's Elite Tools and looked after "Pulse Laser - Gimballed - 1G"

![settings](https://cloud.githubusercontent.com/assets/15107867/10457313/0a73cd7c-71c6-11e5-984d-5deeb6428ece.PNG)

**Comment by Marginal** [comment]
Bah it looks like you're right. Will fix in the next release.

BTW, the File location in the dialog above looks weird. Is the displayed path correct?

**Comment by OchseGit** [comment]
Jep its alright :) Got my documents on a seperate harddrive.
And thanks for fixing!

**Comment by Marginal** [comment]
Fixed in Release 1.81.

**Comment by Marginal** [comment]
Really fixed in Release 1.82 :-)
