### ISSUE TITLE
2.4.8 Error EDSM Commander name/API key not Found

### ISSUE THREAD

**Issue by Labanden** [Marginal/EDMarketConnector#280]
![capture](https://user-images.githubusercontent.com/35172615/34641417-b4c53122-f2fb-11e7-9686-92b13dec5c4f.PNG)
![capture1](https://user-images.githubusercontent.com/35172615/34641418-b4deb200-f2fb-11e7-9190-6a627f19e71b.PNG)

The above error is showing when 
using update. I do not have a EDSM account.
Also The ship loadout is not saving

**Comment by Marginal** [comment]
Will be fixed in the the release. In the meantime please use [Release 2.47](https://github.com/Marginal/EDMarketConnector/releases/tag/rel-247).
