### ISSUE TITLE
Problem with Inara plugin

### ISSUE THREAD

**Issue by Hoyland53** [Marginal/EDMarketConnector#282]
Hi,

I installed EDMC a few days ago and it was working fine. I updated to 2.4.8.0 and all was still good. I then tried to install the Inara Plugin, but it did not work correctly.

When EDMC is started with the Plugin active, it gives an error like "Inara: 16:54 Cannot login!". Disabling the plugin makes EDMC work as before.

When the plugin is active, on the settings screen Inara now has two tabs. The first contains the info expected, but the second looks like what I remember from my initial install of EDMC, i.e. it asks for my Inara details. I have checked that these are good, but still I can't get Inara to work.

I suspect I messed something up when installing the plugin. My feeling is that I shouldn't get a second tab - or am I wrong?

I tried uninstalling and re-installing EDMC, but it appears that a lot of my data such as Inara API keys etc survived the uninstall.

If I want a clean uninstall, what stuff should I remove afterwards manually?

I attach screenshots of the "plain" EDMC settings screen and the main and settings screen when the plugin is active.

Can anyone offer any help, please?

BR

Mick

![basic](https://user-images.githubusercontent.com/35174032/34642489-d579082a-f30b-11e7-92d5-2ee1c4b4f941.jpg)
![with plugin](https://user-images.githubusercontent.com/35174032/34642491-d5b8aeb2-f30b-11e7-9c0e-3525da8e83ab.jpg)

**Comment by Marginal** [comment]
Either:
- delete or disable the Inara plugin and use EDMC's built in support for synchronising with Inara, or
- install the [development build](https://gitlab.com/mrsheepsheep/EDMC-Inara/tree/dev) of the Inara plugin.
