### ISSUE TITLE
Retry journal upload after failed attempt

### ISSUE THREAD

**Issue by mooop12** [Marginal/EDMarketConnector#286]
If EDSM is temporarily down, EDMC will not make more attempts to upload the data. In fact, it will stop uploading data altogether until it is restarted. I have to manually upload the journal to EDSM myself. It would be nice if it would attempt multiple times with specified intervals, or just try to upload them along with new jumps as they happen (like a queue).

**Comment by Marginal** [comment]
The app already does this. It remembers data that it couldn't send to EDSM, and while it is left open it will try to send the unsent data whenever it has new data to send - e.g. on a jump. It doesn't remember unsent data across re-starts.
