### ISSUE TITLE
only market updating

### ISSUE THREAD

**Issue by WinneWarrior** [Marginal/EDMarketConnector#287]
Hello I'm having an issue with only market data updating eddn. for some reason it wont up date the faction  data upon docking any ideas as to why?

**Comment by JasonHutton** [comment]
Same issue, not updating ship data or many other things, on Inara.

**Comment by AnthorNet** [comment]
Where do you think it's not updating, EDDN doesn't update anything, apart from feeding listeners.

**Comment by JasonHutton** [comment]
It's honestly probably broken on the Inara end, as EDMC does pull correct info internally, while the update into Inara is what's not going well. Owned ships is a good example, and actually it looks like Inara's journal import feature might be broken currently too, as it pulls old, partial and duplicate info.
