### ISSUE TITLE
Windows Installer won't execute correctly on Windows 10

### ISSUE THREAD

**Issue by ChristianLohmann** [Marginal/EDMarketConnector#29]
Installer seems not to work on Windows 10. It starts up but silently stays at a background task without any GUI. Using Windows' handling of compatibility problems did not help also.

**Comment by ChristianLohmann** [comment]
ok, after a few tries it finally worked ;)

**Comment by SergeySch** [comment]
Hello ChristianLohmann, did you change any settings/etc to start installer? As I have same problem as you had. Install just starts and quit after second, only show progress bar for a moment and then just closes.
