### ISSUE TITLE
Help with py2exe

### ISSUE THREAD

**Issue by muldy** [Marginal/EDMarketConnector#290]
Hi!

I'm trying to add some libs to my EDMC plugin:

"If there are any external dependencies then include them in the plugin's folder."
I know this is done with py2exe or cx_freeze... 

But i usually use them to create .exe files...
help?

Thanks!

**Comment by Marginal** [comment]
I wouldn't recommend using py2exe to cx_freeze in this case.

If the module is pure python then it's usually sufficient to copy some or all of the module from your Python installations site-packages folder into your plugin's folder.

Which module(s) are you depending on?

**Comment by muldy** [comment]
flask and flask-socketio

I'm basically sending the "journal_entry" and "cmdr_data" via socketio

I guess this could be integrated into EDMC...

**Comment by muldy** [comment]
just pushed it:
https://github.com/muldy/MissionReport

**Comment by inorton** [comment]
socketio is quite a big chunk of library code.

An alternative might be to ship your own flask-socketio based exe and to run it as a subprocess from an edmc plugin (and chat to it over a http socket or even stdin?)
