### ISSUE TITLE
EDMC 3.0 install error

### ISSUE THREAD

**Issue by Sisarot** [Marginal/EDMarketConnector#294]
When running the .msi file (using Windows 7) im getting an error during installation as seen in the screenshot
the installer then proceeds to reverse all steps until then and stops completely.
Any idea how to fix?
![error](https://user-images.githubusercontent.com/37052368/36951803-0a07ec36-2008-11e8-8ba4-44b3707410f8.png)

**Comment by Kurgol** [comment]
If I try and install from double clicking the .msi I get this error:
![image](https://user-images.githubusercontent.com/15245142/40888822-de201e24-6754-11e8-8440-7075f84dd918.png)

If I run a command prompt as admin, and then msiexec /a EDMarketConnector_win_305.msi, I get this:
![image](https://user-images.githubusercontent.com/15245142/40888838-180d4774-6755-11e8-8157-f305ba083fd6.png)
followed by:
![image](https://user-images.githubusercontent.com/15245142/40888841-1ff3776a-6755-11e8-8e62-799e275fd2dd.png)
I initially thought this was my antivirus, as I was running edmc fine but after installing a couple of plugins my antivirus went mental which led me to try to reinstall

**Comment by shaftanderson** [comment]
aqui da o erro 2755 n copativel com windows installer 10
