### ISSUE TITLE
Under some circumstances EDMarketConnector.exe process isn't ended

### ISSUE THREAD

**Issue by Hatsushira** [Marginal/EDMarketConnector#295]
After you close Market Connector under some circumstances the process EDMarketConnector.exe isn't ended.
If you try to open it again a process starts but it doesn't show the window. You can open as many as you want. You have to kill the process manually. After that Market Connector works again.
Note: You have to play a while. If you open Market Connector and close it immediately this doesn't happen.

![edmarketconnector](https://user-images.githubusercontent.com/36489280/37037124-e873d81e-2151-11e8-9b58-91ae3161da47.png)

If you kill the process with the biggest size all other processes are killed, too. If you choose to end a smaller process only the chosen one is killed.

**Comment by EleventhOcean** [comment]
Same thing is consistently happening to me as well, and only since 3.00.  I'm using Windows 10.

**Comment by gregmcdougall** [comment]
Here's a dump of a hanging process (i.e. EDMC closed through File>Exit, but process remains). Hope it helps.

**Comment by Stevax** [comment]
My EDMC updated today, ran first time, now doesnt seem to run at all, same issue

**Comment by katzzero** [comment]
Same happening here.

**Comment by Marginal** [comment]
Should be fixed in [release 3.01](https://github.com/Marginal/EDMarketConnector/releases/latest).

**Comment by Xandalis** [comment]
This issue has either persisted or reappeared. The .exe is not ending after exiting the interface.
