### ISSUE TITLE
'list' object has no attribute 'values'

### ISSUE THREAD

**Issue by CMDR-Cometborne** [Marginal/EDMarketConnector#296]
I am getting this error when loading the game while docked at one of the stations being repaired.

Raw data:
[Bhal.Armstrong Enterprise.2018-03-06T21.40.41.json.txt](https://github.com/Marginal/EDMarketConnector/files/1786659/Bhal.Armstrong.Enterprise.2018-03-06T21.40.41.json.txt)

Log file (looks normal)
[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/1786661/EDMarketConnector.log)

**Comment by Marginal** [comment]
Thanks. Will be fixed in he next release.
