### ISSUE TITLE
Error: Inara setCommanderShip, Unknown ship ID.

### ISSUE THREAD

**Issue by b166er** [Marginal/EDMarketConnector#297]
just switching between private groups in game, get the error message in status-line.

![image](https://user-images.githubusercontent.com/679114/37094693-f895115a-2213-11e8-9527-eda18ff08115.png)

Inara, EDDN and EDSM is configured correctly with API keys. i have Windows 10 with E:D Market Connector version 3.0

**Comment by Marginal** [comment]
Should be fixed by a157478 in the next release.
