### ISSUE TITLE
I can't login after update to 3.0

### ISSUE THREAD

**Issue by ond000** [Marginal/EDMarketConnector#300]
Hello,

after update to version 3.0 I can't login to ED via EDMarketConnector, fields in settings are grey, even if game not running and journal files are at right place as you wrote in Troubleshooting section. Would you please help?

Thanks and Regards

**Comment by Marginal** [comment]
https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#credentials-settings-are-greyed-out
