### ISSUE TITLE
Application will not open

### ISSUE THREAD

**Issue by CMDRBurke** [Marginal/EDMarketConnector#302]
Ever since the last update the application will not open.  

I was able to use last version without any issues however now it will not open.

Please help!

**Comment by Marginal** [comment]
Please run task manager, see if there are any zombie v3.00 EDMarketConnector processes hanging around, and if so kill them.
The underlying issue should be fixed in 3.01.

**Comment by sporebat** [comment]
There were no zombie processes visible in Task Manager, but Microsoft SysInternals' `PROCEXP` found it.
