### ISSUE TITLE
engineer modifications are not yet supported

### ISSUE THREAD

**Issue by Dolphin222** [Marginal/EDMarketConnector#306]
* 2B/FS Pack-Hound Missile Rack (Hardpoint #4): DamageType

YOU CAN HELP! Please use the links in the top-right corner to
send me this complete message (including the data below!)
along with screenshots of the "MODIFICATIONS" view for each
affected module in the in-game outfitter. Your contributions are
the only way for me to add support for more modifications. Thanks!
[Fehler ED.docx](https://github.com/Marginal/EDMarketConnector/files/1844820/Fehler.ED.docx)

**Comment by Marginal** [comment]
The message that you quoted comes from EDShipyard.
Please use one of the links in the top right of EDShipyard’s page to report this issue.
