### ISSUE TITLE
Can't upload to EDSM

### ISSUE THREAD

**Issue by Nosttromo** [Marginal/EDMarketConnector#307]
Well, as the title says, I can't login to Elite Dangerous Star Map. Curiously, my info on INARA is up to date. Somehow I can't update my flight log or any other information to EDSM, but only EDSM. My data on EDSM is from a few days ago, it isn't up to date. I haven't been using EDMC for a while, because of that problem, but I wanted to go back using it because i'm using variated resources a bit more like eddb, inara, coriolis and edsm so i'm adressing this issue now. What can I do to make my app update on EDSM? I've already updated the program and reset the API key.

**Comment by AnthorNet** [comment]
I just checked our access logs from yesterday and this morning, and found some records, mostly from an old version of EDDiscovery.

Can you try by only running, EDMC, but also by upgrading EDD to their last version which use our new API. One you have send a request with EDMC and our new API, the old one is blocked, thus any call from EDD was not resolved.

**Comment by Nosttromo** [comment]
Thanks, I updated EDDiscovery and sent the data, then I began using EDMC and it works fine. Thanks!
