### ISSUE TITLE
"Inara addCommaderTravelFSDJump, Unknown ship ID" error

### ISSUE THREAD

**Issue by CMDR-Cometborne** [Marginal/EDMarketConnector#308]
I got the above error after loading the game while in my SRV, and then jumping to another system. ED 3.0.5, EDMC 3.0.1.0

Steps to reproduce:
1. Land on planet
2. Deploy SRV (and dismiss ship)
3. Save&Exit to desktop (main menu might also be enough)
4. Start client again
5. Recall ship, board, and fly into space
6. Jump to another system

Workaround: Save&Exit to desktop and restart client again after being back in your ship.

Journal of the session where the error occured:
[Journal.180329090732.01.log](https://github.com/Marginal/EDMarketConnector/files/1859162/Journal.180329090732.01.log)

Journal of the session where I landed before:
[Journal.180329003034.01.log](https://github.com/Marginal/EDMarketConnector/files/1859185/Journal.180329003034.01.log)

From a quick look, the 'DockSRV' does not say which ship I entered, the earlier touchdown event does not say which ship landed, there is no event for the recall action, and even when I targeted my own ship to see how far away it is, I did not get the ship ID.

The only fix I can see is to have EDMC store the ship information when it gets the "Deploy SRV" event, and then use that to restore the ship information on 'DockSRV'.  Or ask FD for a journal fix, preferably by writing a full loadout event when you enter your ship.

**Comment by Marginal** [comment]
This should now be fixed at Inara’s end. I’m currently traveling and unable to test - please let me know if it’s solved.
