### ISSUE TITLE
Time zone

### ISSUE THREAD

**Issue by DaimonRom** [Marginal/EDMarketConnector#309]
Hi,
yesterday I ran EDMC - no problems there. 
Today I try to start the program, but right after the small window comes up, I get a message saying: "The program needs a correct timestamp. Check the time-zone settings of your systems."
Well - I didn't change anything on my system inbetweeen - to my knowledge. What can I do?
Deinstalling and re-installing doesn't seem to work.
After clicking OK, the program window closes again.
Thanks 
DR

**Comment by Marginal** [comment]
Check your system's Date & Time settings.

**Comment by Easy-Glider** [comment]
I'm having the same problem, I have verified that my Date and Time settings are correct

**Comment by Easy-Glider** [comment]
Okay so it seems like the time sync sever I was getting updates from was having issues, I changed to a different one, Windows in my case, and it's working again
