### ISSUE TITLE
"Not Available While ED is at the Main Menu"

### ISSUE THREAD

**Issue by Arszilla** [Marginal/EDMarketConnector#314]
My info like CMDR name etc wouldn't display so I checked my settings and saw that message. I closed ED, reinstalled EDMC but that info wouldnt go away.

How can I fix this? Never had such an issue.

https://i.imgur.com/YGeizp5.png

**Comment by Marginal** [comment]
https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#credentials-settings-are-greyed-out

**Comment by Arszilla** [comment]
Issue is that I was **NOT** in game.
