### ISSUE TITLE
Timezone Problems?

### ISSUE THREAD

**Issue by starkline** [Marginal/EDMarketConnector#318]
Getting a message stating, "This app requires accurate timestamps. Check your system's Time Zone settings." This occurs during application launch. 

I've attempted to uninstall and reinstall, but the same error persists. I've checked my time and timezone settings, but I haven't changed those in ages, so they're fine as far as I can tell.

O/S: Win7x64

**Comment by Marginal** [comment]
Please check the time zone setting again.
The recent start of daylight savings might have surfaced the problem.

**Comment by unrealization** [comment]
The error also pops up when the system-clock is set to UTC and Windows (in my case Windows 10) is set up to be able to handle this. My Windows clock shows the correct time in my place, but EDMC complains that I should check my timezone settings, despite them, obviously, being correct.
Changing the system-clock to use local time is not an option, as Windows is only my "Playstation-surrogate", with my primary OS being Linux.
Setting Windows to assume the system-clock uses local time will make EDMC work, but that will also show me an inaccurate time in the Windows clock.

**Comment by Marginal** [comment]
@unrealization If your system clock was correct then setting your system's timezone to UTC would not show the time where you live (unless you live on St Helena, the Azores islands, or in West Africa). Set your Window system's timezone to your *actual* timezone.

See [here](https://help.ubuntu.com/community/UbuntuTime#Multiple_Boot_Systems_Time_Conflicts) to properly resolve issues with the hardware real-time-clock and dual-booting.

**Comment by inorton** [comment]
I think the drift checking code should use time.gmtime() to compare instead of time.time()

**Comment by inorton** [comment]
```
# Check system time
        drift = abs(time() - self.eddn.time())
        if drift > DRIFT_THRESHOLD:
```

Or could eddn be reporting UTC which we parse as GMT?

**Comment by Marginal** [comment]
@unrealization Please start a Command Prompt and copy and paste the following in to it:
```cmd
powershell -Command "Get-Date -Format o; [System.Net.WebRequest]::Create('https://eddn.edcd.io:4430/health_check/').GetResponse().Headers.ToString()"
```
Press Enter, copy the result and paste it back here.

@inorton The EDDN server is reporting GMT/UTC in accordance with https://tools.ietf.org/html/rfc7231#section-7.1.1.1 . The app is using `calendar.timegm()` to convert this to a UNIX timestamp for comparison with `time()`.

**Comment by Sniffy75** [comment]
Just chipping in to say that I just started getting this error today, the app worked fine in yesterdays session. 
Nothing has changed that i know of. Going to attempt a reinstall of EDMC.

**Comment by inorton** [comment]
You might get it if your system clock deviates from the server clock by a large amount too

**Comment by inorton** [comment]
@Marginal since we just made a call to EDDN and got it's time, and we know our time at that moment, could we instead add the difference to the messages we submit?

**Comment by Marginal** [comment]
Yeah, this subject is getting old.

Since ED 3.03 the timestamps in the journal are taken from server-synchronised time, not local clock. So the only thing remaining where we still need to ensure accurate timestamps is cAPI-derived data. For this we can get the timestamp from the cAPI server.
