### ISSUE TITLE
Why was the Solo indicator removed?

### ISSUE THREAD

**Issue by PhaserArray** [Marginal/EDMarketConnector#319]
I am referring to the ` / Solo` indicator that appeared after your username while in solo.

It was a pretty useful feature for not just checking what mode you were in at a glance, but it also helped me with board-flipping as it showed the last mode I was in before quitting to the main menu. ([relevant xkcd](https://xkcd.com/1172/))

**Comment by Marginal** [comment]
I had a complaint from streamers who didn't want it obvious whether they were in Solo or Open mode, to discourage ganking. I didn't think the "Solo" feature was so important as to be worth preserving (group _is_ still displayed) and didn't want to add yet another option.

There's a relevant xkcd for _everything_!

**Comment by inorton** [comment]
It would be quite easy to write a little plugin for this

**Comment by PhaserArray** [comment]
@inorton Good idea, [done](https://github.com/PhaserArray/EDMC-Solo-Indicator).

**Comment by PhaserArray** [comment]
Now that there are privacy options, perhaps this feature could be readded with the hide_private_group option also applying to this.
