### ISSUE TITLE
Special Community Goal commodities are skipped

### ISSUE THREAD

**Issue by Marginal** [Marginal/EDMarketConnector#32]
Commodities with special prices due to an ongoing Community Goal at the station are skipped. e.g. prices for some Metals at "Neville Horizons" due to [this](https://community.elitedangerous.com/galnet/uid/5628b4e29657ba887cc6c8a6) goal.

Should EDMC include these prices in its output?
- Pro: They're valid prices that people are interested in.
- Con: Once the Community Goal is complete the commodities may disappear from the station's listing so the inflated prices would only be removed by manual intervention in trading tools databases.

The prices are currently skipped because they hit the special handling put in place to fix Issue #2. The Companion API JSON for such commodities looks like this in E:D 1.3 and 1.4 :
```json
      {
        "baseConsumptionQty": 36.8, 
        "baseCreationQty": 4.6, 
        "buyPrice": 0, 
        "capacity": 408296, 
        "categoryname": "Metals", 
        "consumebuy": "1", 
        "consumptionQty": 46662, 
        "cost_max": 9080, 
        "cost_mean": "8549.00", 
        "cost_min": 8017, 
        "creationQty": 4375, 
        "demand": 408296, 
        "demandBracket": "", 
        "homebuy": "94", 
        "homesell": "93", 
        "id": "128049168", 
        "market_id": null, 
        "meanPrice": 8549, 
        "name": "Beryllium", 
        "parent_id": null, 
        "rare_max_stock": "0", 
        "rare_min_stock": "0", 
        "sellPrice": 9128, 
        "statusFlags": [
          "Community Goal in progress"
        ], 
        "stock": 0, 
        "stockBracket": 0, 
        "targetStock": 16040, 
        "volumescale": "1.0400"
      }, 
```

**Comment by AnthorNet** [comment]
Was thinking about that for some days...
Even if you send them a lot of listeners will reject the line I think if they are not aware about the community goal.

So I'm still wondering what would be the easiest and better solution ...

**Comment by Marginal** [comment]
I've also been wondering what the right thing to do is. I think I'm going to leave this unfixed because:
- There's no automatic solution to the problem of the "special" prices persisting after the CG has ended.
- Part of the "experience" in these kinds of CGs is in finding the commodities at nearby stations. In my subjective opinion automating this would spoil some of the fun.
