### ISSUE TITLE
Help with market connector

### ISSUE THREAD

**Issue by serenity03** [Marginal/EDMarketConnector#320]
Just installed market connector. Not prompting me for a email or password after opening for first time. Went into settings and entered info and nothing happens. The info I enter does not save either. Whats going on.

**Comment by serenity03** [comment]
also, statement in bottom of window reads: Err Check Ed Journal file location. 

Where do I get this file and what location is it supposed to be in.

**Comment by serenity03** [comment]
Its been 7 hours, anyone have a clue why your program isn't working for me?

**Comment by inorton** [comment]
Hi, thanks for your bug report.

Since installing edmc have you logged into your ship?

**Comment by serenity03** [comment]
Yes, I installed it last night and logged in to the game shortly after. I'll try again.

    On ‎Thursday‎, ‎April‎ ‎19‎, ‎2018‎ ‎11‎:‎03‎:‎38‎ ‎AM‎ ‎PDT, Ian Norton <notifications@github.com> wrote:  
 
 
Hi, thanks for your bug report.

Since installing edmc have you logged into your ship?

**Comment by inorton** [comment]
How did you install EDMC, did you use the installer or download the zip from GitHub releases?

**Comment by Marginal** [comment]
@serenity03 Are you running the app on the same machine as the game?

If so, please type `shell:SavedGames` into Explorer's address bar and press Enter. If you get a "Location is not available" error then you have previously deleted the folder where Elite: Dangerous wants to store its journal files. Please create the folder that it's complaining about, restart Elite Dangerous and enter the game, then restart this app.

If you're running this app on a different machine, please adjust the “E:D journal file location” setting on the Configuration tab to point to the game's journal files on the other machine.

**Comment by serenity03** [comment]
Okay I am playing this game on an Xbox one. Is it possible to do that?

**Comment by inorton** [comment]
I'm afraid EDMC only works if you have a PC/Mac Elite Dangerous account.  Using a remote computer involves running Elite on a PC/Mac and sharing the journal folder over SMB/CIFS/NFS to another PC/Mac

**Comment by serenity03** [comment]
I really wish someone would state that on the apps download page before other xbox users spend countless hours trying to make the app work.
