### ISSUE TITLE
Methanol Monohydrate in .prices output.

### ISSUE THREAD

**Issue by Tromador** [Marginal/EDMarketConnector#326]
There's a problem with one of the commodities in .prices output:

EDMC creates a prices file with METHANOL MONOHYDRATE CRYSTALS which is the full name of the commodity, but in the market list and in the EDDB etc feeds, it's simply listed as "Methanol Monohydrate".

This causes an unknown commodity error in TD.

**Comment by Marginal** [comment]
The official in-game name is [Methanol Monohydrate Crystals](https://github.com/EDCD/FDevIDs/blob/master/commodity.csv#L156) in English.
For historical reasons eddb doesn't always use the current official names for commodities. Use TD's corrections mechanism to work around the discrepency.
