### ISSUE TITLE
How to not update a info all planet?

### ISSUE THREAD

**Issue by KingRider** [Marginal/EDMarketConnector#329]
Why just market? i need update a planet discovery and all, not working

Example a system Daibais

eddb list:
https://eddb.io/system/bodies/3968

screenshot:
https://i.imgur.com/X3Cm8Vv.png

**Comment by Marginal** [comment]
To add or update a planet:
- Select "Send system and scan data to the Elite Dangerous Data Network" in this app's settings.
- Fit a Detailed Surface Scanner on your ship.
- Scan the planet. Or, in populated systems, you can scan the Nav Beacon to add/update all planets in the system.

If you have "Delay sending until docked" selected in this app's settings then the planet info will only be sent when you next dock at a station.

**Comment by KingRider** [comment]
I have "Detailed Surface Scanner" .. I disabled it docked, thanks!

**Comment by KingRider** [comment]
my suggestion, please remove all 2 function dock station ... work a fine!

thanks
