### ISSUE TITLE
Run on a separate machine?

### ISSUE THREAD

**Issue by intel352** [Marginal/EDMarketConnector#33]
I'm playing Elite on my Win10 gaming rig, but have a Macbook Pro laptop next to me. Can I run this app on the Mac, to track my data from there, instead of from the gaming rig itself? Would be handy to be able to interact with the app and have it in full view, rather than having to multitask on the gaming rig.

I understand if it needs local game assets, but if it's simply using ED server APIs, then it seems it could run on a separate rig.

**Comment by cmmcleod** [comment]
Yup, you just need to install the Mac version.

I just uses the companion API, so technically someone on the other side of the planet could log in as you and use it (without ever having E:D installed either...)

**Comment by intel352** [comment]
Perfect, thanks!
