### ISSUE TITLE
Error sound and message 'Value'

### ISSUE THREAD

**Issue by CMDR-Cometborne** [Marginal/EDMarketConnector#330]
For some time, I have been getting the error pling together with the 'Value' (including the quotes), especially in stations.  This looks to be connected to the INARA updater as I am getting the error when only this is active and all other plugins and send options are disabled.  When I disable the Inara integration, the message goes away.  I am also seeing reports about one soft error in my API log page on INARA, unfortunately with no details.  If you and Artie want to check the INARA side logs, try June 14th at 18:03, 18:05, 18:09, 18:10, 18:11, 18:25 (all times in UTC).

I've attached the Raw Status save, any further logs I can provide?
[Barnard's Star.Miller Depot.2018-06-15T07.21.15.json.txt](https://github.com/Marginal/EDMarketConnector/files/2104910/Barnard.s.Star.Miller.Depot.2018-06-15T07.21.15.json.txt)

**Comment by CMDR-Cometborne** [comment]
I also noticed that the module etc. of my current ship are not updated.  Just enabled sharing my details, ship can be found at https://inara.cz/cmdr-fleet/23188/287487/ and was last updated by a manual journal import.

**Comment by Marginal** [comment]
Next time you see this error please zip up and attach the file %TMP%\EDMarketConnector.log .

**Comment by CMDR-Cometborne** [comment]
Happens immediately on game start, here is the zipped EDMC log:

[EDMarketConnector.log.zip](https://github.com/Marginal/EDMarketConnector/files/2106804/EDMarketConnector.log.zip)

And since it looks to be related to parsing the loadout event in the journal:
[Journal.180615182726.01.zip](https://github.com/Marginal/EDMarketConnector/files/2106809/Journal.180615182726.01.zip)

**Comment by Marginal** [comment]
Thanks. Will be fixed in the next release.

**Comment by CMDR-Cometborne** [comment]
Thank you, awesome service.

Jonathan Harris <notifications@github.com> schrieb am Fr., 15. Juni 2018,
23:49:
