### ISSUE TITLE
MSI installer shlould not auto-run on completion

### ISSUE THREAD

**Issue by Taomyn** [Marginal/EDMarketConnector#334]
Please but the MSI installer should not auto-run the application on completion without my consent, this is extremely bad behaviour in my book.

**Comment by Marginal** [comment]
It is possible to install without launching from the command line with
```cmd
msiexec /i "X:\path\to\EDMarketConnector_win_NNN.msi" LAUNCH=no
```
This behaviour used to be the default but people complained that the installer didn't work, e.g. #29, #244.

**Comment by Taomyn** [comment]
But that has nothing to do with auto-running, the instant closing down is a symptom of an installer not being accepted by the newer OSes as trusted, and your MSI is not signed.

I have the same issue with other installers on one of my servers, and I have to remember to right-click the file and tell Windows to trust it. This happens when UAC is not set to "Always prompt" thus people do not see the warning from Windows and it appears to simply run then stop immediately.

![image](https://user-images.githubusercontent.com/4365929/42723654-53296d42-8762-11e8-9d2d-964dab9b95a2.png)

![image](https://user-images.githubusercontent.com/4365929/42723657-5c69172c-8762-11e8-8d61-118d978cd4a1.png)
