### ISSUE TITLE
Link from "Ship: " field opens blank browser window

### ISSUE THREAD

**Issue by randrews01** [Marginal/EDMarketConnector#335]
Hi,

I used to be able to click the shipname and it would open in EDSY or CORL just fine.  Instead, it now just opens a browser with a blank window when I click my shipname.  I've tried uninstalling and reinstalling.

Logs below
E:D Market Connector 3.1.0.0 2018-07-13T11:19:44
loading plugin coriolis from "C:\Program Files (x86)\EDMarketConnector\plugins\coriolis.py"
loading plugin eddb from "C:\Program Files (x86)\EDMarketConnector\plugins\eddb.py"
loading plugin edsm from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
loading plugin edsy from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
loading plugin inara from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"

**Comment by Marginal** [comment]
Don't know why the browser isn't picking this up.
Which browser?
Please try closing all browser windows and try again.

**Comment by randrews01** [comment]
Tried multiple browsers.  Restarted.  Did all the usual tricks.  No URI string appears in the navigation bar for the browser.   So it seems that the URI string isn't passed over correctly for some odd reason.

**Comment by randrews01** [comment]
On a hunch, I toggled my default browsers in WIndows to a different one and then back again.  Now it's working.  <Shrugs>

**Comment by Marginal** [comment]
Interesting. For future reference - what is your default browser set to?
