### ISSUE TITLE
Link Ship: to Coriolis leaves off scanners.

### ISSUE THREAD

**Issue by Alshain01** [Marginal/EDMarketConnector#336]
I click the name of my ship and everything opens exactly as it should, but the scanners that are definitely in my Anaconda's slots do not load in.

**Comment by Marginal** [comment]
Please report this issue over at https://github.com/EDCD/coriolis

It will be helpful for them if you attach a dump of your ship's loadout. To do this choose "Ship loadout" on the "Output" tab in this app's settings, press "Update" and attach the file that is generated to the new Issue that you create.
