### ISSUE TITLE
EDMC does not launch, not log file in User\Temp

### ISSUE THREAD

**Issue by Queex** [Marginal/EDMarketConnector#338]
On a fresh windows 7 install, a freshly-installed EDMarketConnector does not launch. It does not last long enough to even appear in the Task Manager.

When not run as an administrator, nothing happens, not even the log files in the User Temp folder. When run as an adminstrator, it does produce a log file in the executable folder, attached.

`
Traceback (most recent call last):
  File "EDMarketConnector.py", line 6, in <module>
ImportError: No module named collections
`

Is EDMC meant to have python as a prerequisite? It's not mentioned anywhere in the install instructions, if that's the case.

**Comment by Marginal** [comment]
Your installation is incomplete. Check that your AV software isn't being too enthusiastic.
Either re-installm or "Repair" from within Control Panel.

**Comment by Queex** [comment]
That seems to have fixed it. Very strange,though: my AV doesn't do live scans and I'd tried re-installing it from the installer more than once.

**Comment by Marginal** [comment]
Weird. Glad it's working now.
