### ISSUE TITLE
EDSM not working (on MacOS)

### ISSUE THREAD

**Issue by alvar-freude** [Marginal/EDMarketConnector#340]
On MacOS, there is a wrong plugin directory in the settings (E:D Market Connector Version 3.1.2.0); the build-in plugins are located under `/Applications/EDMarketConnector.app/Contents/Library/plugins` (or any other installation directory), but in the settings there is `~/Library/Application Support/EDMarketConnector/plugins` (in the users home directory).

In the GUI settings, it is not possible to change the plugin dir.

Maybe a reason is, that this setting comes from an older version? IMHO the internal directory for build-in plugins should be added always, so the setting should only add another directory and should add always the internal with build-in plugins. (Maybe this is intended and there is a bug, calculating the internal directory on MacOS?)

I found this, because there were no new route updates on EDSM – and it's some time ago I played last time … ;-)

**Comment by alvar-freude** [comment]
OK, seems reasonable!
Sorry, I guessed that the plugins dir was wrong, because EDSM not working. So, my guess was wrong … 
Maybe there is another reason, that EDSM is not working? Is there a visible list of loaded plugins or a debug log?

As far as I remember there should be a EDSM tab in the settings? I have none. And in the Tab „Konfiguration“ (German, configuration obviously ;) ) in the websites I have „EDSM“ selected, but in the dropdown EDSM is missing. So, it looks like the EDSM plugin fails, is not loaded or something similar.

**Comment by alvar-freude** [comment]
(I changed the title according to my last comment)

**Comment by Marginal** [comment]
Fixed. Please choose E:D Market Connector -> Check for Updates...

**Comment by alvar-freude** [comment]
Bug is fixed, thank you! :-)
