### ISSUE TITLE
Materials not updating on Imara after Material trader

### ISSUE THREAD

**Issue by pargyrak** [Marginal/EDMarketConnector#344]
I have noticed this a couple of times already. I went to a Raw material trader and traded Ruthenium for Arsenic, Cadmium and Tellurium.

After I went to a Manufactured materials trader and made some other trades. The trades on the manufactured one where updated in Inara while the one for the Raw not even after several docks, jumps etc. Perhaps one log was ignored? I checked with Artie at Inara and suggested to post there!

Thanks for the great job!

**Comment by Marginal** [comment]
Please attach the Journal file that covers this time period.
