### ISSUE TITLE
Type 9 optional internal not importing correctly into coriolis.io 

### ISSUE THREAD

**Issue by teamcba** [Marginal/EDMarketConnector#345]
Firstly, thanks for all the great work.

My type 9 has the following
8-8E CARGO RACK
8-8E CARGO RACK
7-7E CARGO RACK
6-6E CARGO RACK
5-5A SHIELD
4-4E CARGO RACK
4-4E CARGO RACK
3-3E CARGO RACK
3-3E CARGO RACK
2-1E DOCKING

When imported into coriolis.io it becomes

8-8E CARGO RACK
8-7E CARGO RACK
7-6E CARGO RACK
6-5A SHIELD
5-4E CARGO RACK
4-4E CARGO RACK
4-3E CARGO RACK
3-3E CARGO RACK
3-EMPTY
2-EMPTY

So it lost 8E rack and the docking computer during import.

Cheers

**Comment by Marginal** [comment]
Please report this issue over at https://github.com/EDCD/coriolis

It will be helpful for them if you attach a dump of your ship's loadout. To do this choose "Ship loadout" on the "Output" tab in this app's settings, press "Update" and attach the file that is generated to the new Issue that you create.
