### ISSUE TITLE
Cannot choose installation location

### ISSUE THREAD

**Issue by draeath** [Marginal/EDMarketConnector#346]
I was running into problems installing the update from 2.x to 3.x - when I would relaunch EDMC, the old version would run.

It turns out the update installed itself to Program Files (x86) with no choice offered to me in the matter. This was not where I had the prior version installed, either.

I would suggest adjusting the installer to allow installation of EDMC to custom locations, as has been a common practice since before Windows even existed. Beyond customizability, this offers the user the ability to install to a location that does not need UAC escalation to manage.

**Comment by Marginal** [comment]
https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#installing-on-a-different-drive
