### ISSUE TITLE
Journal file location (MacOS)

### ISSUE THREAD

**Issue by Skarafaz** [Marginal/EDMarketConnector#347]
Hi! How do I change the location of journal files in mac version? The configuration tab does not contain this option. Thanks

**Comment by Marginal** [comment]
This option is not available on the macOS version of the app; I have found reading the Journal file on a Mac over SMB from a PC to be unreliable. I may re-instate the option in the future if I can get it working reliably.

**Comment by Skarafaz** [comment]
Ok! Thanks.

**Comment by Marginal** [comment]
Fixed in 3.20.
