### ISSUE TITLE
Update on 420,000 second cooldown

### ISSUE THREAD

**Issue by MoistAccident** [Marginal/EDMarketConnector#349]
My EDMC using USS Survey plugin is on a 420,000 second cooldown. Closing did not fix. Uninstall and clearing all files, followed by a fresh download and install did not fix the issue. Everything is up to date.
![edmc](https://user-images.githubusercontent.com/43700046/46245211-f4cde100-c385-11e8-96a5-971fc7e653ab.PNG)

**Comment by Marginal** [comment]
I've documented a fix for this [here](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#very-long-cooldown-period)
