### ISSUE TITLE
Track star system, regardless of no station

### ISSUE THREAD

**Issue by intel352** [Marginal/EDMarketConnector#35]
Based on the interface messaging, it appears if I'm not docked at a station, then the app bails out from communicating my location. I want to log my history regardless of being at a station, so I can stay aware of cool (uninhabited) star systems in my log. Is my assessment correct that no station results in no log at all?

If that's the case, then can we get the update process to still run for the star map log, regardless of station?

**Comment by Marginal** [comment]
The "You're not docked at a station!" message occurs when you've selected the option to save EDDN and/or local market data. But an entry is made in the local and/or EDSM flight log whether or not you're docked at a station.

The next release will have an option to automatically make flight log entries on visiting a system, without having to press "Update".

**Comment by intel352** [comment]
Awesome. What about the cooldown?

**Comment by Marginal** [comment]
Release 1.84 adds the option to automatically make a flight log entry on visiting a system.

The cooldown doesn't apply since this works by monitoring your client's netLog file (like EliteOCR does) rather than via the Companion API.
