### ISSUE TITLE
non-ASCII characters in Commander Name -> no update on EDDB

### ISSUE THREAD

**Issue by nbassler** [Marginal/EDMarketConnector#354]
It seems that if there are non-ASCII characters in the commander name, then EDDB apparently refuses to accept the update. ross.eddb.io shows nothing in the log. No error messages are seen anywhere.

Selecting "Pseudo-anonymized ID" from the settings menu resolves the issue, and updates are then propagated.

Not sure if this is an EDMC or EDDB issue.

**Comment by Marginal** [comment]
This should now be fixed in EDDN - https://github.com/EDSM-NET/EDDN/commit/9484f4646a6fcedac7bec79e659926fe95f6bec0
