### ISSUE TITLE
Error when running from source

### ISSUE THREAD

**Issue by intel352** [Marginal/EDMarketConnector#36]
(On OSX) I've cloned the repo, installed Python 2.7 via brew, installed requests, updated activetcl, etc. When I attempt to run EDMarketConnector.py, I get the following error:

```
Traceback (most recent call last):
  File "./EDMarketConnector.py", line 411, in <module>
    app = AppWindow(root)
  File "./EDMarketConnector.py", line 170, in __init__
    hotkeymgr.register(self.w, config.getint('hotkey_code'), config.getint('hotkey_mods'))
  File "/Users/jlangevin/repos/EDMarketConnector/hotkey.py", line 69, in register
    self.tkProcessKeyEvent_old = NSApplication.sharedApplication().methodForSelector_(sel)
AttributeError: No selector tkProcessKeyEvent:
```

Any suggestions?

**Comment by Marginal** [comment]
It's designed to be run with the built-in Python, Tcl/Tk etc on OSX.
Try [running with](https://github.com/Marginal/EDMarketConnector#running-from-source) `./EDMarketConnector.py`

**Comment by intel352** [comment]
I was getting this error prior to installing activetcl, and installing it didn't change the error. So if anything, I'm betting it's more related to me using Python installed via brew. I'll try w/ the vanilla Python install.

**Comment by Marginal** [comment]
If you've overwritten /usr/bin/python with the Homebrew Python, then you can invoke the built-in Python with `python2.7 EDMarketConnector.py` or, if you've overwritten that too, with `/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python EDMarketConnector.py`

**Comment by intel352** [comment]
I didn't replace Python directly, I only updated the .py scripts to reference the /usr/local/bin/python executable instead.

Reverting that, and removing my change that disabled the hotkey logic, allows me to run the app without any error. It would be nice to be able to get this working without having to rely on system-version binaries, but it's working now so that'll suffice.

Thanks!

**Comment by Marginal** [comment]
>  I only updated the .py scripts to reference the /usr/local/bin/python executable instead.

And you didn't think to mention this in your original post?

> It would be nice to be able to get this working without having to rely on system-version binaries

Why? But if it bothers you then I'll welcome a patch that detects your versions of Python and/or Tcl/Tk and does the right thing.

**Comment by intel352** [comment]
Sorry for not being more clear previously, felt I'd implied that when I mentioned I installed python via brew, but I can see that would be misleading due to how the .py was executed.

Re: avoiding reliance on system-version binaries, OSes don't always keep their software packages up to date, so it's nice to be able to use a package manager. Guess I'm personally just more inclined to installing explicit library versions, such as is done with PHP (Composer), NodeJS (npm), Ruby (gem).

**Comment by Marginal** [comment]
I'd happy to re-open if you can provide a reason why it's important that this program should work when modified to use a non-default version of Python.
