### ISSUE TITLE
No commodity data and no outfitting data

### ISSUE THREAD

**Issue by Erdega** [Marginal/EDMarketConnector#365]
The market connector seems not to send "outfitting/2"-"Outfitting" data and no "commodity/3"-"Commodity" data. The only messages sent by the market connector seem to be "journal/1"-"Journal / Docked" events. At least what I see on EDDB-ROSS.

E.g. check EDDB-ROSS-DB for Galileo station in Sol: https://ross.eddb.io/station/update/19

Before 11 Dec 2018 EDMC 3.2.0.0 successfully sent those data. After the patch date no outfitting and no commodities are visible in EDDB-ROSS.

**Comment by Erdega** [comment]
Additional info: When I look directly into data comming from EDDN:
EDDiscovery and EliteLogAgent are sending data for schemas "outfitting/2" and "commdity/3".

**Comment by Erdega** [comment]
May I ask duplicate to what? This issue is independant of the Frontier API - issue. Commodity data is available but not sent since 11 Dec 2018

**Comment by AnthorNet** [comment]
Not from the cAPI, the mentioned software use the local file to send them.
