### ISSUE TITLE
How can I reset starting position on screen, or bring the program back to current screen?

### ISSUE THREAD

**Issue by rcthelp** [Marginal/EDMarketConnector#37]
I've change my default display so now when I start EDMArketConnector it starts up on a 'virtual' screen and I cannot get it back to display on my monitor.

anyway to resolve this without reinstalling please? Registry setting, config file, ???

**Comment by Marginal** [comment]
- Quit the program if you have it running
- Delete the registry key HKEY_CURRENT_USER\Software\Marginal\EDMarketConnector\geometry

**Comment by rcthelp** [comment]
Excellent thanks. No idea why I didn't find the registry keys. Must have mistyped EDMarketConnector in the search dialog.
