### ISSUE TITLE
No way to remove fdev auth for fresh setup

### ISSUE THREAD

**Issue by kaivalagi** [Marginal/EDMarketConnector#370]
You seem to have added webpage based auth for the fdev api in the most recent release, although this works fine, having 2 accounts I found myself authorising with the wrong account for the session edmc was running for at that time and so had the wrong api key generated against that account. To address this I went into the registry and emptied the fdev key entry so edmc re-authed for both commanders again. Now it's fixed...maybe it would be a good idea to have a commander re-auth option where keys are removed? Just a thought....

Keep up the great work

**Comment by Marginal** [comment]
The app detects when the Cmdr returned in cAPI data doesn’t match the Cmdr from the Journal. The app should automatically re-auth in this case.

**Comment by kaivalagi** [comment]
Oh okay, so if I had triggered an event in game it would have needed auth and spawned a web page for it? Good to know, thanks. the only reason I knew it mis-matched was by running a status request and seeing the wrong commander details. I triggered re-auth after deleting after key then closing and opening the app but I needn't have bothered :) It's all good now regardless...thanks for the app
