### ISSUE TITLE
Log in issue

### ISSUE THREAD

**Issue by ice-ivanov** [Marginal/EDMarketConnector#373]
Every time I launch the game, EDMC reconnects to frontier servers and requires me to manually log in. Sometimes it works, sometimes it doesn't so I have to restart EDMC for another attempt.
This only started happening with 3.3.1. Was working fine on 3.3.0.
If there is any technical information I can share, I'd be glad to.

**Comment by Marginal** [comment]
After the next failure please zip up and attach the file `%TMP%\EDMarketConnector.log`.
Do you see any error messages in the app or on the Frontier authentication website?

**Comment by ice-ivanov** [comment]
Here it is. There are multiple 402 errors.

**Comment by ice-ivanov** [comment]
Sorry. For some reason my browser won't upload it. I hope it isn't too bad if I just post log text here.

E:D Market Connector 3.3.1.0 2018-12-30T22:07:10
loading plugin coriolis from "C:\Program Files (x86)\EDMarketConnector\plugins\coriolis.py"
loading plugin eddb from "C:\Program Files (x86)\EDMarketConnector\plugins\eddb.py"
loading plugin eddn from "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py"
loading plugin edsm from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
loading plugin edsy from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
loading plugin inara from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"
EDSM	402 Item unknown	{"StarType": "M","ScanType": "AutoScan","BodyName": "Gru Eork QQ-Y b20-0","_stationName": null,"timestamp": "2018-12-30T19:07:24Z","RotationPeriod": 131332.4375,"BodyID": 0,"_systemName": "Gru Eork QQ-Y b20-0","StellarMass": 0.261719,"_systemCoordinates": [3466.4375,-99.46875,3227.125],"Radius": 323171488.0,"AbsoluteMagnitude": 10.019104,"Luminosity": "Va","_shipId": 10,"AxialTilt": 0.0,"Age_MY": 11820,"event": "Scan","DistanceFromArrivalLS": 0.0,"SurfaceTemperature": 2567.0}
EDSM	402 Item unknown	{"Periapsis": 210.841125,"_systemCoordinates": [3426.84375,-77.78125,3184.90625],"BodyName": "Gru Eork DC-O c9-1 B","SemiMajorAxis": 3639970048.0,"timestamp": "2018-12-30T19:08:41Z","_systemName": "Gru Eork DC-O c9-1","StellarMass": 0.21875,"OrbitalInclination": -13.321571,"Parents": [{"Null": 1},{"Null": 0}],"AxialTilt": 0.0,"Age_MY": 9984,"event": "Scan","ScanType": "AutoScan","_stationName": null,"RotationPeriod": 111091.984375,"BodyID": 3,"StarType": "M","OrbitalPeriod": 186498.75,"Radius": 281804000.0,"AbsoluteMagnitude": 11.113022,"Luminosity": "VI","Eccentricity": 0.124925,"_shipId": 10,"DistanceFromArrivalLS": 16.484865,"SurfaceTemperature": 2137.0}
EDSM	402 Item unknown	{"Periapsis": 30.841143,"_systemCoordinates": [3426.84375,-77.78125,3184.90625],"BodyName": "Gru Eork DC-O c9-1 A","SemiMajorAxis": 1126178560.0,"timestamp": "2018-12-30T19:08:41Z","_systemName": "Gru Eork DC-O c9-1","StellarMass": 0.707031,"OrbitalInclination": -13.321571,"Parents": [{"Null": 1},{"Null": 0}],"AxialTilt": 0.0,"Age_MY": 9984,"event": "Scan","ScanType": "AutoScan","_stationName": null,"RotationPeriod": 305054.59375,"BodyID": 2,"StarType": "K","OrbitalPeriod": 186498.75,"Radius": 613062144.0,"AbsoluteMagnitude": 6.365311,"Luminosity": "Va","Eccentricity": 0.124925,"_shipId": 10,"DistanceFromArrivalLS": 0.0,"SurfaceTemperature": 4322.0}
EDSM	402 Item unknown	{"Periapsis": 11.610092,"_systemCoordinates": [3426.84375,-77.78125,3184.90625],"BodyName": "Gru Eork DC-O c9-1 C","SemiMajorAxis": 786195264.0,"timestamp": "2018-12-30T19:08:48Z","_systemName": "Gru Eork DC-O c9-1","StellarMass": 0.359375,"OrbitalInclination": -63.807949,"Parents": [{"Null": 4},{"Null": 0}],"AxialTilt": 0.0,"Age_MY": 9984,"event": "Scan","ScanType": "AutoScan","_stationName": null,"RotationPeriod": 196789.03125,"BodyID": 5,"StarType": "M","OrbitalPeriod": 126833.351563,"Radius": 367001024.0,"AbsoluteMagnitude": 8.629425,"Luminosity": "Va","Eccentricity": 0.055906,"_shipId": 10,"DistanceFromArrivalLS": 556.730591,"SurfaceTemperature": 3317.0}
EDSM	402 Item unknown	{"Periapsis": 191.610077,"_systemCoordinates": [3426.84375,-77.78125,3184.90625],"BodyName": "Gru Eork DC-O c9-1 D","SemiMajorAxis": 2191818240.0,"timestamp": "2018-12-30T19:08:48Z","_systemName": "Gru Eork DC-O c9-1","StellarMass": 0.128906,"OrbitalInclination": -63.807949,"Parents": [{"Null": 4},{"Null": 0}],"AxialTilt": 0.0,"Age_MY": 9984,"event": "Scan","ScanType": "AutoScan","_stationName": null,"RotationPeriod": 100981.9375,"BodyID": 6,"StarType": "L","OrbitalPeriod": 126833.351563,"Radius": 192234592.0,"AbsoluteMagnitude": 13.136337,"Luminosity": "V","Eccentricity": 0.055906,"_shipId": 10,"DistanceFromArrivalLS": 564.043457,"SurfaceTemperature": 1624.0}

**Comment by ice-ivanov** [comment]
Unless 402 is an error, I don't see anything suspicious here.
EDSM works fine overall, just asking me to log in every time I start the game.

**Comment by AnthorNet** [comment]
402 item unknown means you have the setting wait for docking ticked on EDSM.
Your scan will wait for the body to be inserted by EDDN, and link it laterto your profile.

This is not related to the Frontier Auth Service.

**Comment by ice-ivanov** [comment]
As I thought. So I guess it doesn't track login process. Anything else I can provide to help?

**Comment by ice-ivanov** [comment]
This is getting weird and honestly I'm afraid for my account safety.
Whenever I launch EDMC, it redirects me to a frontier login page, I try to log in with my Steam account (like I always do). But then I get 2 prompts for EDMC to use this login. After I grant it permission, it says "invalid credentials" in the application window, even though I am able to log into both my steam and frontier accounts. Happens every time I launch EDMC or if I launch the game while EDMC is running.

**Comment by AnthorNet** [comment]
Did you click the steam button, or use directly the frontier form?

**Comment by ice-ivanov** [comment]
I have tried both options.

**Comment by ice-ivanov** [comment]
Thanks. The issue is gone now =)
Happy new year, guys!

**Comment by Marginal** [comment]
:-)
