### ISSUE TITLE
Freezing on "Fetching data" after updating to 3.32

### ISSUE THREAD

**Issue by jimbot70** [Marginal/EDMarketConnector#376]
After logging into the new API EDMC will instantly freeze up every time it starts "fetching data" and sit there until I force quit the program.  I have done a full reinstall including deleting the config in the registry and it still locks up after logging in but if I do not log in it does not freeze up.

-edit Found what seems to be causing it.  If you have the game through Steam and use your Steam account to sign into the Frontier API it causes this freezing.  I signed in to my Frontier account itself instead of going through the Steam link on the sign in page and it works fine without freezing.

**Comment by Marginal** [comment]
Did you originally buy the game from Frontier and later link it to your Steam account, or did you buy it  from Steam?

**Comment by jimbot70** [comment]
Bought on Steam originally.

**Comment by raziel83** [comment]
how do you sign on with out using the steam account?

**Comment by jimbot70** [comment]
You had to make a Frontier account when you first bought the game even through Steam.  Just use that account.

**Comment by zaredman** [comment]
I bought mine originally on steam & ended up having to make a Frontier account way back when.
