### ISSUE TITLE
EDmarketconnector not authenticating on first load up

### ISSUE THREAD

**Issue by SyotosViking** [Marginal/EDMarketConnector#377]
I've attempted a fresh install but when I open EDmarketconnector it brings up the ED website for login, I click on steam, give permission through steam, approve and EDmarketconnector doesn't connect. Says loggin in...

If I click on status it says Error: Invalid Credentials. I've double checked my login info as well as I do play through steam and it doesn't allow me to connect.

Any advice/assistance appreciated.

Update** After a reboot it has logged in, and I also found it freezing as another poster commented. I also followed his advice and logged in with my FD credentials instead of Steam and I am no longer freezing.

**Comment by Marginal** [comment]
Did you originally buy the game from Frontier and later link it to your Steam account, or did you buy it  from Steam?
