### ISSUE TITLE
332 hung PC

### ISSUE THREAD

**Issue by jagsj01** [Marginal/EDMarketConnector#378]
attempted the install of 332 but PC hung (was in ED at time).
Found that ED market connector failed to install correctly.  Now 331 doesn't work either.

Currently unable to install 332 as it asks for the msi for 331, which is not on my PC (??)

Unable to uninstall .331 as again it wants msi for 331.  Simple fix is for me to have a copy of 331 but I can find past versions on Git.  Bit stuck, help appreciated

Cheers
 B

**Comment by Marginal** [comment]
Previous releases are [here](https://github.com/Marginal/EDMarketConnector/releases)
