### ISSUE TITLE
Error: Invalid credentials 

### ISSUE THREAD

**Issue by jagsj01** [Marginal/EDMarketConnector#379]
With 332 I am currently getting the invalid credentials error in the connector and my browser opens a window for the Frontier validation and presents the following:

Fatal error: Uncaught Predis\Response\ServerException: OOM command not allowed when used memory > 'maxmemory'. in /var/www/html/vendor/predis/predis/src/Client.php:370 Stack trace: #0 /var/www/html/vendor/predis/predis/src/Client.php(335): Predis\Client->onErrorResponse(Object(Predis\Command\StringSet), Object(Predis\Response\Error)) #1 /var/www/html/vendor/predis/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\StringSet)) #2 /var/www/html/vendor/snc/redis-bundle/Session/Storage/Handler/RedisSessionHandler.php(138): Predis\Client->__call('set', Array) #3 /var/www/html/vendor/snc/redis-bundle/Session/Storage/Handler/RedisSessionHandler.php(146): Snc\RedisBundle\Session\Storage\Handler\RedisSessionHandler->Snc\RedisBundle\Session\Storage\Handler\{closure}(Object(Predis\Client), 'sessiond8d7166f...', '5c2d85b96aaca', 30001) #4 /var/www/html/vendor/snc/redis-bundle/Session/Storage/Handler/RedisSessionHandler.php(205): Snc\RedisBundle\Session\Storage\Handler\RedisSessionHandler->lockSession('d8d in /var/www/html/src/AuthBundle/Resources/views/base.html.twig on line 24

I have uninstalled and reinstalled 332, logged back into Frontier, started ED through to ship cockpit with no improvement.
Let ,me know if further information is required.  

Cheers

**Comment by AnthorNet** [comment]
The Frontier Auth Service is currently broken.

**Comment by Marginal** [comment]
Now fixed.
