### ISSUE TITLE
Program hang on auto-log entry on system

### ISSUE THREAD

**Issue by Kilandor** [Marginal/EDMarketConnector#38]
I am using Release 1.84
Only options on 
* Send Flight Log Data to EDSM
* Automatically make a log entry on entering a system

I went out to start exploring today. With Auto-log on the program seems to hang on every system entry. The last display is "Sending data to EDSM", still showing the previous system name.

If I disable Auto-log on system entry. I can manually update or use the hotkey and it works with no issues

**Comment by Marginal** [comment]
Fixed in Release 1.85
