### ISSUE TITLE
Error: user not found

### ISSUE THREAD

**Issue by elitedangerousplayer** [Marginal/EDMarketConnector#384]
On PC, when trying to link to my account for the first time, trying to login through steam I get the message "error: user not found". This happens regardless of whether I try to log in through Chrome or Firefox.

**Comment by elitedangerousplayer** [comment]
[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/2730323/EDMarketConnector.log)

**Comment by Marginal** [comment]
Try logging in with your Frontier credentials, not via Steam.

**Comment by elitedangerousplayer** [comment]
I don't think I have those, since I bought the game from Steam.

**Comment by Marginal** [comment]
When you redeemed your Steam "CD key(s)" you had to create a Frontier account?
Please use those credentials.

**Comment by elitedangerousplayer** [comment]
I don't think I have those, since I bought the game from Steam.

**Comment by elitedangerousplayer** [comment]
I don't have them. I can't even reset my password. Why are you giving me a workaround?

**Comment by elitedangerousplayer** [comment]
I apologize for that. I'm getting very frustrated. I'm sure I did create a Frontier account but Lastpass didn't save my credentials, so I have to reset my password... but THAT process is giving me its own difficulties (I'm not getting the emails in my inbox or spam). The only way I can access the game or the Frontier store is by using my Steam credentials. If I can't use them for this then I can't use this.

**Comment by Marginal** [comment]
The "User not found" error is coming from Frontier's servers, so I can't fix that.
The reset password form is [here](https://www.frontierstore.net/customer/account/forgotpassword/).
If you suspect you may have provided an invalid email address please see [here](https://support.frontier.co.uk/kb/faq.php?id=186&topicid=48).
