### ISSUE TITLE
Authentication against the Frontier oAuth service

### ISSUE THREAD

**Issue by Varples** [Marginal/EDMarketConnector#389]
I get directed to the authentication page of Frontiers service, but once I click there I am prompted to allow EDMC to " Approve Account Access for Elite Dangerous Market Connector".  When I click Approve there,  Windows prompts me to Allow an Untrusted Application

I affirm that, but it seems too late for the application.  I'm already running EDMC with elevated privileges.  Do I really need to delve into the .NET Framework to elevate its trust still further?  Or is this an Edge/browser configuration thing?

EDMC still appears to be reading and sending stuff to the downstream services when I'm playing (INARA etc).  So is all this a red herring?

**Comment by Varples** [comment]
if I hit Approve again in the window I get a 500 error from the Frontier service...

**Comment by Marginal** [comment]
In general, you shouldn't run this (or any normal app) with elevated privileges. Any reason you can't just run it normally?
If the app isn't displaying any error messages and isn't redirecting you back to Frontier's authentication website again then all is fine.

**Comment by l3lu3** [comment]
Same here. I've tried reinstalling but changes nothing. It's in a loop of auth and edmc claims it's invalid credentials.

**Comment by Varples** [comment]
Well blimey – either it’s failing quietly now, or that’s resolved it...

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
