### ISSUE TITLE
1.8.5 Unable to Enable Auto-Log

### ISSUE THREAD

**Issue by Kilandor** [Marginal/EDMarketConnector#39]
Thanks for the fast update, however I have been unable to test it.

Whenever I try to check the box to enable auto-log on enter system. The window will not close and save the setting. Hitting "Ok" or the "x" keep the window open. As soon as I uncheck it, it can close again. it will save any other setting just fine still

**Comment by Marginal** [comment]
Fixed in Release 1.86.
Note to self: Must test more.
