### ISSUE TITLE
Suggestion: Using the new, updated EDSY

### ISSUE THREAD

**Issue by PartyHawk** [Marginal/EDMarketConnector#392]
The old EDSY is no longer supported, edshipyard.com. It has been dropped for a while and someone else has picked it up and moved it to edshipyard.net. 

Would like it if this gets updated in the MC, as the old EDSY is missing key stuff like the guardian fsd booster.

**Comment by inorton** [comment]
I'm afrad that edshipyard.net is owned an operated by a known scammer and is generally considered untrusted, especially within the Elite community.
