### ISSUE TITLE
AutoUpdate fails with WinSparkle error message

### ISSUE THREAD

**Issue by Dergell** [Marginal/EDMarketConnector#393]
It's not really critical, but it's a pain in the ass. It started a few months ago but so far I've ignored it.

Whenever I start EDMC and there is a new release, I get a corresponding message. I then click on "Install update", it tries to download the new version and then an error occurs immediately.

**Title:** "Update Error!
**Text:** "An error occurred in retrieving update information; are you connected to the internet? Please try again later."

I traced it back to something called "WinSparkle", which is probably responsible for the automatic updates. But I didn't get any further. I have already completely removed EDMC from the system and reinstalled it, but that didn't help either. I also checked the registry to see if anything was broken. But it doesn't look like it. The log file also doesn't say anything and I have already excluded the firewall of windows, as well as antivirus.

Unfortunately I didn't find anyone else with this problem. But it remains a constant problem, even if I manually pull and install the new version from GitHub, which works without problems.

**Comment by Marginal** [comment]
I ran into this issue on Windows 7. Please try disabling (deprecated) SSL and enabling the TLS options: https://help.passageways.com/hc/en-us/articles/115005183226-How-to-enable-TLS-1-2-in-Internet-Explorer-11-and-MS-Edge?mobile_site=true

**Comment by Dergell** [comment]
Okay, maybe that should be added to the FAQ section, because I haven't found anything like that on my Google search.

Anyway, I have updated the settings and will now wait for the next release. Once that hits I can try it and give you an update here.

Thanks for your help!

**Comment by Marginal** [comment]
You can test by:
- Uninstalling
- Installing an [older release](https://github.com/Marginal/EDMarketConnector/releases)
- Choosing File -> Check for Update

**Comment by Dergell** [comment]
Yeah but ... I'm lazy xD
All right, I tested it and it worked like a charm. Thanks again and maybe this can help someone else too.

**Comment by Marginal** [comment]
Thanks. Will add to the [Troubleshooting](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting) guide.
