### ISSUE TITLE
[Linux] Can't set E:D journal file location (Error: Check E:D jounral file location)

### ISSUE THREAD

**Issue by r79** [Marginal/EDMarketConnector#394]
I'm running E:D with using proton on arch linux. I've set the edmc to the correct journal file. I did find the correct journal folder (which is filled with live updating journal entries):

![image](https://user-images.githubusercontent.com/6749862/51095052-29896b00-17b2-11e9-95b1-9107704c4e02.png)

newest journal file (I'm currently just having the game open, not doing anything in it):
![image](https://user-images.githubusercontent.com/6749862/51095068-5178ce80-17b2-11e9-9de6-ae13a6b95e1d.png)

I did set this directory correctly in the edmc settings dialog:
![image](https://user-images.githubusercontent.com/6749862/51095106-969d0080-17b2-11e9-9ae4-fd0b3388009f.png)

This is the output I get from the console I'm running the EDMC from:
![image](https://user-images.githubusercontent.com/6749862/51095154-e5e33100-17b2-11e9-8dc6-19650fffda8f.png)
the first "Stopping monitoring journal" shows at the start, the second one after I selected the folder in the settings menu.

Things I tried to fix it (which obviously didn't work, hence this ticket exists):
- chmod 777 on the journal folder
- running it with sudo
- creating a shortlink (basically a directory link) of the journal folder without spaces (thinking that spaces usually fuck shit up in IT)

Does the EDMC need to find the E:D process itself and not just the journals? Am I in fact not in the correct journal folder? Is it maybe a problem with my installed python libraries?

Any help appreciated (and some money got put aside for donations in case you support me here) :)

**Comment by r79** [comment]
Because I'm a capable coder (and even though I never read python), I did read through the code and found out something interesting when I stumbled at the configfile:
![image](https://user-images.githubusercontent.com/6749862/51095435-01e7d200-17b5-11e9-8912-13e8a44fefcd.png)

It seems like something might be wrong [here](https://github.com/Marginal/EDMarketConnector/blob/master/config.py#L268), it might be possible that you'll see a PR from me in a few minutes :)

**Comment by Marginal** [comment]
Looks like you're setting the output folder on the "Output" tab, rather than the "E:D journal file location" on the "Configuration" tab.

**Comment by r79** [comment]
Oh well...

I'm freaking stupid, of course it never set the journal path because I actually never set it in the Settings window:
![image](https://user-images.githubusercontent.com/6749862/51095536-c1d51f00-17b5-11e9-98af-102ecb77f423.png)

![image](https://user-images.githubusercontent.com/6749862/51095545-d4e7ef00-17b5-11e9-8020-a4a5203d84db.png)

-> Closed, sorry for being stupid, that's why one shouldn't attempt to do things at 4 am in the morning >_<

**Comment by r79** [comment]
P.S.: Fantastic code btw and thanks for the quick reply endorsing my dorkiness :sweat_smile: Do you accept donations? If so can you direct me to the donations? You deserve something just for the plain fact you're perfectly supporting Linux :heart:
