### ISSUE TITLE
[Linux] Browser Authentication doesn't open

### ISSUE THREAD

**Issue by r79** [Marginal/EDMarketConnector#395]
I'm probably [once again too stupid for my own good](https://github.com/Marginal/EDMarketConnector/issues/394), but I feel like this time I found an actual bug: If I understood it correctly at some point the EDMC will want to open a browser Window in order to start the OAuth process. On Linux, this never seems to happen (and I can't find any logs). It looks like the programm is already throwing a CredentialsError [at this line](https://github.com/Marginal/EDMarketConnector/blob/master/companion.py#L284), which seems to be in front of the actual initialization of the Auth process.

What I'm doing: Starting EDMC and logging into the game.
Console Output:
> CredentialsError: Error: Invalid Credentials
Traceback (most recent call last):
  File "./EDMarketConnector.py", line 405, in getandsend
    data = companion.session.station()
  File "/home/r79/slow/games/edmc/EDMarketConnector/companion.py", line 371, in station
    data = self.query(URL_QUERY)
  File "/home/r79/slow/games/edmc/EDMarketConnector/companion.py", line 333, in query
    if self.login():
  File "/home/r79/slow/games/edmc/EDMarketConnector/companion.py", line 284, in login
    raise CredentialsError()
CredentialsError: Error: Invalid Credentials

I'll check through the code and my configs again to see what's going on.

**Comment by r79** [comment]
Okay, broke it down a little more by deleting those lines, now I get a 500 because the client_id is set to "None" in the URL, kinda obvious actually.

So the browser opens fine, the problem is that the EDMC can't get a CLIENT_ID

**Comment by r79** [comment]
I'm not 100% sure but I feel like there needs to be another exception check for CredentialError [here](https://github.com/Marginal/EDMarketConnector/blob/master/EDMarketConnector.py#L471)

**Comment by r79** [comment]
I'm so confused, so you're initializing the CLIENT_ID [here](https://github.com/Marginal/EDMarketConnector/blob/f00e44065c9d9bce73714a5ecd0f608185dfec61/companion.py#L23) and you even added the comment to "Replace this with Frontier ID", but neither can I see any code that is setting this variable (which might be because I don't know much about Python and maybe there's some magic going on) nor was I able to find how exactly this client ID should look like. I was hoping I could just "get into my FDEV account and get that ID" but there's 0 information about it.

How does this whole thing work? How does it get this magical Client_ID?

**Comment by r79** [comment]
[Of course...](https://github.com/Marginal/EDMarketConnector/blob/master/protocol.py#L193)

**Comment by r79** [comment]
Did some research on this, it looks like the only way to implement a protocol handler would be by using a special xdg-open handler, which will only work by using a desktop file, which only should be there after a package got installed, which means that the EDMC would need to be packaged.

Now there's the following alternatives:
- just plop a desktop file there from within the code (dirty but it might work)
 -> that would mean that there needs to be some way of interaction between python instances, I'd have to look into that
- use a different kind of callback handler for linux (like spinning up a webserver and setting the callback to "localhost:[port]/auth")
- use this fancy PKCE thingie that has actually been made for a client-side auth flow: https://auth0.com/docs/api-auth/tutorials/authorization-code-grant-pkce

**Comment by Marginal** [comment]
Yes, the right thing to do would be to create a [custom protocol handler](https://edoceo.com/howto/xfce-custom-uri-handler) in the same spirit as the macOS and Windows implementation and forward the callback URI to the main app, probably using Tk's [send](http://effbot.org/tkinterbook/widget.htm#Tkinter.Widget.send-method) method (sort-of documented [here](https://wiki.tcl-lang.org/page/send)). But that would require either an installation script or properly packaging the app as .deb and .rpm.

Local web server is probably a lot easier all around.

Or a really simple hacky approach is to just prompt for the callback URL like [this](https://github.com/pwerken/EDMarketConnector/commit/4ac4545d573f89908900165824cff34167a49c70)

**Comment by r79** [comment]
Creative

Would you be interested in me rewriting the whole thing to use a webserver? I'd be eager to do it :)

**Comment by Marginal** [comment]
No. The macOS implementation just works. The MS implementation has some reported issues (particularly when the user is using IE) but is less likely to trigger anti-malware programs on Windows than opening up a random port.

**Comment by r79** [comment]
How about only doing it for Linux to make the Linux impl a little less hassleful?

**Comment by Marginal** [comment]
I'm not entirely sure what you mean by "use a webserver".
The whole point of the [OAuth](https://oauth.net/2/) workflow is that as a user you never enter your credentials into a third-party app or website.
