### ISSUE TITLE
maximum recursion depth exceeded in cmp

### ISSUE THREAD

**Issue by Fredyy90** [Marginal/EDMarketConnector#397]
Hey,

Since a few days my EDMC contantly freezes and after some minutes it unfreezes and shows an error message in bottom line: "maximum recursion depth exceeded in cmp"

I thought it was plugin related, but even with all plugins disabled the problem stays.

![image](https://user-images.githubusercontent.com/1572327/51311694-c87bc480-1a49-11e9-8dff-ebd6164fe889.png)

**Comment by Marginal** [comment]
The root cause is that the Frontier cAPI server is currently down. d4cb8b8 produces a more helpful error message.
