### ISSUE TITLE
Fetching Data freezes application

### ISSUE THREAD

**Issue by Azuca89** [Marginal/EDMarketConnector#398]
Hi. 

I have spent the entire morning trying to sort this out. 
Whenever the ED Market connector gets to "Fetching Data..." the application freezes and needs to be force quit. 

I have done a clean reinstall of the application, after removing the registry keys and all associated files from my PC but no luck. 

Attached is the log file. 
It states an error 401 which I believe is a credential problem. However, I have reset my Frontier credentials twice to make sure they are correct. I have also un-linked the application to my account a few times. This then prompts for me to re-enter my credentials. I approve access, EDMC then states "Authentication successful" but then once again freezes once it hits "Fetching Data"

Any assistance will be welcome. 

[EDMarketConnector.zip](https://github.com/Marginal/EDMarketConnector/files/2768349/EDMarketConnector.zip)

**Comment by Kikoman72** [comment]
Same here. Can't make it work.

**Comment by Marginal** [comment]
A workaround is to kill the app and delete the registry key `HKEY_CURRENT_USER\Software\Marginal\EDMarketConnector\fdev_apikeys`.

**Comment by 0xz00n** [comment]
I've done exactly that and still stuck on Fetching Data.

This is what the connector log is showing:
`(x86)\EDMarketConnector\plugins\inara.py"
Auth	No token for SANITIZED
Auth	New authorization request
Auth	New token for SANITIZED
Traceback (most recent call last):
  File "companion.pyo", line 354, in query
  File "requests\models.pyo", line 935, in raise_for_status
HTTPError: 401 Client Error: Unauthorized for url: https://companion.orerve.net/profile
cAPI	https://companion.orerve.net/profile 401 {'Content-Length': '0', 'Strict-Transport-Security': 'max-age=16070400; includeSubDomains', 'Set-Cookie': 'CompanionApp=SANITIZED; path=/', 'Expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'Server': 'Apache', 'Connection': 'keep-alive', 'X-UA-Compatible': 'IE=edge', 'Pragma': 'no-cache', 'Cache-Control': 'no-transform', 'Date': 'Thu, 17 Jan 2019 17:36:25 GMT', 'Content-Type': 'text/html;charset=UTF-8'} `

The traceback is repeated several hundred times from what I assume are my attempts to fix it.

**Comment by Marginal** [comment]
Seems that it's working for some people and not others. Are you running via Steam?

**Comment by 0xz00n** [comment]
Yes, I'm running E:D via Steam.

**Comment by 0xz00n** [comment]
It looks like it's working now, however.  Maybe it was an FDev API issue like mentioned above.

**Comment by Marginal** [comment]
FDev issue that current release of EDMC doesn't handle very gracefully.

**Comment by Marginal** [comment]
Should be fixed in [Release 3.37](
https://github.com/Marginal/EDMarketConnector/releases/latest).
