### ISSUE TITLE
MC b=no longer works.

### ISSUE THREAD

**Issue by incryptx** [Marginal/EDMarketConnector#399]
I can get it to run, but the settings for Inara API and EDSM API are greyed out with no info in them.

I have uninstalled, reinstalled, deleted reg keys, and approved the Frontier login with error 505 coming back.

It just won't run anymore. I took an upgrade from Frontier Elite this morning, and MC was working just before this. 

Given Frontier's API seems to be down, MC and EDDI no longer work or can login.

**Comment by Marginal** [comment]
https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#credentials-settings-are-greyed-out
