### ISSUE TITLE
Not authenticating with Frontier API/Website

### ISSUE THREAD

**Issue by incryptx** [Marginal/EDMarketConnector#400]
MC states "Logging In" after approving the Frontier Login/API. then hangs.

MC then states "Invalid Credentials", and does not login or update.

Just started after latest Elite Upgrade on 01/17/2018 at 8:00AM PST

**Comment by Marginal** [comment]
Please zip up and attach the file `%TMP%\EDMarketConnector.log`.

**Comment by incryptx** [comment]
Your request for EDMarketConnector.Log content:
[EDMarketConnector.zip](https://github.com/Marginal/EDMarketConnector/files/2770685/EDMarketConnector.zip)

**Comment by Marginal** [comment]
Are you using IE as your default browser?

**Comment by Marginal** [comment]
The Frontier servers were unreliable yesterday.
Please retry with [Release 3.37](
https://github.com/Marginal/EDMarketConnector/releases/latest) and post an updated `%TMP%\EDMarketConnector.log` if the problem remains.

**Comment by incryptx** [comment]
Installed 3.37, still unable to approve Frontier API/Website login. ED states logging in and hangs there.

Closing the Frontier Approval Website causes MC to state "Invalid Credentials".

Results for EDMarketConnector.Log
---------------------------------------------------------------------------------------------------
E:D Market Connector 3.3.7.0 2019-01-18T16:42:55
loading plugin coriolis from "C:\Program Files (x86)\EDMarketConnector\plugins\coriolis.py"
loading plugin eddb from "C:\Program Files (x86)\EDMarketConnector\plugins\eddb.py"
loading plugin eddn from "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py"
loading plugin edsm from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
loading plugin edsy from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
loading plugin inara from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"
Auth	No token for Maylor Rom
Auth	New authorization request
---------------------------------------------------------------------------------------------------

**Comment by incryptx** [comment]
I think the Frontier API/Website is still down.

**Comment by Marginal** [comment]
The log shows the app making an authentication request, but never receiving a response from the browser.

Does the authentication website look like this?
![approve](https://user-images.githubusercontent.com/1374740/51404475-71f6af00-1b4b-11e9-8301-1ae8758a57c5.png)

And do you see a dialog that looks exactly like this when you press "Approve"?
![launch](https://user-images.githubusercontent.com/1374740/51404505-820e8e80-1b4b-11e9-9737-b6f74d51bf8e.png)

**Comment by incryptx** [comment]
Yes, the first one looks like that, but not the second one. My second one looks like the first, but looks Like this.

https://screenshots.firefox.com/2O1O269WlZ8Wbdq8/auth.frontierstore.net

**Comment by incryptx** [comment]
I don't have Edge, as I run Windows 7, but I tried Chrome and it all looks the same.

**Comment by incryptx** [comment]
Just as a workaround for this, I exported the registry key "HKEY_CURRENT_USER\Software\Marginal" and saved it to the default MC installation directory. If MC goes down again due to a browser condition of not returning the Frontier API key for MC, I will just import this key and be golden again.

**Comment by incryptx** [comment]
Closing this issue. Summary, another browser error similar to IE, but occurring in Firefox. Using Chrome as the default browser when MC authenticates with the Frontier API/Website will solve the issue of "Invalid Credentials".

**Comment by Marginal** [comment]
> If MC goes down again due to a browser condition of not returning the Frontier API key for MC, I will just import this key and be golden again.

Unfortunately not. The token stored in HKEY_CURRENT_USER\Software\Marginal needs to be periodically refreshed, and you can't re-use an old one.

**Comment by Marginal** [comment]
See also bcd3530 .
