### ISSUE TITLE
Suggestion: notification on newly discovered system entrance

### ISSUE THREAD

**Issue by mosteo** [Marginal/EDMarketConnector#401]
I see that EDMC marks the current system with either a green circle or a star. I understand the latter is when you enter a system never visited before by anybody.
I would find useful to get a pop-up notification when such a system is entered. I play in borderless window and system pop-ups are visible while in-game.
I've tried to locate where this information is determined during an update but haven't found it. If you can point me in the right direction I could add it myself.
Thanks.

**Comment by Marginal** [comment]
https://github.com/Marginal/EDMarketConnector/blob/master/plugins/edsm.py#L358

Or consider using the app's transparent theme and setting it as "Always on top" on the apps "Appearance" settings tab.

**Comment by mosteo** [comment]
Thanks, I will try to progress from there.

Unfortunately, (on linux, rel-337), I see only default and dark themes. Also, the setting for always on top doesn't work and every time I enter the settings tab it has gone back to unchecked. Finally, even the window manager "always on top" doesn't work for the borderless ED window, which is surprising.

**Comment by Marginal** [comment]
Your mention of "borderless window" made me think you were on Windows.
Correct, transparent Theme isn't available on Linux. And dark theme on Linux means taking the app out of the Window Manager's control.

**Comment by Marginal** [comment]
From the next release (or now if you're running from source) you can implement a `edsm_notify_system()` function [like this](https://github.com/Marginal/EDMarketConnector/blob/37a1f0dd23eac02375ced3d62b10e629dbe4143e/plugins/edsm.py#L356) in your plugin to get access to the EDSM status.
