### ISSUE TITLE
Question: How to enter API data for multiple E:D accounts?

### ISSUE THREAD

**Issue by BannorPhil** [Marginal/EDMarketConnector#404]
Hello

I notice EDMC recognises which Commander I happen to be logged into at any particular time, but I'd like to start tracking data from my 2nd E:D account - sending it to EDSM, Inara, and the like (just as with my main E:D account).

If I enter my Frontier login details, the various API keys, etc for my 2nd account, will it 'forget' about my main account (so that when I switch back to it, I'll have to enter everything again)? And do this each time I switch accounts?

I'm not a streamer, and I don't need to run multiple instances of E:D simultaneously on the same machine - I just need to switch between different accounts, using only 1 of them at a time.

If this functionality is not already available in EDMC, please consider adding it. With the recent specials on new E:D accounts that have been happening over the festive season, there's probably quite a few Commanders like myself with multiple accounts.

Thanks for the **excellent** app!!

Philip Bannor

**Comment by Marginal** [comment]
The app will prompt you for new settings when you start playing ED with your 2nd account.
The app keeps Frontier, EDSM and Inara login details separate between your multiple accounts.
