### ISSUE TITLE
Error: Invalid Credentials with definitely valid credentials

### ISSUE THREAD

**Issue by le0lan** [Marginal/EDMarketConnector#405]
[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/2862438/EDMarketConnector.log)

I am getting the Error "Invalid Credentials" all the time. 
I have checked multiple times but the credentials are definitely correct.
Anything I can do?
(And for clearing the cookie.txt like others have done - there is no such file in %USER%\AppData\Local\EDMarketConnector)

**Comment by Alt-Avatar** [comment]
I have the same problem as well

**Comment by Alt-Avatar** [comment]
I found this if you haven't seen this fix. It works.
@jamsoft I have just had the same issue. I solved by going to the [Frontier auth service website](https://auth.frontierstore.net/), logging in, deauthorizing EDMC and then trying to get credentials again through EDMC. Frontier asked me to authorize EDMC again and then it worked.

**Comment by mbojan** [comment]
@Alt-Avatar thanks! worked!

**Comment by le0lan** [comment]
@Alt-Avatar worked for me too. Awesome, thanks!
