### ISSUE TITLE
SYSTEM link no longer working

### ISSUE THREAD

**Issue by doc-ketamine** [Marginal/EDMarketConnector#406]
Love ED:MC, been using it for a few weeks. Initially only used it with Inara, was sending data, using the link on the main screen to click on to get to Inara's data for systems and stations. Was using Coriolis for ship info, of course. 

Then I added EDDN and EDSM data-sending. Created accounts on those sites, everything is logged in, life is good. Except now I can no longer click on the SYSTEM link to view the system in Inara. A little "no-smoking" style red-circle-with-line is there instead. I can copy the text and paste into Inara, but the prior functionality is gone.

I can change the settings to use EDSM for system data, but ED:SM is less than desirable in terms of interface for me. 

What could have gone wrong?

**Comment by doc-ketamine** [comment]
Nothing in my Inara apps error log.

**Comment by Marginal** [comment]
Not sure - it's working for me.
Is Inara updating correctly? The Inara system and station links are only usable if you're successfully sending your flight log and Cmdr status to Inara.

**Comment by doc-ketamine** [comment]
There’s nothing in my error log but no, my system data is not updating on Indra. But my Inara code is legit, double-checked.

-m-
Matthew Kershaw, MD

________________________________

**Comment by Marginal** [comment]
Please double-check your Inara settings.
Otherwise please compress and attach the file `%TMP%\EDMarketConnector.log` here.

**Comment by doc-ketamine** [comment]
I did. I triple and quadruple checked them. And then I generated a new API key and used it, authentication all successful. My info shows up in the Inara flight log but "nearest" doesn't show my current location. And the red-circle-can't-click-here is still there for my SYSTEM on EDMC.

**Comment by doc-ketamine** [comment]
Here is my  EDMarketConnector.log:
`E:D Market Connector 3.3.7.0 2019-02-17T19:38:43
loading plugin coriolis from "C:\Program Files (x86)\EDMarketConnector\plugins\coriolis.py"
loading plugin eddb from "C:\Program Files (x86)\EDMarketConnector\plugins\eddb.py"
loading plugin eddn from "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py"
loading plugin edsm from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
loading plugin edsy from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
loading plugin inara from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"
`

**Comment by doc-ketamine** [comment]
Again, everything worked well with Inara until I added in the other two services, EDDN and EDSM.

**Comment by doc-ketamine** [comment]
Maybe it's not EDMC? Maybe it's a lack of data in Inara? I am on a 5k LY exploration trip. See the attached ... the systems I'm in aren't even linked on Inara's website. Screenshot from when I set out - some of them are lined, then not.
![inara1](https://user-images.githubusercontent.com/47696626/52922746-77354e00-32f1-11e9-8898-1002b75d0d69.GIF)

**Comment by doc-ketamine** [comment]
It's bizarre because those same systems can be found in EDSM.

**Comment by Marginal** [comment]
If Inara doesn't recognise the system then the system link in EDMC isn't going to work.
