### ISSUE TITLE
Show log directory in Settings - Enhancement

### ISSUE THREAD

**Issue by NoFoolLikeOne** [Marginal/EDMarketConnector#409]
It would be useful to show the logfile directory or a clickable link to open the logfile somewhere in the settings page. Because I can never remember where it is when I don't have access to EDMC and have someone reporting a bug on my buggy plugins

**Comment by Marginal** [comment]
I'm reluctant to add more clutter to the settings page.
FYI the log file location is documented [here](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#reporting-a-problem).
