### ISSUE TITLE
EDSM failure seems to prevent csv output

### ISSUE THREAD

**Issue by nickfromkew** [Marginal/EDMarketConnector#41]
Hello CMDRs. 

Love this application - really useful to help me contribute to the EDDN data network. I also use Thrudd's site and so use it to generate a .csv file when I arrive at a station. 
In my settings I have EDSM set up to contribute star data, but if that fails for any reason, the .csv is not generated. I then have to wait for the 2 minute cool down, and then re-do the hot-key in order to get the .csv. That's if I notice before I launch... which often I don't. 
I am unsure if the EDDN data is sent, but I know for certain that the .csv is not generated.
Is this a dependency issue in the order the code is executed, so that the .csv fails due to the EDSM failure? If so, can it be made independent so that I can still get the .csv file? 
I would contribute to the development, but I've never done any coding, other than a bit of visual basic... 
I'm using Windows 10 64 bit, fully patched and up to date, with the latest release of the EDMarketConnector.
I've tried clearing EDSM credentials and logging back in, and the only consistent fix is to untick the "Send flight log to EDSM" box. 
Happy to provide more information if needed. 
Cheers

**Comment by Marginal** [comment]
Will be fixed in the next release (commit 62c85d5).

**Comment by Marginal** [comment]
Fixed in Release 1.88.
