### ISSUE TITLE
EDMCOverlay?

### ISSUE THREAD

**Issue by incryptx** [Marginal/EDMarketConnector#410]
Hello
I have EDMC installed and when I start Elite, when the spinning ship is on the screen, I get a "/EDMC/Overlay/ in this window. Am I supposed to see something on my cockpit screen?

I also have some app called "HITS" which I have not installed yet, because I don't see any "Overlay" on my cockpit screen.

Am I missing something here?

**Comment by inorton** [comment]
Hi, it sounds like you have a version of my plugins installed.

They aren't bundled with EDMC so they might just be from a long time ago.

EDMCOverlay is a plugin that other plugins can try to use to render text and simple vector graphics over the top of the game window.

It usually works well with Nvidia cards when run in borderless mode.

The plugins that I know of that can use it are EDR, HITS, Flat track and LandingPad.

There might be a couple of others too.

Some plugins used to distribute the overlay server inside their own plugin folder

**Comment by incryptx** [comment]
I'm not real sure what version of it I have, but I do get some info from HITS and EDRecon on the screen, but it all seems flakey at times. Sometimes I get the /edmc/edmcoverlay/ on the spinning ship screen and sometimes not. 

Is there a download of the latest version of EDMCOverlay somewhere?

**Comment by inorton** [comment]
Sure, the latest version is https://github.com/inorton/EDMCOverlay/releases

**Comment by incryptx** [comment]
That is the one I have. Are you no longer supporting it?

**Comment by inorton** [comment]
I am supporting it yes. Can you write stuff into the bug reports over there? you might have hit an existing one.

**Comment by incryptx** [comment]
Isn't this where I should log bugs? Where should I put this kind of stuff?
