### ISSUE TITLE
Request: Add a link to EDMC-Canonn Plugin in Wiki

### ISSUE THREAD

**Issue by derrickmehaffy** [Marginal/EDMarketConnector#411]
Requesting to add our Canonn plugin to the list of plugins on the [wiki](https://github.com/Marginal/EDMarketConnector/wiki/Plugins)

Here is a link to our repo's latest release which is now public and pushed to Canonn pilots: https://github.com/canonn-science/EDMC-Canonn/releases/latest

Please and thank you :smiley:

**Comment by Marginal** [comment]
[Done](https://github.com/Marginal/EDMarketConnector/wiki/Plugins).
