### ISSUE TITLE
Suggestion: Match Transparent Appearance to HUD Theme

### ISSUE THREAD

**Issue by RHBallistic** [Marginal/EDMarketConnector#412]
I like to see the EDMC widget when playing, but the default appearance options are too far from the in-game HUD aesthetic for me (muh immerzion!).  A simple font change, text skew, and right alignment for the Transparent appearance option would go a long ways towards making it feel more integrated into the game.

Attached is a mockup of what I am talking about.
![EDMC Mockup](https://user-images.githubusercontent.com/33406619/55666550-456a3f00-57ec-11e9-9000-44ff41b1b429.png)

**Comment by Marginal** [comment]
Next release will use a matching font:
![Screenshot 2019-04-07 at 13 33 04](https://user-images.githubusercontent.com/1374740/55684652-875ac880-5945-11e9-9856-1df4179d40f7.png)

But I don't think it's possible to get the degree of immersion you're looking for - there's too much potential variation in font size, placement and skew.
