### ISSUE TITLE
End of python 2

### ISSUE THREAD

**Issue by Tilt78** [Marginal/EDMarketConnector#415]
Hello,
I think your app use python2, and on linux distributions, python 2 is being unsuported and now its python 3.
Do you plan to make your app compatible with Python 3 for linux users ?
Thanks and bbye

**Comment by Marginal** [comment]
Python 2 is supported by the latest release of all major distros.
At some point in the future it will be necessary to convert the app to Python 3, but this will break all plugins.

**Comment by dudeofawesome** [comment]
Python 2.7 EOL is coming January 1st 2020, so just under 4 months out as of this comment. 

From a perspective of writing new plugins, 3.X would be much appreciated.

**Comment by Athanasius** [comment]
As a heads up, I've started active work again on getting EDMC to work with Python3.  As EOL of Python2.7 is now so close I'm forgoing having my changes work on both.  The work will be at https://github.com/Athanasius/EDMarketConnector/tree/python3-2019 .  I'm trying to take as much care as possible to have this not cause issues for any data receivers, and have put in great big warnings for anyone else attempting to use it.
