### ISSUE TITLE
Unable to change install directory

### ISSUE THREAD

**Issue by bWildcard** [Marginal/EDMarketConnector#417]
I have uninstalled EDMC, ran CCleaner and tried to reinstall to change the install folder off of my C:/ drive and it doesn't work. 

Is there some trick im missing to get this addon to stop installing to "C:\Program Files (x86)\EDMarketConnector\"

**Comment by Marginal** [comment]
https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#installing-on-a-different-drive
