### ISSUE TITLE
Invalid Credentials still a problem?

### ISSUE THREAD

**Issue by lehthanis** [Marginal/EDMarketConnector#419]
I finally got the app working in Arch Linux...had to bootstrap pip to Python2.7

Now I'm getting invalid credentials...it's updating EDDN, Inara, and EDSM apparently, but if I click the update button it says invalid credentials.  I'm guessing this is related to the cAPI? I tried setting up one with frontier, but it says 500 server error.  therefore I'm not starting the app from source with a CLIENTID...is that my problem?

**Comment by chr7** [comment]
Same problem here: the app runs under Ubuntu 18.04 well. I exported my CLIENTID, the page opens in the browser but I get a "500 Internal Server Error".

URL is (sensitive data removed):
https://auth.frontierstore.net/auth?response_type=code&audience=frontier&scope=capi&client_id=xxx&code_challenge=xxx&code_challenge_method=S256&state=xxx&redirect_uri=http://localhost:44651/auth

**Comment by CMDR-Kiel42** [comment]
Same problem here, I opened a ticket with Frontier, it looks like it's a problem on their end.
Feel free to upvote it.

https://issues.frontierstore.net/issue-detail/2342

**Comment by chr7** [comment]
Not exactly the same: I already have a CLIENTID but I cannot register EDMC with it.

**Comment by CMDR-Kiel42** [comment]
Yes, but lehthanis doesn't:

>  tried setting up one with frontier, but it says 500 server error. therefore I'm not starting the app from source with a CLIENTID...

I assume it's part of the same problem with FDev server.

**Comment by mikeloeven** [comment]
Just installed this every time the app tries to do anything it brings me to the frontier login page but any time it updates or needs to be refreshed it spits out a invalid credentials error so it seems like the app is authenticating with frontier properly but not remembering the session

**Comment by BenIkNiels** [comment]
Has there been any new info for this? Having the same problem.

**Comment by badmin-c** [comment]
Same problem here, did all of the troubleshootings, didn't help.

I read there was a recent change in Frontiers Account processing. Inara.cz also has problems since then, Data from Frontiers Website cannot be imported right now. They filed a report and it got acknowledged.

Link: https://inara.cz/board/7049/?page=17

**Comment by badmin-c** [comment]
There is a reddit post which states that Frontier will fix the issue in the next major update and that it's indeed related to the new "keyless" Steam purchases:

https://www.reddit.com/r/EliteDangerous/comments/cwon5r/caution_regarding_steam_purchases_of_ed/

Guess it will be over soon!

**Comment by Senti666** [comment]
I can confirm it´s working fine since ED´s 2019 September update
