### ISSUE TITLE
trying make plugin with flask

### ISSUE THREAD

**Issue by wormie007** [Marginal/EDMarketConnector#423]
I am trying to develop a plugin using Flask to present the information through the browser and thus be able to see it on any device connected to the same network. The problem arises in that after trying in different ways to import Flask, I always get an import error.

Is there any way to make it run?

**Comment by inorton** [comment]
I think you will either need to ship flask and other things with your plugin or get it distributed with EDMC

**Comment by wormie007** [comment]
> I think you will either need to ship flask and other things with your plugin or get it distributed with EDMC

Thanks for all, i get all the lib that it required and now it's working well the import.

The issue could be close. 

When I have the plugin completed and working correctly, I will upload it to github for everyone's use
