### ISSUE TITLE
Frontier Login issue 

### ISSUE THREAD

**Issue by Senti666** [Marginal/EDMarketConnector#427]
Hello,
I want to use EDMC with Elite Dangerous (Horizon/Singleplayer) on a Windows10 Home, 64bit System but struggle with the frontier login it seems.

Before starting ED I always start EDMC, it opens the login-page at https://auth.frontierstore.net/auth. I enter email and password and it tells me that the authorisation is fine. I start ED it tells me ship, system and station correctly, but as soon I hit "Update", it always opens a new browser window and asks me to enter my data again. I tried Firefox and Chrome. Reading the log, I see the 500 Internal Server Error. I tried for some days now but always without success. 

I read in some forum it might help to change the audience=frontier part to audience=steam, but this didn´t help. (I bought the game with Steam)
I deauthorized/authorized EDMC at https://user.frontierstore.net/linked, but this didn´t help either.

[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/3372790/EDMarketConnector.log)

**Comment by mikeloeven** [comment]
Confirmed this still an issue possibly related to #419

**Comment by Saxtus** [comment]
I bought game through Steam and I confirm the problem. Changing the audience part of the URL doesn't solve the problem. Every time I dock somewhere, needs to get authenticated again.

**Comment by Senti666** [comment]
I can confirm it´s working fine since ED´s 2019 September update
