### ISSUE TITLE
How to integrate with OBS?

### ISSUE THREAD

**Issue by XenHat** [Marginal/EDMarketConnector#429]
I currently use EDDiscovery AND EDMC at the same time while I play Elite Dangerous.

I would prefer to use EDMC alone, but I could not find any existing plugin that would convert the JSON data to plain text files for OBS text overlays.

Could we get such functionality, or a workable way of achieving the same result?

**Comment by Marginal** [comment]
What's OBS?

**Comment by Maldor** [comment]
Open Broadcaster software. Basically allows for streaming gameplay to twitch or similar service.

**Comment by Marginal** [comment]
Writing an EDMC plugin to output to OBS should be easy, or at least do-able. But the only reference I can find to text input sources is [this](https://obsproject.com/wiki/Sources-Guide#text-gdi), which only talks about plain text not structured JSON. Is there any other documentation I should be looking at?

Other alternatives are:
- set EDMC to use the [transparent theme](https://raw.githubusercontent.com/Marginal/EDMarketConnector/master/img/win_transparent.png) with "Always on top", and set OBS to use Display Capture.
- write plugin that uses [EDMC Overlay](https://github.com/inorton/EDMCOverlay) o display whatever text you want in the game window, and set OBS to use Game Capture.

**Comment by XenHat** [comment]
>  But the only reference I can find to text input sources is this, which only talks about plain text not structured JSON. 

The way most users I know do this is indeed through plain text. The software monitors the content of a file and displays it as an element. 
An example would be:
```bash
# ship_model.txt
Krait mkII
```
I could write a C# application that would parse the JSON file repeatedly and split the relevant data into several text files but I think a plugin would be much more convenient.

**EDDiscovery** has a plugin for this, so it is at least doable in some way, here's an example with system name and nearest body/fallback to system name, and universe coordinates, overlaid with a texture (another OBS element that can be added)
![image](https://user-images.githubusercontent.com/980408/61599095-54d29400-abf3-11e9-8bd1-ca5ef2024dd7.png)

**Comment by Marginal** [comment]
Please try [this plugin](https://github.com/Marginal/StreamSource) and let me know how you get on.

**Comment by XenHat** [comment]
Thank you very much!
It is pretty late and I have to head to bed but so far it seems to be working. I will spend more time reviewing this the next time I play and will post issues/improvements/suggestions on that plugin's bug tracker.

https://imgur.com/iLGZuyW

**Comment by Marginal** [comment]
Great. Please do.
