### ISSUE TITLE
Unable to Add API from INARA or EDSM due to being grayed out

### ISSUE THREAD

**Issue by Night-wing** [Marginal/EDMarketConnector#434]
I'm actually finding it a bit annoying after reinstalling this program now i cannot input my Inara OR EDSM API, its completely grayed out as shown on the screenshots I'm attaching 
![Screenshot_233](https://user-images.githubusercontent.com/9482201/61920709-240a9b80-af20-11e9-88e7-cb20b3c696ab.png)
![Screenshot_234](https://user-images.githubusercontent.com/9482201/61920710-240a9b80-af20-11e9-8589-76b27ec7f27e.png)

**Comment by Marginal** [comment]
https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#credentials-settings-are-greyed-out
