### ISSUE TITLE
Include Wine/Linux in Installation & Setup docs?

### ISSUE THREAD

**Issue by DevSolar** [Marginal/EDMarketConnector#437]
Apparently this little beauty is _capable_ of running on Wine/Linux, as commit comments indicate. I _assume_ this is meant to mean "together with Elite running via SteamPlay", i.e. "just as you would on Windows".

However, after some fumbling in the dark, I was unable to make it work.

There is nothing on how this is _intended_ to be done in [Installation & Setup](https://github.com/Marginal/EDMarketConnector/wiki/Installation-&-Setup) (or anywhere else obvious enough for me to find).

Perhaps add a section to the docs?

**Comment by Psilovybin** [comment]
it doesn't require wine to run, i'm running it just fine on gentoo linux and playing ED on steam, however i'm running into the auth issues that most people are plagued with

**Comment by Psilovybin** [comment]
You just git clone the master branch into its own dir, eun the EDMarketConnector.py with "python2 EDMarketConnector.py"  then in the configuration, point the journal logs at you ~/.local/share/Steam/steamapps/compatdata/359320/pfx/ dir whereever your logs are saved and waalaa

**Comment by DevSolar** [comment]
I did clone and run EDMarketConnector.py from the command line, I did set File / Settings / Configuration / Journal File Location to "~/.steam/steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/Local Settings/Application Data/Frontier Developments/Elite Dangerous" (after figuring out that this apparently is the right path to set it to), but I neither get any auth issues (or indeed an auth request), nor do I see my commander's info in EDMC.

And because there isn't any documentation on whether this actually _is_ the correct thing to do (which I still have doubts about since there are commit comments about "Fix running **under Wine**"), I have no idea if I did something wrong, this is a known problem, or whatever...

**Comment by Marginal** [comment]
For Wine just follow the instructions for installing and running on Windows. The default “E:D journal file location” setting is fine if you're running the app on the same machine as E:D.

**Comment by DevSolar** [comment]
I really don't want to give the impression that I am being confrontational (or dense)... but... that doesn't fly, really.

The Windows instructions state that I should "double-click" on the .msi to install. Well, I got around that via

`env WINEPREFIX=~/.steam/steam/steamapps/compatdata/359320/pfx wine EDMarketConnector_win_342.msi`

and successfully (?) installed it. But the Windows instructions continue with: "run EDMC from the Start Menu or Start Screen", which I don't have. So if I do `env WINEPREFIX=... wine .../EDMarketConnector.exe`, I either get a blocking E:D loader (if I started EDMC first), or a "wine client error / version mismatch" (if I started E:D first).

Apparently SteamPlay is using a different wine version than the system-installed one. And I have no idea how I could start EDMC in the same Wine environment as the Steam-launched E:D (or if I am again missing something obvious).

**Comment by Marginal** [comment]
I hadn't really thought about the combination of wine + Steam. To avoid the version mismatch try invoking the app with something like  `WINEPREFIX=~/.steam/steam/steamapps/compatdata/359320/pfx ~/.steam/steam/steamapps/common/Proton 4.11/dist/bin/wine .../EDMarketConnector.exe`

**Comment by DevSolar** [comment]
The concurrent running worked once I did set WINEESYNC=1 in addition to the WINEPREFIX.

However, there is no "steamuser/Saved Games". I got a "${USER}/Saved Games" (which is empty though). Searching for folders named "Elite Dangerous" I got one at "steamuser/Application Data/Frontier Developments" and one at "steamuser/Local Settings/Application Data/Frontier Developments".

Neither of those leads to my data being displayed in EDMC. I also didn't get that dreaded authentication request, not once. So something is amiss, here...

**Comment by Marginal** [comment]
The E:D journal files that this app needs are normally named like Journal.190807173331.01.log and on Windows live in the folder %USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous. But if %USERPROFILE%\Saved Games doesn't exist then E:D doesn't create the subfolders or the Journal files.
Can you find any files named Journal.*.log under ~/.steam/steam/steamapps/compatdata/359320/pfx ?

Is there a button labelled "Default" on this app's "Configuration" settings tab. If so, what is in the "E:D journal file location" box after you press the "Default" button?

**Comment by DevSolar** [comment]
No "Default" button.

Following the "from source" installation instructions and doing a `mkdir -p ~/.steam/steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/Saved\ Games/Frontier\ Developments/Elite\ Dangerous` to prep the log directory was all it took.

That on the Installation & Setup page will make a lot of people happy. ;-)

**Comment by DevSolar** [comment]
FWIW, I [added a summary in the Frontier forum](https://forums.frontier.co.uk/threads/how-to-install-ed-on-linux-using-wine-experimental-not-officially-supported.366894/post-7945953). It would still be nice if the Installation & Setup wiki page would mention the run from source / directory prep part under "Linux"...
