### ISSUE TITLE
several crashes

### ISSUE THREAD

**Issue by feiercrack** [Marginal/EDMarketConnector#439]
i got several crashes of the app during my daily playtime
since 3 weeks 

almost every hour, or shorter the prog crashes

windows 10 x64 1903  samsung ssd, 2x M.2 Corsair ssd, i7 7700k, geforce 1070, g900, g910, g933, 2 screens asus PG348Q, 34", samsung tft 24", trackir5, thrustmaster warthog hotas,

**Comment by NoFoolLikeOne** [comment]
Are  you using any plugins?

**Comment by feiercrack** [comment]
![edmc](https://user-images.githubusercontent.com/47046040/62960135-53634880-bdfa-11e9-908b-5a6c49d4b592.png)

**Comment by NoFoolLikeOne** [comment]
The crashes are probably caused by EDMC-Canonn. We are aware of this and looking for a solution

**Comment by NoFoolLikeOne** [comment]
@feiercrack  we have just delivered a new release. If you have autoupdate enabled then it should update itself.  Otherwise get it from here. Let us know how you get on

https://github.com/canonn-science/EDMC-Canonn/releases/tag/2.3.4
