### ISSUE TITLE
Non-UTF8 cmdr names

### ISSUE THREAD

**Issue by maddavo** [Marginal/EDMarketConnector#44]
Just got some non-UTF8 in the Uploader-ID via EDDN.  Any chance of filtering that out before transmitting?

**Comment by Marginal** [comment]
I thought I was doing so (or, rather, that the module that I'm using was doing so).
Can you provide a rough timestamp and station so that I can find the message on eddb and use it for testing?

**Comment by Marginal** [comment]
Did you receive [this](https://ross.eddb.io/eddn/log/6392741) message OK ?

(Note - I believe the "\u00e9" is caused by the way that eddb displays the message - my testing on a local gateway indicates that the message was correctly received).

**Comment by maddavo** [comment]
Hi - sorry - my timezone is probably way off urs.  The Uploader ID was "Knnuður" .  Quite a few came through from him/her today.  Here is one line post my parsing:
      EXPLOSIVES                           460       0     20737H          -  2015-12-05 04:37:07 # Knnuður_E:D Market Connector [Windows]_1.8.7.0

**Comment by maddavo** [comment]
Ah, I found the EDDN message...

https://ross.eddb.io/eddn/log/6392802

**Comment by Marginal** [comment]
Fixed in Release 1.88.
