### ISSUE TITLE
dark theme crashes

### ISSUE THREAD

**Issue by fishfishfish2104** [Marginal/EDMarketConnector#440]
On arch linux when enabling the dark theme it works then after i click on the window it crashes

**Comment by Marginal** [comment]
I can't reproduce using latest Arch. What does it say in the Terminal that you launched the app from?
I [documented](https://github.com/Marginal/EDMarketConnector/wiki/Running-from-source#running-from-source) running on Arch. Are you doing anything different?

**Comment by Psilovybin** [comment]
same here, running on Gentoo Linux
the console says nothing, have to control c to get out

**Comment by Psilovybin** [comment]
> I can't reproduce using latest Arch. What does it say in the Terminal that you launched the app from?
> I [documented](https://github.com/Marginal/EDMarketConnector/wiki/Running-from-source#running-from-source) running on Arch. Are you doing anything different?

doc@sal9000 ~/ed/EDMarketConnector $ python2 EDMarketConnector.py
loading plugin edsm from "/home/doc/ed/EDMarketConnector/plugins/edsm.py"
loading plugin eddn from "/home/doc/ed/EDMarketConnector/plugins/eddn.py"
loading plugin edsy from "/home/doc/ed/EDMarketConnector/plugins/edsy.py"
loading plugin coriolis from "/home/doc/ed/EDMarketConnector/plugins/coriolis.py"
loading plugin eddb from "/home/doc/ed/EDMarketConnector/plugins/eddb.py"
loading plugin inara from "/home/doc/ed/EDMarketConnector/plugins/inara.py"
Stopping monitoring Journal
^CTraceback (most recent call last):
  File "EDMarketConnector.py", line 806, in <module>
    root.mainloop()
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1135, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt
doc@sal9000 ~/ed/EDMarketConnector $

**Comment by Psilovybin** [comment]
Ran it thru PyCharm's debugger:
Exception in thread OAuth worker:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/doc/ed/EDMarketConnector/protocol.py", line 234, in worker
    self.httpd.serve_forever()
  File "/usr/lib64/python2.7/SocketServer.py", line 230, in serve_forever
    r, w, e = _eintr_retry(select.select, [self], [], [],
AttributeError: 'NoneType' object has no attribute 'select'


Process finished with exit code 1

**Comment by fishfishfish2104** [comment]
in the terminal there is no noticeable difference and it only hangs after clicking on the window this does not cause any output. I can video it happening if that would help

**Comment by fishfishfish2104** [comment]
a video of the issue in action and a screenshot of when it eventually returns an error which takes a couple of mins
[bug.zip](https://github.com/Marginal/EDMarketConnector/files/3539991/bug.zip)

**Comment by Marginal** [comment]
I can't reproduce this. But I've changed how dark mode window decorations work, so please try with latest master.

**Comment by fishfishfish2104** [comment]
seems to work fine now thanks
