### ISSUE TITLE
Not working on second PC

### ISSUE THREAD

**Issue by Nazrex** [Marginal/EDMarketConnector#441]
I am trying to run this on my second PC on my network.
I've shared ED's log file location and have this pointed to that location...
But nothing is updating and its not prompting me for my ED login when I run it; and I can not entire my Inara Key because everything on that tab is all grayed out.

**Comment by Marginal** [comment]
The app needs the location of E:D's Journal files (not log files). Which is typically `C:\Users\you\Saved Games\Frontier Developments\Elite Dangerous`.

**Comment by Nazrex** [comment]
Hmm.. ok.   I used the first one, the windows users, etc...

I think I should be using the steam play one cause I play ED through Steam... except my steamapps folder does not have a "compatdata" folder... so I'm not sure how to do this?

**Comment by Marginal** [comment]
"Steam Play" refers to Steam on Linux. You should use the first one.
See https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#credentials-settings-are-greyed-out for other reasons you can have this problem.

**Comment by Nazrex** [comment]
I got it working!
I had the log file location inputted into the wrong spot.
I had > File>Settings>Ouput -- and on that tab there is "File Location" and I thought that was where I was supposed to put in my log file location.
It was actually supposed to be in File>Settings>Configuration

I have it working correctly now!  Thank you for your help!
