### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by snuffletrumper** [Marginal/EDMarketConnector#455]
When I start EDMarketConnector it shows the station and system name in the command window then closes. The log only shows my last activity from the previous session. (I have attached anyway (note: I have just tried to open EDMarketConnector @ 23/09/2019 18:57))

To get around this is I have to remove EDMarketConnector's privileges from https://user.frontierstore.net/linked. Once I have done this it will run fine after authorising again.

[EDMarketConnector.zip](https://github.com/Marginal/EDMarketConnector/files/3643446/EDMarketConnector.zip)

**Comment by Marginal** [comment]
> The log only shows my last activity from the previous session

That's odd. If you run taskmgr are there any zombie EDMarketConnector process lying around? If so, please kill them.

**Comment by snuffletrumper** [comment]
No process at all, it exists when the program initially starts to load, then disappears completely. I have now uninstalled and removed the registry entry. Re-installed and working as expected without issue.
