### ISSUE TITLE
plugins/inara: Interdicted not always setting opponentName correctly.

### ISSUE THREAD

**Issue by Athanasius** [Marginal/EDMarketConnector#459]
Inara is complaining:

`Inara    400 Incorrect format of opponentName parameter or it is completely missing.    {"eventName": "addCommanderCombatInterdiction", "eventTimestamp": "2019-10-01T18:59:49Z", "eventData": {"starsystemName": "Nanomam", "isPlayer": true, "isSuccess": true}}`

because the Journal Interdicted event might not have `Interdictor` set (but is that a Frontier bug?).  The Inara API docs say:

`opponentName    string    Name of the target (commander or NPC). If there is no 'Inderticted' property in the journal event, use just 'Power' or 'Faction' property instead.`

so https://github.com/Marginal/EDMarketConnector/blob/master/plugins/inara.py#L618 needs adjusting to not just blindly look up the key, but check if it's set, and if needs be attempt the Power/Faction alternative.

**Comment by VAKazakov** [comment]
It is firstly EDMC bug, row https://github.com/Marginal/EDMarketConnector/blob/8c2775f6d8ea2966aa829e08d8bbe65cda712c5b/plugins/inara.py#L629 trying to set opponent name from key "Interdictor" instead of "Interdicted"

5.12 Interdiction 
When written: player has (attempted to) interdict another player or npc 
Parameters: 
 Success : true or false 
 Interdicted: victim pilot name 
 IsPlayer: whether player or npc 
 CombatRank: if a player 
 Faction: if an npc 
 Power: if npc working for power 
Example: 
{ "timestamp":"2016-06-10T14<:32:418146028378914841>03Z", "event":"interdiction", "Success":true, "Interdicted":"Fred 
Flintstone", "IsPlayer":true, "CombatRank":5 }

**Comment by Athanasius** [comment]
No, the 'Interdictor' is the name of the key in the 'Interdicted' Journal event:

`5.11 Interdicted			
When written: player was interdicted by player or npc
Parameters: 
    • Submitted: true or false
    •  Interdictor: interdicting pilot name
    • IsPlayer: whether player or npc
    • CombatRank: if player
    • Faction: if npc
    • Power: if npc working for a power

Example:
{ "timestamp":"2016-06-10T14:32:03Z", "event":"interdicted", "Submitted":false, "Interdictor":"Dread Pirate Roberts", "IsPlayer":false, "Faction": "Timocani Purple Posse"  }`

**Comment by Athanasius** [comment]
"Interdiction" gives the name of the Cmdr being interdicted, which for EDMC is always going to be "the player using EDMC", so that's irrelevant.  Inara wants the name of who initiated the interdiction, which is from the "Interdiction" event, field "Interdictor".

**Comment by Athanasius** [comment]
Wait, no, I'm wrong, and this is pure EDMC bug it seems.  Stay tuned.

**Comment by Athanasius** [comment]
Inara docs https://inara.cz/inara-api-docs/ say:

`addCommanderCombatInterdiction
Adds an 'interdiction' record to commander's combat log (when he tried to interdict someone).
Note: This event won't work without a 'commanderName' in the header set.`

So we do indeed want the Journal "Interdiction" event, not the "Interdicted" one.  So this is https://github.com/Marginal/EDMarketConnector/blob/master/plugins/inara.py#L623-L634

**Comment by VAKazakov** [comment]
Blame fd for doubling key names with event names))))

**Comment by Athanasius** [comment]
So, yes, that line 629 in d8b5884 should read:

`data['opponentName'] = entry['Interdicted']`

**Comment by Athanasius** [comment]
> Blame fd for doubling key names with event names))))

Blame the English language for the words being very similar ;).
