### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by btknight** [Marginal/EDMarketConnector#464]
I downloaded and ran the MSI package, however Windows reports unknown publisher.  A digital signature with a valid certificate should be included with the software release.
![EDMC](https://user-images.githubusercontent.com/12056795/67607606-b18d9f80-f74a-11e9-9b39-afe0eca933f7.png)

**Comment by Marginal** [comment]
Unfortunately obtaining a certificate for use with Microsoft's Authenticode is tedious and expensive for an individual developer, involving phone calls and notaries. For the "Extended Verification" version that gets rid of the above dialog it's [$319](https://comodosslstore.com/codesigning.aspx) / year.

Marking this as "wont fix" unless anyone wants to volunteer $319.
