### ISSUE TITLE
No authentication page request, app just hangs

### ISSUE THREAD

**Issue by hack-wizard** [Marginal/EDMarketConnector#470]
The app is not popping the FDEV auth page and this is a brand new install, please explain how I can force a manual link (I know this can be done).  Already tried revoking auth as well, to no avail, it simply is failing to launch the browser (Vivaldi).  I also changed my default to Edge, and the same thing happened so I know that isn't the issue...  Log doesn't tell me anything.

[EDMarketConnector.log](https://github.com/Marginal/EDMarketConnector/files/4000757/EDMarketConnector.log)

**Comment by hack-wizard** [comment]
I was able to find the link on my other computer ... but it's still unresponsive.  Is this possibly a perms issue of some sort?  Tried running it as admin but to no avail.   OS is Win10 build 1809

**Comment by hack-wizard** [comment]
Just noticed it is saying "Invalid credentials" but I know that what I put in is completely valid, so something is either causing the auth to be delivered in a malformed format, or Frontier has changed things ... the latter makes no sense as it works on my other computer.  Is there a way to "hard code" the auth, or at least manually force it on a low level?

**Comment by Marginal** [comment]
https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#credentials-settings-are-greyed-out ?

**Comment by hack-wizard** [comment]
I'm pretty sure I signed in and was on the pad when I tested.
Also confirmed I used the correct journal file location.

**Comment by hack-wizard** [comment]
So it looks like simply being on the pad is not enough, had to launch to get it to work, perhaps you should update the instructions for this? :)
