### ISSUE TITLE
3.4.3.0 demandBracket is empty

### ISSUE THREAD

**Issue by Patsch78** [Marginal/EDMarketConnector#494]
Hi, when buyPrice is 0 and demand is 0, then demandBracket is an empty String. Regarding the Eddn schema it should be any levelType.

`           }, {
                "buyPrice": 0,
                "demand": 0,
                "demandBracket": "",
                "meanPrice": 791,
                "name": "liquor",
                "sellPrice": 892,
                "stock": 0,
                "stockBracket": 0
            }, {
`
Full Message:

[Bug01.txt](https://github.com/Marginal/EDMarketConnector/files/4668724/Bug01.txt)

**Comment by Athanasius** [comment]
The schema definition includes "" in the levelType definition: https://github.com/EDSM-NET/EDDN/blob/master/schemas/commodity-v3.0.json

**Comment by Patsch78** [comment]
Oh my gosh, how could I read over this!? Sorry.
