### ISSUE TITLE
Is all the data being sent to EDDN?

### ISSUE THREAD

**Issue by rcthelp** [Marginal/EDMarketConnector#5]
Over 70% of the time I do an update, the status bar at the bottom will freeze part way through the EDDN send, normally in the mid 20's for a station with more than 50 commodities.

**Comment by Marginal** [comment]
You can see the messages [here](http://ross.eddb.io/eddn/log)

**Comment by rcthelp** [comment]
OK thanks, so that error log shows that EDMarketConnector 1.3.4 is not sending Osmium or Sap 8 Core Container data. Does that cause it to stall with the remainder?

**Comment by rcthelp** [comment]
Oh ignore me. That's EDDN not accepting it *facepalm*

**Comment by Marginal** [comment]
Actually it's showing that eddbi.io is not accepting those commodities - the author has been on holiday since before 1.3 and hasn't updated.
The display freeze will be fixed in version 1.40.

**Comment by rcthelp** [comment]
Thanks for the update.
