### ISSUE TITLE
Does this send more than just trade data to EDDN?

### ISSUE THREAD

**Issue by rcthelp** [Marginal/EDMarketConnector#50]
Does this app send:

station capability (e.g. Refuel, Rearm, Outfitting)?
details of modules in outfitters?
ships for sale in shipyards?

If the station does not exists in EDDN (I'm thinking all these ground bases), does EDDN accept the updates, or does something else have to be sent first?

IS all of this stored locally in a file as well as being sent? (I know the price data is).

**Comment by AnthorNet** [comment]
Yes EDDN receives commodities, shipyard and outfitting.

Sadly there is no information about the status of the station.

**Comment by Marginal** [comment]
If the station doesn't exist it's up to each consumer of the data to decide what to do. Currently EDDB ignores data for non-existent stations, but IIRC the maintainer has in the past automatically created a new station.
