### ISSUE TITLE
API server is up after Horizons release, getting an error message

### ISSUE THREAD

**Issue by rcthelp** [Marginal/EDMarketConnector#51]
DAta is not sent to EDDN, there's a 'capacity' message instead.

![image](https://cloud.githubusercontent.com/assets/8623605/11929525/c911b9ae-a7d3-11e5-949a-f236eedefcbc.png)

**Comment by bigblock116** [comment]
second on this issue. Glad the server is up though.

Also not generating a .csv file.

**Comment by AnthorNet** [comment]
Odd thing, It works well on my computer.
Try to remove export to coriolis the time it is being investigated.

**Comment by rcthelp** [comment]
With just the export to EDDN and make .prices file, it's working.

Maybe ship loadout export is not supporting planetary stuff?

**Comment by bigblock116** [comment]
Removing the export to coriolis fixes the capacity issue... however, now it's showing that I'm not docked when I am...

**Comment by RatSalad59** [comment]
+1 for unticking Coriolis and ED Shipyard, working again after.

**Comment by TinyBigJacko** [comment]
+1 for unticking ED Shipyard (I didn't have Coriolis format set). I'm guessing this is to do with a new ship feature from 1.5 (capacity). Props to the person who discovered the temporary workaround though - nice one AnthorNet, thanks.

**Comment by riddler2kone** [comment]
I always get the message "Error: Can't get market data!".

**Comment by RatSalad59** [comment]
Actually it's just the ED Shipyard that's causing the 'capacity' error I've just ticked Coriolis and it updated as normal

**Comment by Marginal** [comment]
Fixed in bfcd701 and Release 2.00.

**Comment by Marginal** [comment]
> I always get the message "Error: Can't get market data!".

See Issue #6. Is this at an Outpost or a Planetary Base or what?
