### ISSUE TITLE
Settings screen too tall for some laptop resolutions

### ISSUE THREAD

**Issue by TinyBigJacko** [Marginal/EDMarketConnector#53]
I'm currently running EDMC on a laptop with a native 1366 x 768 screen resolution, and the EDMC app is almost too tall to be able to fit into that screen under Windows 10. Probably the same in all Windows versions, I expect. It will *just* squeeze in and can be dragged up to reach the very tippy-top of the OK button when making changes, but it's a pain in the neck to move around (even using keystrokes and tab-presses to reach hidden boxes).

It'd be really useful if the screen's layout could be auto-resized, or reflowed onto a two-column, wider dialog-window, if at all possible.

Certainly if the screen height gets any taller, it will become impossible to use with a mouse, so please bear this in mind!

Thanks for an otherwise excellent and helpful app. Much appreciated.

**Comment by Marginal** [comment]
Yes I'm struggling to keep it under 768, and will have to re-design if I add any more options.

**Comment by inorton** [comment]
In my fork I've collapsed the authentication entries into tabs so might ease this problem

**Comment by Marginal** [comment]
Fixed in Release 2.02
