### ISSUE TITLE
Meta Alloys vs Meta-Alloys

### ISSUE THREAD

**Issue by rcthelp** [Marginal/EDMarketConnector#55]
In the game market and on EDDN this new commodity contains a hyphen. TradeDangerous is displaying it as Meta-Alloys.

But the .prices file produced by this tool removes the hyphen, and importing into Trade Dangerous, the file fails.

**Comment by rcthelp** [comment]
It also outputs SKIMER COMPONENTS

**Comment by Marginal** [comment]
Should be fixed in d188a22 and Release 2.00. Please upgrade.
