### ISSUE TITLE
Not Automatically Tracking New Systems Entered

### ISSUE THREAD

**Issue by tententacles** [Marginal/EDMarketConnector#58]
Previous to Horizons and the EDMC 2.0 update, EDMC would keep track of new systems when I jumped into them. It doesn't appear to be doing it now. I suspect it's probably looking at the wrong netLog file, but I cannot see anywhere to change it. Is there a place to update it? Is this what is happening?

**Comment by Marginal** [comment]
Check that you have "Automatically make a log entry on entering a system" selected in Settings.

Do you have horizons, and which option are you running from the Elite Dangerous Launcher?

**Comment by tententacles** [comment]
I do have it checked. And I'm running the Elite Dangerous: Horizons (64-BIT) option from the Launcher.

**Comment by Marginal** [comment]
EDMC looks for the folders `elite-dangerous-64` then `FORC-FDEV-D-1xxx` in the Products folder under the launcher (usually C:\Program Files (x86)\Frontier\EDLaunch\Products). It expects them to contain the file AppConfig.xml and a Logs subfolder.

If it doesn't find either folder under the launcher it looks for them in:
1. C:\Program Files (x86)\Steam\steamapps\common\Elite Dangerous\Products
2. C:\Program Files (x86)\Frontier\Products
3. %LOCALAPPDATA%\Frontier_Developments\Products

And stops on the first match.

Is it possible that you have old copies of E:D lying around? What copies of the two games do you have and where?

**Comment by tententacles** [comment]
Yep, that was the problem. I'd initially installed the game through Steam, but then moved to the stand-along launcher for Horizons. I deleted the game from Steam, and its associated directory, and everything is working fine now. Thanks!

**Comment by Marginal** [comment]
Hmm, I'd considered people migrating *to* Steam, but not people migrating away *from* Steam!
Glad you have it working now.

**Comment by Marginal** [comment]
Fixed in Release 2.01
