### ISSUE TITLE
No auto detect system (Horizons Steam)

### ISSUE THREAD

**Issue by SavageCore** [Marginal/EDMarketConnector#59]
Steam version of ED: Horizons does not auto detect system.

It is in a new folder `Elite Dangerous Horizons` and the only product is `elite-dangerous-64`

Also worth nothing for the Steam base game I have `FORC-FDEV-D-1010` as a product not `FORC-FDEV-D-1` that `monitor.py` is looking for?

**Comment by Marginal** [comment]
What's the full path of the Logs folder?

**Comment by SavageCore** [comment]
E:\Program Files\Steam\SteamApps\common\Elite Dangerous Horizons\Products\elite-dangerous-64\Logs

**Comment by Marginal** [comment]
Thanks. Looks like I'll have to revamp my detection algorithm.

Can you confirm that you installed Steam into E:\Program Files\Steam, and that the registry key HKEY_CURRENT_USER\Software\Valve\Steam\SteamPath also points to this folder ?

**Comment by SavageCore** [comment]
Yes can confirm both of those but I've actually fixed it by uninstalling Elite: Dangerous from Steam and changing `monitor.py` as you can see from my commit, shall I pr?

**Comment by Marginal** [comment]
Thanks.
No the the PR thanks - I have some uncommitted changes, and I really should read that regsitry key to find Steam's location, rather than assume that it's under %ProgramFiles(x86)%.

**Comment by Marginal** [comment]
Fixed in Release 2.01
