### ISSUE TITLE
App doesn't save outfitting and shipyard data locally.

### ISSUE THREAD

**Issue by georgehank** [Marginal/EDMarketConnector#60]
Only the command-line part optionally does, and I couldn't find a rationale for this difference.  I'd like to have everything locally too, and was actually surprised it didn't.

**Comment by Marginal** [comment]
There isn't really a rationale.

**Comment by georgehank** [comment]
I'm hacking away at this, right now just dumping Python dicts to some files just so I have the data locally in case I want to play and some servers are down.

**Comment by Marginal** [comment]
Or just make the same calls that EDMC.py does.

**Comment by georgehank** [comment]
I have something, but I need to do another pass.  My first stab is in the "pydump" branch of my fork, if you want to have a look.

**Comment by inorton** [comment]
sounds like you might like my plugin branch?

**Comment by Marginal** [comment]
Closing since this seems like a feature with quite narrow demand, and the [plugins](https://github.com/Marginal/EDMarketConnector/blob/master/PLUGINS.md) mechanism mentioned by inorton above and included in Release 2.05 provides an alternative way to achieve it.
