### ISSUE TITLE
EDMC writes VerboseLogging=1 into AppConfigLocal.xml every time it runs

### ISSUE THREAD

**Issue by rcthelp** [Marginal/EDMarketConnector#62]
I use EDMC with TDHelper.

TDHelper does not like it when there is more than one VerboseLogging=1 entry in the config file.

EDMC seems to write a new entry every time it runs.

**Comment by Marginal** [comment]
> EDMC seems to write a new entry every time it runs.

Sounds like EDMC doesn't like something about your AppConfigLocal.xml file. Please attach it below.

Here's mine, which EDMC doesn't re-write every time it runs:
[AppConfigLocal.xml.zip](https://github.com/Marginal/EDMarketConnector/files/70659/AppConfigLocal.xml.zip)

**Comment by rcthelp** [comment]
Don't seem to be able add a zip file.

<?xml version="1.0" encoding="utf-8"?>
<AppConfig>
  <Network
		VerboseLogging="1"
	/>
</AppConfig>

**Comment by Marginal** [comment]
That file is syntactically incorrect. Use the file I attached and edit or edit out the port and unp settings as required.

**Comment by rcthelp** [comment]
It pasted badly

<?xml version="1.0" encoding="utf-8"?>
<AppConfig>
  <Network
		VerboseLogging="1"
	/>
</AppConfig>

**Comment by rcthelp** [comment]
Ang again. Peculiar. Syntactically, it is correct.

![image](https://cloud.githubusercontent.com/assets/8623605/11977414/8a1b644a-a97a-11e5-8b66-e9f198b9a8fe.png)

**Comment by Marginal** [comment]
It's not the formatting, it's the content that's invalid. See my file.

**Comment by rcthelp** [comment]
I think I know what's happened here. TDHelper has 'corrupted' the file adding the Verbose Logging line and a shorthand syntax. I've edited it by hand to make it more strict, and now your prog is not adding another entry.

**Comment by Marginal** [comment]
Glad you have it working now.
