### ISSUE TITLE
Not Automatically Tracking New Systems Entered (Operating System-Language specific?)

### ISSUE THREAD

**Issue by Coruin** [Marginal/EDMarketConnector#63]
I know there was a recent ticket about this issue. In my case the reason for this seems to be that my Elite Dangerous (no Steam) isn't located in "Program Files (x86)". Instead it is installed into "Programme (x86)". See attached screenshot.

Maybe it is possible to add an option to tell the Connector where the installation and/or the logs are saved. This way any kind of "non-default" installations can be recognized manually :)

![elite dangerous log location](https://cloud.githubusercontent.com/assets/13752163/11997801/2daad836-aa87-11e5-9330-272b1e703c29.png)

**Comment by Marginal** [comment]
That folder contains the launcher's logs. The game client's logs live somewhere else. I've added a [Troubleshooting](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting) section to the wiki that explains where EDMC looks for the game client's logs.

**Comment by Coruin** [comment]
You are right, I got the wrong folder there. To be precise: I grabbed the wrong folder for the screenshot.

However, the path doesn't change much as you can see with the correct screenshot.

![image](https://cloud.githubusercontent.com/assets/13752163/12003977/ab348e50-ab36-11e5-86bb-41e1a3be8aba.png)

**Comment by Marginal** [comment]
EDMC gets the launcher's location from the Windows registry (specifically from the uninstallation info). So the fact that you're running a Non-English (German?) version of Windows shouldn't matter.

Some questions:
- do you see the "Automatically make a log entry on entering a system" option in EDMC's settings? And have you selected it?
- do you have any other copies of Elite Dangerous or Horizons installed?

**Comment by Coruin** [comment]
The option is there and when checking it, it gives the error message:
![image](https://cloud.githubusercontent.com/assets/13752163/12006035/b6b808a0-abc3-11e5-8729-6051d0d88864.png)

I have no other copies installed. I removed the beta and the 32-bit version after I installed Horizon.


by the way: Merry Christmas ;)

**Comment by Marginal** [comment]
It would have saved time if you had mentioned the error message to start with.

For some reason, probably file permissions, EDMC is unable to edit your AppConfig.xml file. The simplest solution is for you to edit this file and add the required [VerboseLogging](https://forums.frontier.co.uk/showthread.php?t=94977) value yourself. Then (re)start the game.

**Comment by Coruin** [comment]
Sorry for not mentioning the error message in the beginning. I thought I did.

I used to run a programm which added the verboselogging to the appconfig. For some reason it didn't do it last time I ran it... Well, manually adding it fixed the problem :)

**Comment by Marginal** [comment]
Glad it's working now.
