### ISSUE TITLE
Question: Does the companion API support the planetary stations on planets in Horizons?

### ISSUE THREAD

**Issue by wolverine2710** [Marginal/EDMarketConnector#65]
Haven't played ED in  a while and curious if the iPhone API does support horizons, as in the stations/outposts/markets introduced with horizons? I post it here because you don't have a thread on the forums. I need the info for a post. I apologize for a possible  abuse of github...

**Comment by Marginal** [comment]
Yes, the API returns the same info for planetary ports and outposts as for space ones (and with the same bugs - e.g. Reporting spurious shipyards). eddb already has a number of them in its database.

**Comment by wolverine2710** [comment]
Thanks a lot for the swift response ;-) I'm gonna close this one.
