### ISSUE TITLE
Automatic Commodities Entry

### ISSUE THREAD

**Issue by Devlah** [Marginal/EDMarketConnector#66]
I noticed that there are options to automatically log and submit data to Elite Dangerous Starmap.  Any chance something similar could be done when we dock at stations and submit commodity data without having to press the "Update" button?

**Comment by Marginal** [comment]
No. To do so would require polling Frontier's servers, say every 10 seconds. I don't think they'd be happy about that.

The best that you can do is to set up a hotkey and get in the habit of pressing it after docking.
