### ISSUE TITLE
Unable to use a particular Shift key combination.

### ISSUE THREAD

**Issue by camelman912** [Marginal/EDMarketConnector#68]
Before the last update I had Shift+F11 mapped as a hotkey.

After the update, I'm unable to use the same mapping. I am able to program Shift+F1 thru F10, but F11 and F12 won't program. 

I will be changing my mapping, but I thought it was worth mentioning.

**Comment by Marginal** [comment]
You can't use F12, with any combination of modifiers or none. This is a Windows [limitation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646309) - "Even when you are not debugging an application, F12 is reserved in case a kernel-mode debugger or a just-in-time debugger is resident".

You should be able to use F11 or Shift F11 providing that no other app has grabbed it first. Do you have another copy of this app running?

**Comment by Marginal** [comment]
This should be fixed in Release 2.02, but only after you've rebooted. Please re-open if not.
