### ISSUE TITLE
request: instructions on how to run this on linux...

### ISSUE THREAD

**Issue by lemmy04** [Marginal/EDMarketConnector#7]
...that way I could run the app on my laptop that I use for browsing eddb.io and similar sites as I fly.

**Comment by Marginal** [comment]
I've clarified the [Running from source](https://github.com/Marginal/EDMarketConnector#running-from-source) section of the README.

I haven't tested extensively on Linux - please let me know how you get on.

**Comment by lemmy04** [comment]
crashes on start:

mathias@kirika:~/EDMarketConnector-rel-140> ./EDMarketConnector.py 
Traceback (most recent call last):
  File "./EDMarketConnector.py", line 16, in <module>
    import companion
  File "/home/mathias/EDMarketConnector-rel-140/companion.py", line 17, in <module>
    from config import config
  File "/home/mathias/EDMarketConnector-rel-140/config.py", line 230, in <module>
    config = Config()
  File "/home/mathias/EDMarketConnector-rel-140/config.py", line 198, in __init__
    self.config.add_section('DEFAULT')
  File "/usr/lib/python2.7/site-packages/iniparse/compat.py", line 59, in add_section
    raise ValueError, 'Invalid section name: %s' % section
ValueError: Invalid section name: DEFAULT

**Comment by Marginal** [comment]
Sorry about that. Fixed in b96c5bc88b.
Please try with the [current source code](https://github.com/Marginal/EDMarketConnector/archive/master.zip).

**Comment by lemmy04** [comment]
It also needs python-Pillow-tk, then it starts. let's see if it works, too, i just had 1.40 RC1 simply not sending data (on windows), had to rollback to 1.34.

**Comment by lemmy04** [comment]
works fine! thanks for this!

**Comment by Marginal** [comment]
Thanks - have updated the dependencies in the README.

1.40 *is* sending data - just in a form that eddb.io does not yet understand. That's why 1.40 is still a pre-release.
