### ISSUE TITLE
problem in using the soft

### ISSUE THREAD

**Issue by grems1** [Marginal/EDMarketConnector#70]
Hello,

I'm running m'y computer with Windows10 and avast. When I try to open ED Market connecter a Windows open les 1 second and the close automatically.

I try to open edmc as an admin, to stop avast but at this time I never can use edmc 😞.

Can somebody help me?

I wish you the best for the new year.

**Comment by Marginal** [comment]
Try disabling avast and re-installing the latest release of EDMC.
Running EDMC as admin is unlikely to help.

**Comment by grems1** [comment]
I try but... it dont works :-(

**Comment by Mirtma** [comment]
I have same problem. Windows 10 64 bit, ESET Endpoint Antivirus.

**Comment by Marginal** [comment]
Please open the file `%TMP%\EDMarketConnector.log` and paste the contents (if any) here.

**Comment by Mirtma** [comment]
Traceback (most recent call last):
  File "EDMarketConnector.py", line 496, in <module>
  File "EDMarketConnector.py", line 187, in __init__
  File "prefs.pyo", line 139, in __init__
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9e in position 14: ordinal not in range(128)

**Comment by Marginal** [comment]
Please try [this version](https://github.com/Marginal/EDMarketConnector/releases/tag/rel-203) and let me know how you get on.

**Comment by grems1** [comment]
It's OK for me. It works...

Thanks

**Comment by Marginal** [comment]
Glad it works now.

**Comment by Mirtma** [comment]
Yes, it's working. Thank you!
