### ISSUE TITLE
Mac: Changing Storage location

### ISSUE THREAD

**Issue by BarryCarlyon** [Marginal/EDMarketConnector#73]
If I use preferences to change as shown:

<img width="448" alt="preferences" src="https://cloud.githubusercontent.com/assets/20999/12080481/73b24a02-b253-11e5-8674-8a10632c23a9.png">

Results in:

<img width="750" alt="e_d_market_connector" src="https://cloud.githubusercontent.com/assets/20999/12080482/897a145a-b253-11e5-8316-a6bbdfad2b68.png">

And on reopen of Prefs:

<img width="448" alt="preferences" src="https://cloud.githubusercontent.com/assets/20999/12080484/91c0e1a2-b253-11e5-9200-4d02f18eebea.png">

**Comment by BarryCarlyon** [comment]
Oh and when I restart the App is resets to ~/Documents

I'd go in and haxor the prefs file manually but I am unfamilar with python and I have no idea where it's writing prefs to :-P

**Comment by Marginal** [comment]
Oops. Fixed in Release 2.04.

**Comment by BarryCarlyon** [comment]
Can confirm the fix is good.
