### ISSUE TITLE
Not updating EDSM with all visited systems

### ISSUE THREAD

**Issue by Dariuas** [Marginal/EDMarketConnector#76]
Images of my EDMC setup for EDSM.

EDSM only gets updated when I click update, and it only updates the current system I am in, it does not display previous systems. 

I am 7000ly from SOL and EDSM shows 30 systems.

![edsm](https://cloud.githubusercontent.com/assets/927002/12214544/1ac26366-b666-11e5-9bde-79200df1c4f3.PNG)

![image](https://cloud.githubusercontent.com/assets/927002/12214546/24418264-b666-11e5-8dc5-88baf91229be.png)

**Comment by Marginal** [comment]
The app is probably picking up the wrong E:D installation - see [here](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#doesnt-track-systems-visited).
Which copies of E:D Season 1 and Horizons do you have installed and where?

**Comment by Dariuas** [comment]
I have both 1.5 and 2.0 installed through Steam
C:\Program Files (x86)\Steam\steamapps\common\Elite Dangerous Horizons
C:\Program Files (x86)\Steam\steamapps\common\Elite Dangerous

**Comment by Marginal** [comment]
And you're playing 2.0 ?

**Comment by Dariuas** [comment]
Yea

**Comment by Marginal** [comment]
Please try [this](http://marginal.org.uk/EDMarketConnector_win_205b0.msi) pre-release; it has some changes around Log file detection. Note you don't have to jump system - just dropping out of supercruise should be enough for EDMC to detect your system.

If that doesn't work, please open %TMP%\EDMarketConnector.log and see ehat (if anything) it says.

**Comment by Dariuas** [comment]
Sorry, my home got destroyed by a tornado, so I have not had time to get this going. :(

I'll let you know once I am back on my feet.

**Comment by Marginal** [comment]
Yow. Sorry to hear that.

**Comment by Dariuas** [comment]
Thanks its a rough road right now.
