### ISSUE TITLE
597,592 seconds cooldown...

### ISSUE THREAD

**Issue by Limeliz** [Marginal/EDMarketConnector#77]
Program wouldn't update when I pressed update. When I restarted I had a cooldown of 597,592 seconds. That's a week! What happened?!

![image](https://cloud.githubusercontent.com/assets/5267867/12224270/b95f6942-b7ec-11e5-88a6-9534c8da2ce4.png)

**Comment by Marginal** [comment]
Is there something weird about the clock on your computer?

You can reset the cooldown time by quitting the app, running regedit, and navigating to and deleting the key HKEY_CURRENT_USER\Software\Marginal\EDMarketConnector\querytime

**Comment by Limeliz** [comment]
Yes, you're right. You can close this.

I changed my date back a week to run a software that had a trial time that just ran out. :-P

**Comment by Marginal** [comment]
> I changed my date back a week to run a software that had a trial time that just ran out.

Naughty, naughty !
