### ISSUE TITLE
Sound when EDSM is offline

### ISSUE THREAD

**Issue by rcthelp** [Marginal/EDMarketConnector#79]
IMO it would be better if the noise that EDMC makes when entering a system, but EDSM is offline was NOT the noise of shields going off/online. :) Or was a setting that could be switched off.

**Comment by Marginal** [comment]
It's actually borrowed from the Mercenary Edition "Ringtones & Message Alerts" bonus extras. Though it does sound similar.
Get's your attention, doesn't it!
