### ISSUE TITLE
[REQUEST] Add ship vendor functionality

### ISSUE THREAD

**Issue by rcthelp** [Marginal/EDMarketConnector#8]
Any plans for this? I assume it's possible, given that the companion app can display it?

**Comment by Marginal** [comment]
Shipyard and Outfitting are in progress in the [outfitting branch](https://github.com/Marginal/EDMarketConnector/tree/outfitting).
But it depends on EDDN settling on message schemas, which are being discussed [here](https://github.com/jamesremuscat/EDDN/issues/16) for shipyard and [here](https://github.com/jamesremuscat/EDDN/issues/20) for outfitting. And then on EDDN subscriber websites and tools to display this info.

**Comment by rcthelp** [comment]
Thanks for the response. ShipVendor would certainly be welcome in  .csv format for upload to maddavo, while EDDN v2 schema is sorted.

**Comment by Marginal** [comment]
Leaving open until resolved
