### ISSUE TITLE
Entering a Training Mission triggers EDSM distance entry

### ISSUE THREAD

**Issue by Athanasius** [Marginal/EDMarketConnector#81]
I just popped into the 'Target Practice' Training scenario and was surprised when EDMC caused http://www.edsm.net/show-system/index/id/112308/name/Training to open in my browser.

That specific scenario caused the following in the netLog:

{14:14:38} System:28(Training) Body:7 Pos:(1.08967e+007,833.411,5.93693e+006) NormalFlight

**Comment by Marginal** [comment]
Fixed in Release 2.06.
