### ISSUE TITLE
Add EDProxy support

### ISSUE THREAD

**Issue by andrewgoz** [Marginal/EDMarketConnector#82]
I run EDMC on a different computer to ED. I currently use EDProxy to keep EDSM updated. Could EDMC also use EDProxy as an alternative to looking at the log files (which aren't on my EDMC computer) to keep track of when I change systems?

FYI: https://bitbucket.org/westokyo/edproxy/overview

**Comment by wolverine2710** [comment]
You seem to made a typo somewhere in the url. I've digged up edproxy in in edcodex. That link does work. The author uses edproxy in his own tool: AndDiscovered - Android exploration tracking tool modeled after EDDiscovery.

*Urls*
EDProxy - Netlog proxy server
http://edcodex.info/?m=tools&entry=255
https://bitbucket.org/westokyo/edproxy/overview

AndDiscovered - Android exploration tracking tool modeled after EDDiscovery.
http://edcodex.info/?m=tools&entry=254

Btw. EDproxy is a VERY promising tool.

**Comment by Marginal** [comment]
Please this version: [Windows](http://marginal.org.uk/EDMarketConnector_win_206b1.msi) [Mac](http://marginal.org.uk/EDMarketConnector_mac_206b1.zip).

It should pick up edproxy on a mchine on the same subnet. The edproxy connection is shown on the Output and EDSM tabs in settings.

**Comment by andrewgoz** [comment]
I've just downloaded 2.0.7 and found you've added this already! Thanks!
