### ISSUE TITLE
Upload Trade Data upon docking - Enhancement

### ISSUE THREAD

**Issue by chrismartinau** [Marginal/EDMarketConnector#83]
Firstly, thanks for this amazing tool! It has changed both these ease of submissions and quality of submissions to the various databases. Fantastic!

I would like an option to submit market data when you dock. EDMC currently supports uploading on H-jump, so I assume it shouldn't be that hard to add an option to trigger an upload as you dock, perhaps with a configurable delay to ensure that the servers see you as docked. Is this as simple as I think it is, or would docking be harder to detect than hyperspace jumps?

Thanks!

**Comment by AnthorNet** [comment]
The docking process was in the log before, but is not anymore.
So little tricky to do ;)

Now, maybe it will be back soon, we'll see.

**Comment by stefanmohl** [comment]
This is what the hotkey button in EDMC is for. Once you are docked, you hit the hotkey to initiate an upload.

**Comment by chrismartinau** [comment]
stefanmohl,

Yes, I understand that. I have programmed the hotkey, and I use it. The problem is the _remembering_ to use it.

Hopefully the logs will at some point include docking; or maybe, some day, we'll get an API.

**Comment by stefanmohl** [comment]
Yes, I agree, it would have been a lot nicer if it were in the logs. The hotkey is a workaround, but it _does_ help. Though fully automatic would have been nicer...

**Comment by delfer** [comment]
Can I modify sources to update on timer, every minute, for example? Does it cause any problems, like ban?

**Comment by Marginal** [comment]
@delfer
Frontier haven't defined what they consider acceptable use of their API. But polling every minute might be pushing it.

**Comment by inorton** [comment]
We could perhaps adapt the analysis of the netlog. When i was working on my "channel 16" project I was able to work out when I entered a station instance (but not necessarily when I landed).

**Comment by inorton** [comment]
Maybe bind EDMC to the same key as landing gear and then to wait 2 minutes?

**Comment by stefanmohl** [comment]
Hey! That's a good idea! As long as EDMC doesn't swallow up the keypress, but passes it along to Elite so that both Elite and EDMC can react, then checking for station data a configurable time after toggling landing gear could work! (Configurable to find a suitable setting depending on pilot landing habits, i.e. extend landing gear to slow down for station entry vs extend landing gear at last moment.) It will give an unneeded request on take-off, but that won't be so bad, not even close to what any sort of relevant poll would give!

**Comment by delfer** [comment]
Lots of pilots (include me) use joysticks.

**Comment by stefanmohl** [comment]
Yes, I do too. EDMC needs to implement a joystick interface for this to work well for everybody. Still, a hotkey solution connected to the landing gear will at least help some!

**Comment by delfer** [comment]
Polling would be better, I think.
But "Delayed update" is alternative feature, what must be implemented.
