### ISSUE TITLE
'Skinning' Options

### ISSUE THREAD

**Issue by msteele9999** [Marginal/EDMarketConnector#84]
Marginal,

Long time fan and user of EDMC.

Enhancement request: ability to change the color or opacity of the app window - I run E:D in a dark environment and the app shines like a beacon :-)

**Comment by Marginal** [comment]
Opacity is tricky. But a "dark" mode should be do-able.

**Comment by Marginal** [comment]
Added "Dark" theme in Release 2.07.

**Comment by msteele9999** [comment]
Excellent.  Thank you

**Comment by msteele9999** [comment]
Jonathan,

Excellent job. Looks really good.

**Comment by DAOWAce** [comment]
Has some weird painting effects when you drag it around, but otherwise, that was really quick and nice.

**Comment by Marginal** [comment]
> Has some weird painting effects when you drag it around, but otherwise, that was really quick and nice.

Yes, the redraw is not very smooth. Don't think I can fix that with the toolkit I'm using.
