### ISSUE TITLE
Shipyard/ship stations data only on second attempt/update

### ISSUE THREAD

**Issue by djadjok** [Marginal/EDMarketConnector#86]
Don't know if its already reported and if this is a ED API glitch or some edmc problem but I noticed that frequently the "ship" data is only transfered on second update to eddn
Examle: update hisrory on eddb for Furuta dock - https://ross.eddb.io/station/update/39700 (only commodity/outfitting were updated after first visit)

**Comment by Marginal** [comment]
It's an API bug - sometimes the shipyard data is missing. In which case EDMC retries, but sometimes it's missing from the second try too.
Going into the shipyard in game before hitting "Update" usually causes the shipyard data to be present.

**Comment by djadjok** [comment]
Thanks, pity I'm always tend to forget to recheck if ships data is present, and this situation with ED API is more like a rule than an exception :(

**Comment by Marginal** [comment]
This appears to be fixed, so closing.
