### ISSUE TITLE
Feature Request: Raw Dump File

### ISSUE THREAD

**Issue by Sharlikran** [Marginal/EDMarketConnector#87]
First I'm sorry I'm not trying to make your issue tracker a forum, I just don't know where to ask.  

I saw the -l, -m, -o, -s, -t that will write a CSV file but I am wondering if I run the python version from a command line can EDM save the information from the API exactly as it is before you parse it and save it as a CSV file or tradedangerous file?

For example: 094142434445464746480004F95DAB07
Instead of: ABCDEFGFH, 0x07AB5DF9 or 128671225

**Comment by Marginal** [comment]
I don't understand you example.

What are you wanting to do with the data?

**Comment by Sharlikran** [comment]
![rawformat](https://cloud.githubusercontent.com/assets/1912426/12856243/ce1593aa-cbf8-11e5-859e-8b5494970fc7.jpg)

I am looking for the actual raw data directly from the API in binary format.  You can't load binary data in a text editor but I give a screen shot above of what it would look like.  I want the raw data as is with all the length bytes for the strings, length bytes for the 32 and 64 bit integers and everything before you parse it and save it as Json. csv, or tradedangerous format.

I am trying to troubleshoot the error `<tradedb.Station object at 0x0494D6C0>` in tradedangerous and I suspect it is because some Horizons information isn't added.  So rather then bug you with a lot of questions about a program you did not write I just wondered if I can get the raw data as it comes from the API so I can look at it myself.

**Comment by Marginal** [comment]
The Companion API that this app uses returns its data in .json format.
Perhaps you're talking about some other API?

**Comment by Sharlikran** [comment]
I was thinking the "Companion API" is the same API for all programs and provided by Frontier for author's like yourself.  Don't programs like EDM call EliteDangerous64.exe or something?  I provide my elite login and password and you use it to call some kind of API.  What API are you accessing?  Once you get the response from the API then you save it as a .json file.  I'm wanting the raw data from the Elite API before you format it and save it as a .json file.

**Comment by Marginal** [comment]
The Companion API that this app uses returns its data in .json format.

**Comment by Sharlikran** [comment]
Oh, okay, the Companion API you use will only save it in [json format](http://pastebin.com/3TP1EcJj) like I show in the Pastebin link?

**Comment by Sharlikran** [comment]
Anyway.  I am sorry to bother you.  Like I said I didn't want to treat your issue tracker like a forum.  I was excepting the API to be more like a C++ wrapper and I call a DLL file or something else.  

I apologize.  Thanks for answering my questions.
