### ISSUE TITLE
Error: Can't connect to EDSM

### ISSUE THREAD

**Issue by Juddz** [Marginal/EDMarketConnector#88]
Hi mate, great app and I had it working before but now I've set it up for my other account, it gives me this message: Error Can't connect to EDSM.

I have used a © in my commander name and when I type alt+0169 into the market data app, it comes up with a '2'. Is this the problem perhaps?

Used copy and paste to add the commander name and api key and everything else is working perfectly.

Any ideas?

Thanks in advance

**Comment by Juddz** [comment]
Sorry for being non-technical and taking up your time but what do I do with that?

**Comment by Marginal** [comment]
It means that it will be fixed in the next release.
Patience!

**Comment by Juddz** [comment]
lol Sorry! Didn't mean to rush you. Take your time and awesome work :)

**Comment by Marginal** [comment]
Fixed in Release 2.08.

**Comment by Juddz** [comment]
You are a demon. All working perfectly ¦:-)
Just one small problem mate; I can't find the link for donations. Not that I'm rich or anything but I have to make some kind of offer for one of the most amazing responses I've ever seen from a developer.

**Comment by Marginal** [comment]
I don't solicit donations, but [here's a Paypal link](https://www.paypal.me/Xant) if you'd like to.
