### ISSUE TITLE
Global shortcut key

### ISSUE THREAD

**Issue by watar** [Marginal/EDMarketConnector#9]
Would it be possible to add a keyboard shortcut for the update button?
That way I could add it to my voice command and instead of having to Alt-Tab out and press update at every station.

**Comment by Marginal** [comment]
The Return key is a shortcut. Is that not suitable?

**Comment by koreldan** [comment]
It works also if the app's window is not focused ?
It's possible to have some kind of sound feedback if 'return key' works as shortcut ?

anyway, if it's too hard to implement, doesn't matter, is just a comfort function.

**Comment by Marginal** [comment]
I'm looking into it

**Comment by koreldan** [comment]
I hope this link will help:
http://stackoverflow.com/questions/13806829/os-x-python-keylogger-letters-in-double

**Comment by Marginal** [comment]
Unfortunately the interaction between NSEvent addGlobalMonitorForEventsMatchingMask and Tkinter is causing a crash.

**Comment by Marginal** [comment]
Fixed in Release 1.74
