### ISSUE TITLE
Not outputting ship data

### ISSUE THREAD

**Issue by WaferMouse** [Marginal/EDMarketConnector#90]
Sometime over the most recent updates EDMC has stopped outputting ship data.  Everything else still works, just no new ship files getting added to the output folder.

**Comment by Marginal** [comment]
Ship loadouts are only written to the file location specified on the "Output" settings tab if:

- You have selected one of the "Ship loadout" options on the "Output" settings tab; and
- Your current ship loadout is different from the last saved loadout of that ship type.

**Comment by WaferMouse** [comment]
Ah, that makes sense.  Nothing to see here then!
