### ISSUE TITLE
After self-updating, the app doesn't relaunch

### ISSUE THREAD

**Issue by nemesyssoft** [Marginal/EDMarketConnector#93]
Both on Windows and Mac. Basically, when the app does an auto-update, after the update is downloaded, you're presented with a window that has one button labeled "Install and Relaunch". Well, it does the install but it never re-launches the app.

**Comment by Marginal** [comment]
Will be fixed in the next release on Windows.

On Mac the fact that it doesn't relaunch seems to be due to a race condition in [Sparkle](https://github.com/sparkle-project/Sparkle) that is proving difficult to track down.
