### ISSUE TITLE
Update showing previous station details.

### ISSUE THREAD

**Issue by badbud65** [Marginal/EDMarketConnector#95]
Traveled to a new system and then docked, UPDATED EDMC, but details shown are for previous station. Exited station, redocked same problem.

![edmc_error](https://cloud.githubusercontent.com/assets/4669127/13205924/85b5600e-d8eb-11e5-86ea-4b19e8a555af.png)

Travelled to another station in the same system and again EDMC shows details for previous station.

![next_station_shows_deatils_for_previous_station](https://cloud.githubusercontent.com/assets/4669127/13205931/9ef4e080-d8eb-11e5-9580-2f397ea181f9.png)

In between EDMC does recognise the system, but on UPDATE shows previous station.

![recognises_sytem_untill_i_update_it](https://cloud.githubusercontent.com/assets/4669127/13205936/af0e0cb2-d8eb-11e5-88e0-d555fdc0f119.png)

I've fully uninstalled EDMC, including clearing out all the folders, reinstalled, problem is still prevalent.

**Comment by Marginal** [comment]
Occasionally the servers hosting the Companion API that this app uses lag behind the game servers.
(Haven't personally seen it as bad as this 'though).

**Comment by badbud65** [comment]
I was at the first station in Khaka well over 1 hour before I went to the second station. I'll try tomorrow now.

**Comment by Marginal** [comment]
Probably related to [this](https://forums.frontier.co.uk/showthread.php?t=234139&page=4&p=3597492#post3597492) problem.

**Comment by badbud65** [comment]
Could be? Let's see what tomorrow brings.

**Comment by badbud65** [comment]
Your name 'marginal' now explains the registry entry under such a folder for EDMarketConector. 

Brilliant app by the way.

**Comment by Marginal** [comment]
Thx

**Comment by badbud65** [comment]
Hi, I can confirm that it was the server issues causing EDMC to get behind, good spot.
