### ISSUE TITLE
Window lost after monitor change

### ISSUE THREAD

**Issue by zolthan** [Marginal/EDMarketConnector#96]
Hi,

I have a really odd problem: I had to change my 2 monitor setup to just one monitor. My market connector was positioned on the 2nd monitor. Now if I start the EDMC, the window is not visible but it runs. I can see the Windows 10 preview if I hover the task icon, but I'm not able to access the EDMC.

How could I rest the window position? I already reinstalled the EDMC but it has no impact.

Please help :-)

Best
Sebastian

**Comment by Marginal** [comment]
Will be fixed in the next release. In the meantime:
- close the app
- run regedit
- delete the registry key `HKEY_CURRENT_USER\Software\Marginal\EDMarketConnector\geometry`
- re-start the app

**Comment by zolthan** [comment]
Perfect thanks so much
