### ISSUE TITLE
Unable to read market data from any station with Palladium supply

### ISSUE THREAD

**Issue by Aedesh** [Marginal/EDMarketConnector#97]
Issue:  When at a station with palladium supplies, clicking "Update" returns "Error reading market data." status message, and a 60 second cooldown.

I have experienced this on a number of reboots across a number of days.

The last station this occurred at was Manitola, Beer Platform.

My account is Horizons, single purchase, prior to the "Season Pass" change.

**Comment by Aedesh** [comment]
Disregard.  I now see there is a known issue regarding outposts, of which this is one.

**Comment by Marginal** [comment]
Duplicate of Issue #6.
