### ISSUE TITLE
Windows MSI assumes installation target in Program Files

### ISSUE THREAD

**Issue by draeath** [Marginal/EDMarketConnector#98]
The installer should allow the user to specify where to install. I don't know how to make that magic actually happen, but it's expected behavior on Windows platform installers to ask. The application itself seems to work fine when transplanted elsewhere.

**Comment by Marginal** [comment]
You can install it somewhere else using the standard(ish):
`msiexec /i "X:\path\to\EDMarketConnector_win_2.0.9.0.msi" INSTALLDIR="Y:\destination\folder"`

**Comment by draeath** [comment]
This is a workaround. The MSI installer UI should present a standard installation path dialog.

**Comment by Marginal** [comment]
Patches welcome, I guess.

**Comment by draeath** [comment]
Ah, looks like you're using the minimal installer UI. You would want to use [WixUI_InstallDir](http://wixtoolset.org/documentation/manual/v3/wixui/dialog_reference/wixui_installdir.html), I guess?

I could try building a patch for you, but I've no way to build the installer so would just be gambling and probably wasting your time.

**Comment by Marginal** [comment]
Yes, WixUI_InstallDir would be the way to go.

Plus the [build](https://github.com/Marginal/EDMarketConnector/blob/master/setup.py#L159) needs to be modified to create 13 (curently) [localized](http://wixtoolset.org/documentation/manual/v3/wixui/wixui_localization.html) .msi files and to glue them back together with transforms to make a multi-lingual .msi file.
